import type { TemplateSeed, TierKey } from "@/app/schema/templateSeed";
import { WM_ROUTES } from "@/core/wingman/routeMap";

export type RoomTemplateCategory =
  | "Corporate"
  | "Education"
  | "Public & Ops"
  | "Healthcare"
  | "Retail & Signage"
  | "Hospitality & Leisure"
  | "Residential"
  | "Worship";

export type RoomTemplateScenario = {
  id: string;
  category: RoomTemplateCategory;
  vertical: string;
  roomType: string;
  summary: string;
  story: string;
  designPurpose: string;
  templateTier: TierKey;
  recommendedFamilies: string[];
  recommendedTool: string;
  useCases: string[];
  sourceTypes: string[];
  outputTypes: string[];
  transportProfile: string;
  audioProfile: string;
  controlProfile: string;
  includedSystems: string[];
  assumptions: string[];
  uplift: string[];
  ioProfile: {
    sources: string;
    outputs: string;
    operators: string;
    sourceCount: number;
    displayCount: number;
  };
};

export const ROOM_TEMPLATE_CATEGORY_ORDER: Array<"All Rooms" | RoomTemplateCategory> = [
  "All Rooms",
  "Corporate",
  "Education",
  "Public & Ops",
  "Healthcare",
  "Retail & Signage",
  "Hospitality & Leisure",
  "Residential",
  "Worship",
];

export const ROOM_TEMPLATE_LIBRARY: RoomTemplateScenario[] = [
  {
    id: "uc-enabled-meeting-room",
    category: "Corporate",
    vertical: "Corporate",
    roomType: "UC Enabled Meeting Room",
    summary: "Collaboration-first meeting room with table BYOD, room USB peripherals, and one or two front-of-room displays.",
    story: "Designed for day-to-day Teams and Zoom meetings where the user journey matters more than routing scale.",
    designPurpose: "Preload a practical collaboration room with sensible source counts, display expectations, USB assumptions, and a WyreStorm-first meeting workflow.",
    templateTier: "silver",
    recommendedFamilies: ["Apollo", "USB Extension"],
    recommendedTool: WM_ROUTES.roomWizard,
    useCases: ["Teams room", "Zoom room", "Small board meeting", "Guest laptop presentation"],
    sourceTypes: ["USB-C laptop at table", "In-room UC PC or codec", "Wireless guest share"],
    outputTypes: ["Primary front display", "Optional confidence or second display"],
    transportProfile: "Short to medium in-room transport with a display-side collaboration core or tidy local rack handoff.",
    audioProfile: "USB camera or soundbar, table microphones, and soft-codec audio return are expected.",
    controlProfile: "Simple room control with input switching, display wake and sleep, and basic room presets.",
    includedSystems: ["Presentation and UC switcher", "USB host and peripheral extension", "Display transport", "Basic room control"],
    assumptions: ["Users expect self-serve operation", "USB-C ingest is more important than raw matrix scale", "Wireless guest presentation is desirable but not mandatory"],
    uplift: ["Easy room standard for repeat deployment", "Strong upsell path into better USB and wireless workflow", "Good fit for everyday hybrid meeting spaces"],
    ioProfile: {
      sources: "2 to 3 presentation and UC sources",
      outputs: "1 to 2 front-of-room displays",
      operators: "Presenter-led and self-serve",
      sourceCount: 3,
      displayCount: 2,
    },
  },
  {
    id: "executive-boardroom",
    category: "Corporate",
    vertical: "Corporate",
    roomType: "Executive Boardroom",
    summary: "Higher-finish meeting space with dual displays, table connectivity, rack integration, and stronger audio and control expectations.",
    story: "Built for executive meetings where reliability, polish, and simple control are expected from day one.",
    designPurpose: "Preload a boardroom-ready room with balanced source routing, dual-display assumptions, and room infrastructure that feels consultant-safe.",
    templateTier: "gold",
    recommendedFamilies: ["Apollo", "HDBaseT", "Matrix"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["Executive meetings", "Customer presentations", "Dual-display UC meetings", "Table BYOD with room peripherals"],
    sourceTypes: ["Table BYOD source", "In-room PC", "Dedicated UC appliance", "Guest HDMI input"],
    outputTypes: ["Dual front displays", "Optional overflow or confidence output"],
    transportProfile: "Structured cabling and a rack-based core are assumed, with longer installed routes than a huddle room.",
    audioProfile: "Ceiling or table microphones, reinforced speech, and cleaner integration into room audio are expected.",
    controlProfile: "Touch control, display power, source select, and room presets are part of the baseline experience.",
    includedSystems: ["Presentation switching core", "HDBaseT display transport", "USB and camera integration", "Audio DSP tie-in", "Room control"],
    assumptions: ["Dual displays are the norm", "Rack space is available", "The room is expected to feel premium and repeatable"],
    uplift: ["Consultant-friendly standard room type", "Supports more polished executive workflow", "Clear path into premium control and audio scope"],
    ioProfile: {
      sources: "4 room and guest presentation sources",
      outputs: "2 primary displays plus optional local confidence output",
      operators: "Self-serve users with executive polish",
      sourceCount: 4,
      displayCount: 2,
    },
  },
  {
    id: "divisible-meeting-room",
    category: "Corporate",
    vertical: "Corporate / Hospitality",
    roomType: "Divisible Meeting Room",
    summary: "Flexible room that can run as one larger space or two smaller spaces with shared or independent AV behaviour.",
    story: "This room type is about partition-aware routing and keeping the system understandable when the room shape changes.",
    designPurpose: "Preload a divisible-space starter with realistic source counts, zone-aware outputs, and switching assumptions that survive room combination.",
    templateTier: "gold",
    recommendedFamilies: ["Matrix", "HDBaseT"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["Partitionable training room", "Divisible meeting suite", "Hospitality breakout space", "Combined event mode"],
    sourceTypes: ["Presenter lectern", "In-room PC", "Guest HDMI source", "Wireless presentation source"],
    outputTypes: ["Zone A display", "Zone B display", "Combined-room mirrored mode", "Optional local confidence display"],
    transportProfile: "Structured cabling between rack and each partitioned zone is assumed from the start.",
    audioProfile: "Speech reinforcement and zone-aware audio handoff are likely even if DSP details are finalized later.",
    controlProfile: "Partition presets, source switching by zone, and combine or divide logic should be assumed early.",
    includedSystems: ["Matrix switching core", "Display zone transport", "Partition presets", "Room control", "Audio handoff"],
    assumptions: ["The room can operate in split or combined mode", "Independent switching by zone matters", "Control logic matters as much as transport"],
    uplift: ["Strong fit for flexible spaces", "Reduces redesign later when partitions are confirmed", "Supports cleaner proposal language for combined and divided use"],
    ioProfile: {
      sources: "4 shared and local sources",
      outputs: "2 to 4 displays depending on split and combined mode",
      operators: "Presenter-led with partition presets",
      sourceCount: 4,
      displayCount: 4,
    },
  },
  {
    id: "town-hall-all-hands-space",
    category: "Corporate",
    vertical: "Corporate",
    roomType: "Town Hall / All-Hands Space",
    summary: "Larger internal presentation space with multiple presentation sources, stage confidence, and distributed audience displays.",
    story: "The focus here is less about room-table collaboration and more about event-ready switching, transport, and audience confidence.",
    designPurpose: "Preload a larger presentation venue with multiple stage sources, audience displays, and transport assumptions that can scale cleanly.",
    templateTier: "gold",
    recommendedFamilies: ["Matrix", "AVoIP"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["All-hands briefing", "Company update", "Town hall presentation", "Large internal meeting"],
    sourceTypes: ["Presentation laptop", "Lectern PC", "Wireless guest share", "Media playback source"],
    outputTypes: ["Main audience display", "Stage confidence display", "Overflow or side displays"],
    transportProfile: "Longer runs and more than one display path push this toward structured distribution rather than a simple room switcher.",
    audioProfile: "Speech reinforcement and integration into house or installed audio are assumed.",
    controlProfile: "Operator-driven source selection and show-mode presets are likely.",
    includedSystems: ["Presentation switching", "Distributed display transport", "Confidence output handling", "Audio handoff", "Operator control"],
    assumptions: ["Audience viewing angles matter", "Presentation sources change frequently", "Confidence and audience feeds are not always identical"],
    uplift: ["Natural upsell from standard meeting space", "Supports event-ready proposal language", "Good candidate for future distributed AV growth"],
    ioProfile: {
      sources: "4 staged presentation and media sources",
      outputs: "3 audience and confidence display paths",
      operators: "Operator-assisted or presenter plus support staff",
      sourceCount: 4,
      displayCount: 3,
    },
  },
  {
    id: "school-classroom",
    category: "Education",
    vertical: "Education",
    roomType: "School Classroom",
    summary: "Daily teaching space with lectern teaching source, guest laptop input, and a predictable front-of-room display system.",
    story: "The room needs to be easy for staff, easy to repeat site-wide, and resilient enough for everyday teaching.",
    designPurpose: "Preload a classroom baseline with realistic teacher and guest inputs, one teaching display path, and practical control assumptions.",
    templateTier: "silver",
    recommendedFamilies: ["Apollo", "HDBaseT"],
    recommendedTool: WM_ROUTES.roomWizard,
    useCases: ["Teacher-led classroom", "Interactive flat panel room", "Secondary school classroom", "Primary classroom AV refresh"],
    sourceTypes: ["Teacher laptop or dock", "In-room teaching PC", "Guest HDMI source", "Visualiser or document camera"],
    outputTypes: ["Main display or projector", "Optional repeater display"],
    transportProfile: "Simple front-of-room transport is expected, with structured cabling where the display is fixed.",
    audioProfile: "Basic classroom amplification or soundbar-style support may be present but is usually not the main design driver.",
    controlProfile: "Straightforward source selection and display power control are more important than deep automation.",
    includedSystems: ["Presentation switcher", "Display transport", "Teacher connectivity", "Simple classroom control"],
    assumptions: ["Teachers need a repeatable user experience", "Guest connectivity happens regularly", "A single main display path covers most lessons"],
    uplift: ["Strong template for campus-wide refresh", "Easy to standardize across many rooms", "Clear upsell path into better teacher workflow"],
    ioProfile: {
      sources: "3 to 4 teacher and guest inputs",
      outputs: "1 main teaching display and optional repeater",
      operators: "Teacher-led and repeatable",
      sourceCount: 4,
      displayCount: 1,
    },
  },
  {
    id: "university-lecture-theatre",
    category: "Education",
    vertical: "Higher Education",
    roomType: "University Lecture Theatre",
    summary: "Larger teaching environment with lectern sources, program confidence, and more than one audience-facing display path.",
    story: "This room type is about lecturer confidence, multiple presentation sources, and reliable transport into a larger seating environment.",
    designPurpose: "Preload a lecture-theatre starting point with lectern workflow, multiple display destinations, and enough structure to support complex teaching delivery.",
    templateTier: "gold",
    recommendedFamilies: ["Matrix", "HDBaseT", "USB Extension"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["University lecture theatre", "Large seminar space", "Tiered teaching room", "Lecture capture-friendly teaching space"],
    sourceTypes: ["Lectern PC", "Presenter laptop", "Document camera", "Lecture capture feed", "Guest HDMI source"],
    outputTypes: ["Main projection or display", "Lectern confidence monitor", "Repeater or side screens"],
    transportProfile: "Longer installed routes and lectern-to-rack transport are assumed from the outset.",
    audioProfile: "Speech reinforcement, lecturer microphone, and integration into lecture capture or installed audio are common.",
    controlProfile: "Lectern control and show-ready presets matter more than consumer-style self-service simplicity.",
    includedSystems: ["Lecture switching core", "Lectern transport", "Confidence display handling", "Audio tie-in", "Control interface"],
    assumptions: ["Lectern is the command point", "Confidence monitoring is required", "Transport distance is not trivial"],
    uplift: ["Stronger fit for higher-ed estates", "Supports consultant-grade teaching spaces", "Ready for more advanced capture and confidence workflows"],
    ioProfile: {
      sources: "5 teaching, guest, and capture sources",
      outputs: "3 presentation and confidence display paths",
      operators: "Lecturer-led with support-ready control",
      sourceCount: 5,
      displayCount: 3,
    },
  },
  {
    id: "training-room-seminar-space",
    category: "Education",
    vertical: "Education / Corporate",
    roomType: "Training Room / Seminar Space",
    summary: "Instructor-led space with more than one teaching display, practical switching, and moderate infrastructure.",
    story: "This sits between a classroom and a divisible space, where clarity and repeatability matter as much as flexibility.",
    designPurpose: "Preload a practical training-room baseline with instructor inputs, secondary displays, and room-wide presentation assumptions.",
    templateTier: "silver",
    recommendedFamilies: ["Apollo", "Matrix"],
    recommendedTool: WM_ROUTES.roomWizard,
    useCases: ["Corporate training room", "Seminar space", "Instructor-led workshop room", "Learning lab"],
    sourceTypes: ["Instructor laptop", "In-room PC", "Guest source", "Visualiser or demo source"],
    outputTypes: ["Main teaching display", "Secondary display or repeater"],
    transportProfile: "Medium transport expectations with more than one display path but not yet a full distributed AV system.",
    audioProfile: "Instructor voice lift and presentation audio are common, with DSP detail often added later.",
    controlProfile: "Instructor-friendly source selection and presentation presets are usually enough.",
    includedSystems: ["Presentation switching", "Secondary display distribution", "Instructor connectivity", "Basic control"],
    assumptions: ["Instructor is the main operator", "Secondary viewing matters", "The room may need modest future scaling"],
    uplift: ["Good fit for repeat training environments", "Simple to explain commercially", "Supports a clean move into more complex routing later"],
    ioProfile: {
      sources: "4 instructor and guest sources",
      outputs: "2 teaching display paths",
      operators: "Instructor-led",
      sourceCount: 4,
      displayCount: 2,
    },
  },
  {
    id: "command-and-control-room",
    category: "Public & Ops",
    vertical: "Operations",
    roomType: "Command and Control Room",
    summary: "Operator-driven environment with many sources, several display surfaces, and a strong bias toward routed, scalable AV distribution.",
    story: "This room type is about visibility, operator control, and architecture that can tolerate change without rewiring the whole room.",
    designPurpose: "Preload a control-room starter with many-to-many routing, larger display assumptions, and enough structure to support operational review.",
    templateTier: "gold",
    recommendedFamilies: ["AVoIP", "Matrix", "Video Wall"],
    recommendedTool: WM_ROUTES.videowall,
    useCases: ["Security operations", "Network operations centre", "Traffic or utilities monitoring", "Mission-critical oversight room"],
    sourceTypes: ["Operator PCs", "Reference feeds", "Broadcast or network feeds", "Spare incident review source", "KVM-linked systems", "Video wall feed"],
    outputTypes: ["Operator wall displays", "Large overview display", "Video wall canvas", "Side support displays"],
    transportProfile: "Scalable routed AV over network is often the correct starting assumption because source and output relationships change over time.",
    audioProfile: "Audio is usually secondary to visibility but may include alarms, comms monitoring, or briefing playback.",
    controlProfile: "Operator presets, fast recall, and reliable routing control are baseline expectations.",
    includedSystems: ["AV over IP distribution", "Video wall processing", "Operator routing control", "KVM-aware design assumptions"],
    assumptions: ["Source to display relationships change frequently", "Operator oversight matters more than a single presenter workflow", "The room will evolve over time"],
    uplift: ["Clear path into scalable routed architecture", "Supports high-value operational proposals", "Good fit for future expansion and wall processing"],
    ioProfile: {
      sources: "6 to 8 operational and reference sources",
      outputs: "4 or more operator and overview display surfaces",
      operators: "Operator-driven and support-assisted",
      sourceCount: 6,
      displayCount: 4,
    },
  },
  {
    id: "council-chamber-hearing-room",
    category: "Public & Ops",
    vertical: "Public Sector",
    roomType: "Council Chamber / Hearing Room",
    summary: "Formal decision-making space with dais, public viewing, and reliable presentation routing for chamber proceedings.",
    story: "The system needs to look formal, behave predictably, and support a mix of presenters, committee members, and audience viewing.",
    designPurpose: "Preload a chamber-ready configuration with moderator or dais presentation, public displays, and measured control assumptions.",
    templateTier: "gold",
    recommendedFamilies: ["Matrix", "HDBaseT"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["Council chamber", "Public hearing room", "Committee room", "Civic decision space"],
    sourceTypes: ["Clerk or moderator PC", "Guest laptop", "Document or evidence feed", "Remote hearing or VC source"],
    outputTypes: ["Main chamber displays", "Public gallery repeater", "Dais confidence display"],
    transportProfile: "Installed cabling and rack integration are normally assumed even when the room feels relatively compact.",
    audioProfile: "Speech reinforcement and microphone tie-in are common requirements even if audio is specified separately.",
    controlProfile: "Moderator-led control and scene recall matter more than open self-service operation.",
    includedSystems: ["Matrix switching", "Display transport", "Confidence display handling", "Control presets", "Audio tie-in assumptions"],
    assumptions: ["The room has a formal operating pattern", "Public viewing may differ from moderator confidence", "Reliability matters more than novelty"],
    uplift: ["Strong fit for civic and committee environments", "Supports clean operating-mode language", "Easy to justify better control and routing resilience"],
    ioProfile: {
      sources: "4 formal presentation and VC sources",
      outputs: "3 chamber and gallery display paths",
      operators: "Moderator-led or support-assisted",
      sourceCount: 4,
      displayCount: 3,
    },
  },
  {
    id: "courtroom",
    category: "Public & Ops",
    vertical: "Justice",
    roomType: "Courtroom",
    summary: "Structured judicial room with evidence presentation, public displays, and controlled source routing.",
    story: "This room type values orderly operation, visibility of evidence, and predictable control over who sees what.",
    designPurpose: "Preload a courtroom baseline with evidence-source assumptions, multiple viewing surfaces, and controlled routing expectations.",
    templateTier: "gold",
    recommendedFamilies: ["Matrix", "HDBaseT"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["Courtroom modernisation", "Judicial chamber", "Evidence display room", "Hearing court"],
    sourceTypes: ["Court PC", "Evidence laptop", "Document or evidence source", "Remote hearing or VC source"],
    outputTypes: ["Judge display", "Public display", "Evidence or witness display"],
    transportProfile: "Rack-based transport and dependable wired pathways are more credible than ad hoc switching.",
    audioProfile: "Speech reinforcement and recording tie-in are likely but can remain higher-level assumptions at template stage.",
    controlProfile: "Control is structured and usually operator-managed or limited to approved room roles.",
    includedSystems: ["Evidence switching", "Display routing", "Structured transport", "Operator or clerk control"],
    assumptions: ["Evidence presentation must be controlled", "Different participants may need different visual emphasis", "The room should not rely on casual wireless-only workflow"],
    uplift: ["Better fit for evidence-led judicial rooms", "Supports more formal proposal language", "Reduces later redesign risk around source visibility"],
    ioProfile: {
      sources: "4 court and evidence sources",
      outputs: "3 controlled display destinations",
      operators: "Clerk or operator-managed",
      sourceCount: 4,
      displayCount: 3,
    },
  },
  {
    id: "telemedicine-consultation-room",
    category: "Healthcare",
    vertical: "Healthcare",
    roomType: "Telemedicine Consultation Room",
    summary: "Small clinical collaboration room for patient or clinician consultation, secure video calls, and practical local presentation.",
    story: "The design needs to feel clinically straightforward while supporting camera, microphone, and display workflow without friction.",
    designPurpose: "Preload a healthcare collaboration room with consultation-friendly inputs, one main display path, and realistic USB conferencing assumptions.",
    templateTier: "silver",
    recommendedFamilies: ["Apollo", "USB Extension"],
    recommendedTool: WM_ROUTES.roomWizard,
    useCases: ["Telemedicine room", "Clinical consultation room", "Secure VC consult space", "Small healthcare meeting room"],
    sourceTypes: ["Clinical laptop", "Room PC", "Video consultation source"],
    outputTypes: ["Main consultation display"],
    transportProfile: "Simple in-room transport is expected, but camera and USB behaviour must be assumed correctly.",
    audioProfile: "Camera, microphone, and consultation audio are critical even in a small room.",
    controlProfile: "Fast start, clean source switching, and simple call-ready operation matter most.",
    includedSystems: ["UC and presentation switcher", "USB peripheral path", "Display connectivity", "Basic control"],
    assumptions: ["The room is consultation-led", "USB peripherals matter", "The workflow should feel quick and low-friction for staff"],
    uplift: ["Clear fit for healthcare consult rooms", "Good path into repeatable clinic standards", "Easy to justify better USB handling"],
    ioProfile: {
      sources: "2 to 3 consultation and VC sources",
      outputs: "1 main consultation display",
      operators: "Clinician-led and self-serve",
      sourceCount: 3,
      displayCount: 1,
    },
  },
  {
    id: "clinical-review-room",
    category: "Healthcare",
    vertical: "Healthcare",
    roomType: "Clinical Review / MDT Room",
    summary: "Clinical team room for case review, shared imaging or data, and multi-source discussion across one or two main displays.",
    story: "The room is less about casual meeting-room use and more about clear visibility of important information during team review.",
    designPurpose: "Preload an MDT-friendly room with more than one source, dual-display expectations, and a practical review workflow.",
    templateTier: "gold",
    recommendedFamilies: ["Apollo", "Matrix"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["MDT meeting room", "Clinical review room", "Imaging discussion room", "Healthcare collaboration room"],
    sourceTypes: ["Review PC", "Guest laptop", "Imaging source", "Remote consult feed"],
    outputTypes: ["Primary review display", "Secondary comparison display"],
    transportProfile: "Medium transport assumptions with stronger source flexibility than a basic consult room.",
    audioProfile: "Speech reinforcement or better room microphone behaviour may be required depending on team size.",
    controlProfile: "Fast source switching and simple review presets are more important than advanced automation.",
    includedSystems: ["Presentation switching", "Dual-display routing", "Clinical review workflow", "Optional USB tie-in"],
    assumptions: ["Two displays improve comparison and review", "The room is used by several clinicians, not one primary owner", "Source switching must stay simple under time pressure"],
    uplift: ["Stronger fit for clinician collaboration", "Clear path into higher-value healthcare rooms", "More persuasive than a generic small meeting room template"],
    ioProfile: {
      sources: "4 clinical and guest review sources",
      outputs: "2 review displays",
      operators: "Clinician-led team use",
      sourceCount: 4,
      displayCount: 2,
    },
  },
  {
    id: "retail-showroom",
    category: "Retail & Signage",
    vertical: "Retail",
    roomType: "Retail Showroom",
    summary: "Customer-facing display environment with curated content, occasional live presentation, and multiple surfaces to keep aligned.",
    story: "The room is about visual impact and flexible content delivery rather than traditional table-based collaboration.",
    designPurpose: "Preload a showroom template with signage and presentation crossover, multiple display assumptions, and room-ready routing expectations.",
    templateTier: "gold",
    recommendedFamilies: ["AVoIP", "Matrix"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["Retail showroom", "Brand experience space", "Demonstration room", "Product launch environment"],
    sourceTypes: ["Media player", "Staff laptop", "Live demo source"],
    outputTypes: ["Feature display wall", "Secondary product displays", "Window or attract display"],
    transportProfile: "More than one display surface and changing content layouts make scalable routed distribution a sensible baseline.",
    audioProfile: "Program audio may be present, but display coordination is usually the main design driver.",
    controlProfile: "Staff-triggered presets and clean content switching are more useful than full room automation.",
    includedSystems: ["Distributed AV transport", "Multi-display routing", "Signage and demo source switching", "Preset recall"],
    assumptions: ["Displays do not always show the same thing", "Visual impact matters", "Content sources change between passive and live demo modes"],
    uplift: ["Strong fit for premium customer-facing spaces", "Good route into scalable distribution", "Supports better experiential proposals"],
    ioProfile: {
      sources: "3 showroom and demo sources",
      outputs: "3 to 4 coordinated display surfaces",
      operators: "Staff-led presets and launch modes",
      sourceCount: 3,
      displayCount: 4,
    },
  },
  {
    id: "reception-lobby-signage",
    category: "Retail & Signage",
    vertical: "Corporate / Retail",
    roomType: "Reception / Lobby Signage",
    summary: "Front-of-house signage or welcome environment with one primary content source and one or more visible display surfaces.",
    story: "This is usually about simple, reliable playback with enough flexibility to support branding, welcome content, or a modest feature wall.",
    designPurpose: "Preload a lobby signage starter with obvious playback assumptions, simple control expectations, and the option to grow into a feature wall.",
    templateTier: "bronze",
    recommendedFamilies: ["HDBaseT", "Video Wall"],
    recommendedTool: WM_ROUTES.catalogue,
    useCases: ["Corporate reception", "Lobby signage", "Welcome wall", "Visitor information display"],
    sourceTypes: ["Media player", "Local signage source"],
    outputTypes: ["Main lobby display", "Secondary side display", "Optional small feature wall"],
    transportProfile: "Often one content source with fixed routes, though the display surface can still justify stronger transport choices.",
    audioProfile: "Audio is usually light-touch or optional.",
    controlProfile: "Scheduling and basic display power behaviour are more important than interactive control.",
    includedSystems: ["Playback source", "Display transport", "Basic power and scheduling control"],
    assumptions: ["Content is centrally managed or slow-changing", "A simple operating model is preferred", "The space should look polished but remain easy to maintain"],
    uplift: ["Good first step into reception refresh", "Easy to quote and standardise", "Can expand into more visual-impact signage later"],
    ioProfile: {
      sources: "1 to 2 signage sources",
      outputs: "1 to 3 welcome display surfaces",
      operators: "Mostly unattended",
      sourceCount: 2,
      displayCount: 2,
    },
  },
  {
    id: "qsr-digital-menu-venue",
    category: "Retail & Signage",
    vertical: "Food Service",
    roomType: "QSR / Digital Menu Venue",
    summary: "Menu and promotional display environment with one or two playback sources feeding several repeated screens.",
    story: "The room is operational, fast-moving, and usually values repeatability over bespoke interaction.",
    designPurpose: "Preload a digital-menu venue with repeated-display assumptions, practical playback sources, and a straightforward distribution model.",
    templateTier: "silver",
    recommendedFamilies: ["Matrix", "HDBaseT"],
    recommendedTool: WM_ROUTES.catalogue,
    useCases: ["Quick-service restaurant", "Cafe menu boards", "Counter display zone", "Franchise signage refresh"],
    sourceTypes: ["Digital signage player", "Backup local source"],
    outputTypes: ["Repeated menu boards", "Promotional side display"],
    transportProfile: "A repeated source model is common, but display quantity still needs reliable structured transport.",
    audioProfile: "Audio is usually not central to the design unless promotional playback is requested.",
    controlProfile: "Simple scheduling and power control are usually sufficient.",
    includedSystems: ["Repeated-source distribution", "Display transport", "Basic scheduling and maintenance access"],
    assumptions: ["Most screens mirror content", "Playback is centrally managed", "Operational simplicity matters more than feature depth"],
    uplift: ["Useful for franchise rollouts", "Simple to standardize across venues", "Commercially clear repeat pattern"],
    ioProfile: {
      sources: "1 to 2 signage playback sources",
      outputs: "4 or more mirrored menu displays",
      operators: "Mostly unattended and centrally managed",
      sourceCount: 2,
      displayCount: 4,
    },
  },
  {
    id: "local-pub",
    category: "Hospitality & Leisure",
    vertical: "Hospitality",
    roomType: "Local Pub",
    summary: "Multi-screen hospitality venue with a small number of local sources feeding several wall displays and everyday switching needs.",
    story: "The goal is to make common pub AV feel organized, practical, and ready for daily sports and entertainment use.",
    designPurpose: "Preload a hospitality starter with repeated daily viewing, several screens, and transport assumptions that suit a typical pub layout.",
    templateTier: "silver",
    recommendedFamilies: ["Matrix", "HDBaseT"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["Neighbourhood pub", "Small hospitality bar", "Live sport venue", "Mixed entertainment and TV viewing"],
    sourceTypes: ["Broadcast receiver", "Media player", "Local guest source"],
    outputTypes: ["Bar displays", "Feature display", "Optional outdoor or side display"],
    transportProfile: "More than one screen and mixed viewing positions make a rack-centred distribution model sensible.",
    audioProfile: "Program audio often exists, but the visual routing usually leads the conversation.",
    controlProfile: "Staff need quick source changes without a complicated operating model.",
    includedSystems: ["Rack-based switching", "Multi-screen transport", "Staff control interface", "Program source distribution"],
    assumptions: ["Several displays mirror or share a small source pool", "Staff need fast, understandable switching", "The venue may add more screens later"],
    uplift: ["Strong fit for recurring hospitality work", "Clear path from simple pub to larger venue", "Straightforward sports-viewing proposition"],
    ioProfile: {
      sources: "3 local program and guest sources",
      outputs: "5 to 6 hospitality displays",
      operators: "Staff-led daily operation",
      sourceCount: 3,
      displayCount: 6,
    },
  },
  {
    id: "sports-bar-entertainment-venue",
    category: "Hospitality & Leisure",
    vertical: "Hospitality / Entertainment",
    roomType: "Multi-Level Sports Bar and Entertainment Venue",
    summary: "Larger hospitality environment with many screens, multiple source pools, and routing that can change by floor, zone, or event.",
    story: "This is a distribution-led venue where the architecture should be chosen for scale and operational flexibility, not just today's display count.",
    designPurpose: "Preload a larger hospitality venue with zone-aware AV distribution, many displays, and clear assumptions around scalable routed AV.",
    templateTier: "gold",
    recommendedFamilies: ["AVoIP", "Matrix"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["Sports bar", "Multi-level venue", "Entertainment venue", "Event-driven hospitality venue"],
    sourceTypes: ["Broadcast receivers", "Media playback sources", "DJ or stage feed", "Guest presentation source", "Signage source", "Backup local feed"],
    outputTypes: ["Bar displays by zone", "Feature walls", "Large-format promo screens", "VIP or private-area displays"],
    transportProfile: "Scalable AV over network is usually the more credible baseline because display groups and event modes change often.",
    audioProfile: "Program audio and entertainment feeds are commonly part of the wider venue scope even when specified separately.",
    controlProfile: "Staff presets, event modes, and zone control matter more than simple fixed routing.",
    includedSystems: ["AV over IP distribution", "Zone routing", "Event presets", "Venue control assumptions", "Multi-zone source management"],
    assumptions: ["The venue runs different modes through the week", "Not every screen shows the same source", "Additional displays and zones are likely over time"],
    uplift: ["High-value hospitality proposition", "Justifies scalable architecture early", "Supports future growth without redesigning the venue backbone"],
    ioProfile: {
      sources: "6 to 8 live, broadcast, and signage sources",
      outputs: "12 or more displays across several zones",
      operators: "Staff-led presets with support-ready routing",
      sourceCount: 8,
      displayCount: 12,
    },
  },
  {
    id: "hotel-ballroom-event-space",
    category: "Hospitality & Leisure",
    vertical: "Hospitality / Events",
    roomType: "Hotel Ballroom / Event Space",
    summary: "Event-driven room with flexible staging, presentation sources, distributed displays, and mode changes between conference and hospitality use.",
    story: "The design needs to accommodate staging and event variation, not just a fixed room pattern.",
    designPurpose: "Preload a ballroom-ready event starter with more sources, more displays, and realistic support for show modes and flexible use.",
    templateTier: "gold",
    recommendedFamilies: ["Matrix", "AVoIP"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["Hotel ballroom", "Banqueting suite", "Conference event room", "Hospitality presentation space"],
    sourceTypes: ["Presentation laptop", "In-room event rack source", "Stage feed", "Media playback source", "Guest HDMI source"],
    outputTypes: ["Main projection or LED wall", "Comfort monitors", "Repeater displays", "Overflow feed"],
    transportProfile: "Longer runs and changing event layouts often push this beyond a simple room switcher discussion.",
    audioProfile: "Event audio is almost always relevant, even if the detailed design lives elsewhere.",
    controlProfile: "Operator-led presets and event modes are baseline expectations.",
    includedSystems: ["Event switching core", "Distributed display transport", "Confidence outputs", "Operator control assumptions"],
    assumptions: ["Room modes change between event types", "Staging and viewing positions vary", "Support staff are likely involved in operation"],
    uplift: ["Good fit for hotel AV refresh and expansion", "Supports premium event-ready proposals", "Clear bridge into larger hospitality design work"],
    ioProfile: {
      sources: "5 staged and guest presentation sources",
      outputs: "4 event and confidence display paths",
      operators: "Operator-led with event support staff",
      sourceCount: 5,
      displayCount: 4,
    },
  },
  {
    id: "home-cinema-media-room",
    category: "Residential",
    vertical: "Residential",
    roomType: "Home Cinema / Media Room",
    summary: "Residential media space with several local sources, one primary viewing surface, and stronger expectations around presentation quality.",
    story: "This is a comfort-first, quality-first environment where route simplicity and image confidence usually win over enterprise-style flexibility.",
    designPurpose: "Preload a residential viewing room with sensible local source assumptions, one main display path, and practical switching logic.",
    templateTier: "silver",
    recommendedFamilies: ["Matrix", "HDBaseT"],
    recommendedTool: WM_ROUTES.catalogue,
    useCases: ["Home cinema", "Residential media room", "Private lounge viewing room", "High-end family entertainment space"],
    sourceTypes: ["Streaming player", "Set-top box", "Games console", "Local media source"],
    outputTypes: ["Projector or main display", "Optional mirrored local repeater"],
    transportProfile: "The design is usually local or same-room, but clean transport and source quality still matter.",
    audioProfile: "Program audio is central to the room and usually specified as part of the wider system design.",
    controlProfile: "Simple source selection and scene recall are more valuable than operational complexity.",
    includedSystems: ["Source switching", "Display transport", "Residential control assumptions"],
    assumptions: ["The room is quality-led", "Most sources are fixed", "One main viewing surface dominates the design"],
    uplift: ["Good fit for premium residential viewing", "Easy to position around performance and finish", "Practical baseline for local rack design"],
    ioProfile: {
      sources: "4 fixed media sources",
      outputs: "1 main display path and optional mirrored local output",
      operators: "Owner-led with simple control scenes",
      sourceCount: 4,
      displayCount: 1,
    },
  },
  {
    id: "house-of-worship-sanctuary",
    category: "Worship",
    vertical: "Worship",
    roomType: "House of Worship / Sanctuary",
    summary: "Presentation and program environment with stage-driven sources, one main audience display path, and support for additional confidence or overflow viewing.",
    story: "This room type is about keeping stage content visible and dependable without turning a worship space into a generic meeting room.",
    designPurpose: "Preload a sanctuary starter with stage-led source assumptions, audience display expectations, and a path toward larger routed AV if needed.",
    templateTier: "gold",
    recommendedFamilies: ["Matrix", "AVoIP"],
    recommendedTool: WM_ROUTES.proposals,
    useCases: ["Church sanctuary", "Worship hall", "Stage-led presentation space", "Overflow-capable worship venue"],
    sourceTypes: ["Presentation PC", "Lyrics or media playback source", "Guest HDMI source", "Live production feed", "Streaming or recording feed"],
    outputTypes: ["Main projection or LED display", "Stage confidence display", "Overflow or foyer feed"],
    transportProfile: "The space often benefits from structured or scalable distribution once confidence and overflow feeds are included.",
    audioProfile: "Program and speech audio are normally significant, even if the detailed audio design is handled separately.",
    controlProfile: "Operator-led scenes and service presets are common and should be assumed early.",
    includedSystems: ["Presentation routing", "Confidence feed handling", "Overflow-ready transport", "Operator control assumptions"],
    assumptions: ["Stage content may differ from audience confidence", "Services run to presets", "The venue may grow into broader distributed AV over time"],
    uplift: ["Clear fit for stage-led venues", "Supports future overflow and streaming growth", "More persuasive than treating the space as a generic hall"],
    ioProfile: {
      sources: "5 stage, media, and streaming sources",
      outputs: "3 audience, confidence, and overflow display paths",
      operators: "Operator-led service presets",
      sourceCount: 5,
      displayCount: 3,
    },
  },
];

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

function labelForTier(tier: TierKey): "Bronze" | "Silver" | "Gold" {
  if (tier === "bronze") return "Bronze";
  if (tier === "gold") return "Gold";
  return "Silver";
}

export function buildWorkbenchTemplateSeed(template: RoomTemplateScenario): TemplateSeed {
  return {
    source: "template-workbench",
    verticalMarket: {
      id: slug(template.vertical),
      name: template.vertical,
      summary: `${template.vertical} room template starter.`,
    },
    roomType: {
      id: template.id,
      name: template.roomType,
      summary: template.summary,
      story: template.story,
      designPurpose: template.designPurpose,
      useCases: template.useCases,
    },
    tier: {
      id: template.templateTier,
      label: labelForTier(template.templateTier),
      summary: template.summary,
      positioning: template.story,
      performance: template.transportProfile,
      commercialNote: template.uplift.join("; "),
    },
    includedSystems: template.includedSystems,
    uplift: template.uplift,
    assumptions: [
      `Inputs: ${template.ioProfile.sources}`,
      `Outputs: ${template.ioProfile.outputs}`,
      `Operators: ${template.ioProfile.operators}`,
      `Transport: ${template.transportProfile}`,
      `Audio: ${template.audioProfile}`,
      `Control: ${template.controlProfile}`,
      ...template.assumptions,
    ],
    recommendedFamilies: template.recommendedFamilies,
    recommendedTool: template.recommendedTool,
    solutionSummary: template.designPurpose,
    ioProfile: template.ioProfile,
    projectName: `${template.roomType} Project`,
    createdAt: new Date().toISOString(),
  };
}

export function roomTemplateSearchBlob(template: RoomTemplateScenario): string {
  return [
    template.category,
    template.vertical,
    template.roomType,
    template.summary,
    template.story,
    template.designPurpose,
    ...template.useCases,
    ...template.sourceTypes,
    ...template.outputTypes,
    ...template.recommendedFamilies,
    ...template.includedSystems,
  ]
    .join(" ")
    .toLowerCase();
}
