import type {
  AvoipSubtype,
  ComparisonDomain,
  ComparisonHints,
  ComparisonUseCase,
  DeviceRole,
  HdbtGeneration,
  TransportClass,
} from "./types";

export type FamilyRule = {
  id: string;
  skuPattern: RegExp;
  brandPattern?: RegExp;
  transport?: TransportClass;
  avoipSubtype?: AvoipSubtype;
  hdbtGeneration?: HdbtGeneration;
  role?: DeviceRole;
  multiview?: boolean;
  comparisonDomain?: ComparisonDomain;
  comparisonUseCase?: ComparisonUseCase;
  comparisonHints?: ComparisonHints;
  notes?: string;
};

const MATRIX_HINTS: ComparisonHints = {
  preferredDomains: ["MATRIX"],
  preferredUseCases: ["ROUTING"],
  avoidDomains: ["PRESENTATION", "EXTENDER", "VIDEO_WALL"],
  avoidUseCases: ["COLLABORATION", "EXTENSION", "WALL_PROCESSING"],
  rankLowerUseCases: ["DISTRIBUTION"],
};

const PRESENTATION_HINTS: ComparisonHints = {
  preferredDomains: ["PRESENTATION"],
  preferredUseCases: ["COLLABORATION", "ROUTING"],
  avoidDomains: ["EXTENDER", "VIDEO_WALL"],
  avoidUseCases: ["EXTENSION", "WALL_PROCESSING"],
  rankLowerUseCases: ["DISTRIBUTION"],
};

const AVOIP_HINTS: ComparisonHints = {
  preferredDomains: ["AVOIP"],
  preferredUseCases: ["DISTRIBUTION"],
  avoidDomains: ["EXTENDER", "VIDEO_WALL"],
  avoidUseCases: ["EXTENSION", "WALL_PROCESSING"],
  rankLowerUseCases: ["COLLABORATION"],
};

const EXTENDER_HINTS: ComparisonHints = {
  preferredDomains: ["EXTENDER"],
  preferredUseCases: ["EXTENSION"],
  avoidDomains: ["AVOIP", "MATRIX", "PRESENTATION", "VIDEO_WALL"],
  avoidUseCases: [
    "DISTRIBUTION",
    "COLLABORATION",
    "ROUTING",
    "MULTIVIEW",
    "WALL_PROCESSING",
  ],
  rankLowerUseCases: [],
};

const WALL_HINTS: ComparisonHints = {
  preferredDomains: ["VIDEO_WALL", "AVOIP"],
  preferredUseCases: ["WALL_PROCESSING", "MULTIVIEW"],
  avoidDomains: ["EXTENDER"],
  avoidUseCases: ["EXTENSION"],
  rankLowerUseCases: ["DISTRIBUTION", "COLLABORATION"],
};

const CONTROL_HINTS: ComparisonHints = {
  preferredDomains: ["CONTROL"],
  preferredUseCases: ["CONTROL"],
  avoidDomains: ["AVOIP", "MATRIX", "PRESENTATION", "EXTENDER", "VIDEO_WALL"],
  avoidUseCases: ["DISTRIBUTION", "COLLABORATION", "ROUTING", "MULTIVIEW", "WALL_PROCESSING", "EXTENSION"],
  rankLowerUseCases: [],
};

export const FAMILY_RULES: FamilyRule[] = [
  {
    id: "wyrestorm-nhd-150-rx",
    skuPattern: /^NHD-150-RX/i,
    transport: "AVOIP",
    avoipSubtype: "MULTIVIEW",
    role: "MULTIVIEW_DECODER",
    multiview: true,
    comparisonDomain: "AVOIP",
    comparisonUseCase: "MULTIVIEW",
    comparisonHints: WALL_HINTS,
    notes: "WyreStorm NHD-150-RX is multiview-specific.",
  },
  {
    id: "wyrestorm-nhd-100-series",
    skuPattern: /^NHD-(100|110|120|140)/i,
    transport: "AVOIP",
    avoipSubtype: "JPEG2000",
    role: "DECODER",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
  },
  {
    id: "wyrestorm-AVoIP-series",
    skuPattern: /^NHD-2\d{2}/i,
    transport: "AVOIP",
    avoipSubtype: "JPEG2000",
    role: "DECODER",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
  },
  {
    id: "wyrestorm-nhd-500-series",
    skuPattern: /^NHD-5\d{2}/i,
    transport: "AVOIP",
    avoipSubtype: "JPEG2000",
    role: "DECODER",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
  },
  {
    id: "wyrestorm-nhd-600-series",
    skuPattern: /^NHD-6\d{2}/i,
    transport: "AVOIP",
    avoipSubtype: "JPEG2000",
    role: "ENCODER",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
  },
  {
    id: "wyrestorm-video-wall",
    skuPattern: /^SW-02(04|06)-VW/i,
    transport: "HDMI_DISTRIBUTION",
    role: "SWITCHER",
    comparisonDomain: "VIDEO_WALL",
    comparisonUseCase: "WALL_PROCESSING",
    comparisonHints: WALL_HINTS,
    notes: "WyreStorm SW-0204-VW and SW-0206-VW are dedicated video wall processors.",
  },
  {
    id: "wyrestorm-nhd-0401-mv",
    skuPattern: /^NHD-0401-MV/i,
    transport: "AVOIP",
    avoipSubtype: "MULTIVIEW",
    role: "MULTIVIEW_DECODER",
    multiview: true,
    comparisonDomain: "VIDEO_WALL",
    comparisonUseCase: "MULTIVIEW",
    comparisonHints: WALL_HINTS,
    notes: "NHD-0401-MV is the wall-feed compositor for multiview use cases.",
  },
  {
    id: "wyrestorm-sw-tx3",
    skuPattern: /^SW-.*TX3/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_3_0",
    role: "ENCODER",
    comparisonDomain: "EXTENDER",
    comparisonUseCase: "EXTENSION",
    comparisonHints: EXTENDER_HINTS,
  },
  {
    id: "wyrestorm-sw-rx3",
    skuPattern: /^SW-.*RX3/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_3_0",
    role: "DECODER",
    comparisonDomain: "EXTENDER",
    comparisonUseCase: "EXTENSION",
    comparisonHints: EXTENDER_HINTS,
  },
  {
    id: "extron-presentation-switcher",
    skuPattern: /\b(?:IN\d{4}|DTP(?:3)?\s+T\s+USW)\b/i,
    brandPattern: /\bExtron\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Presentation switcher for room staging and collaboration. Compare to Apollo-style workflows, not to pure matrices.",
  },
  {
    id: "extron-dtp-t",
    skuPattern: /\bDTP(?:3)?\s+T\s+\d{3}\b/i,
    brandPattern: /\bExtron\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "ENCODER",
    comparisonDomain: "EXTENDER",
    comparisonUseCase: "EXTENSION",
    comparisonHints: EXTENDER_HINTS,
    notes: "Point-to-point DTP transmitter. Compare as an extender, not as a matrix or AVoIP endpoint.",
  },
  {
    id: "extron-dtp-r",
    skuPattern: /\bDTP(?:3)?\s+R\s+\d{3}\b/i,
    brandPattern: /\bExtron\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "DECODER",
    comparisonDomain: "EXTENDER",
    comparisonUseCase: "EXTENSION",
    comparisonHints: EXTENDER_HINTS,
    notes: "Point-to-point DTP receiver. Compare on extension distance, loop-through, and control pass-through.",
  },
  {
    id: "extron-crosspoint-dtp3",
    skuPattern: /\bDTP3\s+CrossPoint\b/i,
    brandPattern: /\bExtron\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_3_0",
    role: "MATRIX",
    comparisonDomain: "MATRIX",
    comparisonUseCase: "ROUTING",
    comparisonHints: MATRIX_HINTS,
    notes: "Presentation matrix with DTP3 extension and scaling. Compare as a matrix-led system.",
  },
  {
    id: "extron-crosspoint-dtp",
    skuPattern: /\bDTP\s+CrossPoint\b/i,
    brandPattern: /\bExtron\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "MATRIX",
    comparisonDomain: "MATRIX",
    comparisonUseCase: "ROUTING",
    comparisonHints: MATRIX_HINTS,
    notes: "Presentation matrix with DTP extension and scaling. Separate matrix core from extension endpoints.",
  },
  {
    id: "extron-nav",
    skuPattern: /\bNAV\b/i,
    brandPattern: /\bExtron\b/i,
    transport: "AVOIP",
    avoipSubtype: "PROPRIETARY",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
    notes: "NAV is an endpoint-based AV over IP ecosystem. Compare using encoder, decoder, controller, and network speed roles.",
  },
  {
    id: "extron-mgp",
    skuPattern: /\bMGP\b|\bWindoWall\b/i,
    brandPattern: /\bExtron\b/i,
    role: "SWITCHER",
    multiview: true,
    comparisonDomain: "VIDEO_WALL",
    comparisonUseCase: "MULTIVIEW",
    comparisonHints: WALL_HINTS,
    notes: "Multiview processor for one-canvas or one-wall compositions. Compare against wall processors and multiview workflows.",
  },
  {
    id: "crestron-nvx",
    skuPattern: /\bNVX\b/i,
    brandPattern: /\bCrestron\b/i,
    transport: "AVOIP",
    avoipSubtype: "PROPRIETARY",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
  },
  {
    id: "crestron-nvx-385c",
    skuPattern: /^DM-NVX-385C/i,
    brandPattern: /\bCrestron\b/i,
    transport: "AVOIP",
    avoipSubtype: "PROPRIETARY",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Crestron DM-NVX-385C is collaboration-heavy with USB-C and 5K support, so it should compare against UC/presentation systems rather than a plain decoder.",
  },
  {
    id: "crestron-dm-md",
    skuPattern: /\bDM-MD\d+X\d+\b/i,
    brandPattern: /\bCrestron\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "MATRIX",
    comparisonDomain: "MATRIX",
    comparisonUseCase: "ROUTING",
    comparisonHints: MATRIX_HINTS,
    notes: "Crestron DM-MD is a modular matrix chassis, not a fixed HDMI switcher.",
  },
  {
    id: "crestron-dmps3",
    skuPattern: /\bDMPS3\b/i,
    brandPattern: /\bCrestron\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Crestron DMPS3 is a presentation system with integrated control and matrix-like routing.",
  },
  {
    id: "crestron-hd-ps",
    skuPattern: /\bHD-PS\d+\b/i,
    brandPattern: /\bCrestron\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Crestron HD-PS is a room presentation system, not an AVoIP wall platform.",
  },
  {
    id: "atlona-omni",
    skuPattern: /\bOMNI\b/i,
    brandPattern: /\bAtlona\b/i,
    transport: "AVOIP",
    avoipSubtype: "PROPRIETARY",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
  },
  {
    id: "atlona-omni-usb",
    skuPattern: /\bAT-OMNI-(311|324)\b/i,
    brandPattern: /\bAtlona\b/i,
    transport: "USB_EXTENSION",
    role: "EXTENDER_RX",
    comparisonDomain: "EXTENDER",
    comparisonUseCase: "EXTENSION",
    comparisonHints: EXTENDER_HINTS,
    notes: "Atlona OmniStream USB adapters should compare as USB extension, not as video AVoIP endpoints.",
  },
  {
    id: "atlona-ome",
    skuPattern: /\bOME\b/i,
    brandPattern: /\bAtlona\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
  },
  {
    id: "atlona-omega-cs",
    skuPattern: /\bOME-CS\d+/i,
    brandPattern: /\bAtlona\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Omega CS family is the collaboration-first meeting-room switcher line with USB-C, HDMI, and HDBaseT integration.",
  },
  {
    id: "atlona-omega-ms",
    skuPattern: /\bOME-MS\d+/i,
    brandPattern: /\bAtlona\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "ROUTING",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Omega MS family is a matrix presentation switcher line; compare it as a collaboration matrix, not a pure HDMI matrix.",
  },
  {
    id: "atlona-omega-ps",
    skuPattern: /\bOME-PS\d+/i,
    brandPattern: /\bAtlona\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "MATRIX",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "ROUTING",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Omega PS family is the lecture-hall / presentation matrix line with local and remote AV plus USB extension.",
  },
  {
    id: "atlona-omega-sw",
    skuPattern: /\bOME-SW\d+/i,
    brandPattern: /\bAtlona\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "ROUTING",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Omega SW family is a compact presentation switcher line for BYOD and classroom workflows.",
  },
  {
    id: "atlona-omega-ex",
    skuPattern: /\bOME-EX/i,
    brandPattern: /\bAtlona\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "EXTENDER_TX",
    comparisonDomain: "EXTENDER",
    comparisonUseCase: "EXTENSION",
    comparisonHints: EXTENDER_HINTS,
    notes: "Omega EX family is Atlona's HDBaseT extender layer and should compare as extension rather than routing.",
  },
  {
    id: "atlona-velocity",
    skuPattern: /\bV(?:KP|TPG|TP|GW|PS|VPS|OCS)\b/i,
    brandPattern: /\bAtlona\b/i,
    transport: "UNKNOWN",
    comparisonDomain: "CONTROL",
    comparisonUseCase: "CONTROL",
    comparisonHints: CONTROL_HINTS,
    notes: "Velocity family products are room control, scheduling, and automation devices, not AV transport endpoints.",
  },
  {
    id: "kramer-kds",
    skuPattern: /\bKDS\b/i,
    brandPattern: /\bKramer\b/i,
    transport: "AVOIP",
    avoipSubtype: "H264_H265",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
  },
  {
    id: "kramer-via",
    skuPattern: /\bVIA\b/i,
    brandPattern: /\bKramer\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Kramer VIA is a wireless collaboration family, so compare it against BYOD and meeting-room workflows.",
  },
  {
    id: "kramer-vs-matrix",
    skuPattern: /\bVS-\d+H2A\b/i,
    brandPattern: /\bKramer\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "MATRIX",
    comparisonDomain: "MATRIX",
    comparisonUseCase: "ROUTING",
    comparisonHints: MATRIX_HINTS,
    notes: "Kramer VS matrix products should be compared as fixed HDMI matrices, not presentation systems.",
  },
  {
    id: "lightware-ubex",
    skuPattern: /\bUBEX\b/i,
    brandPattern: /\bLightware\b/i,
    transport: "AVOIP",
    avoipSubtype: "SDVOE",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
    notes: "Lightware UBEX is premium 10G AV-over-IP; compare against high-performance AVoIP, not a matrix or presentation box.",
  },
  {
    id: "lightware-vinx",
    skuPattern: /\bVINX\b/i,
    brandPattern: /\bLightware\b/i,
    transport: "AVOIP",
    avoipSubtype: "JPEG2000",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
    notes: "Lightware VINX is a 1G virtual matrix AVoIP family.",
  },
  {
    id: "lightware-ucx",
    skuPattern: /\bUCX\b/i,
    brandPattern: /\bLightware\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Lightware UCX is a collaboration matrix with USB-C and host switching, not a plain HDMI matrix.",
  },
  {
    id: "lightware-mx2",
    skuPattern: /\bMX2\b/i,
    brandPattern: /\bLightware\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "MATRIX",
    comparisonDomain: "MATRIX",
    comparisonUseCase: "ROUTING",
    comparisonHints: MATRIX_HINTS,
    notes: "Lightware MX2 is a conventional HDMI matrix family.",
  },
  {
    id: "lightware-tpx",
    skuPattern: /\bTPX\b/i,
    brandPattern: /\bLightware\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "EXTENDER_TX",
    comparisonDomain: "EXTENDER",
    comparisonUseCase: "EXTENSION",
    comparisonHints: EXTENDER_HINTS,
    notes: "Lightware TPX is a point-to-point extender family.",
  },
  {
    id: "lightware-tps",
    skuPattern: /\bTPS\b/i,
    brandPattern: /\bLightware\b/i,
    transport: "HDBASET",
    hdbtGeneration: "HDBT_2_0",
    role: "EXTENDER_TX",
    comparisonDomain: "EXTENDER",
    comparisonUseCase: "EXTENSION",
    comparisonHints: EXTENDER_HINTS,
    notes: "Lightware TPS is a long-reach extender family.",
  },
  {
    id: "blustream-ip300",
    skuPattern: /\bIP300UHD\b/i,
    brandPattern: /\bBlustream\b/i,
    transport: "AVOIP",
    avoipSubtype: "PROPRIETARY",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
    notes: "Blustream IP300UHD is a 1G compressed AV-over-IP family with wall and KVM options.",
  },
  {
    id: "blustream-ip350",
    skuPattern: /\bIP350UHD\b/i,
    brandPattern: /\bBlustream\b/i,
    transport: "AVOIP",
    avoipSubtype: "PROPRIETARY",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
    notes: "Blustream IP350UHD is the Dante-enabled AV-over-IP tier; treat it as a premium AVoIP distribution family.",
  },
  {
    id: "blustream-wmf",
    skuPattern: /\bWMF(?:72|USBC-D|HDMI-D)\b/i,
    brandPattern: /\bBlustream\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Blustream WMF is a wireless collaboration switcher family with dual HDMI output and BYOD-centric controls.",
  },
  {
    id: "blustream-sw41",
    skuPattern: /\bSW41AB-V2\b/i,
    brandPattern: /\bBlustream\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Blustream SW41AB-V2 is a compact multiformat presentation switcher, not a matrix or AVoIP endpoint.",
  },
  {
    id: "blustream-uex3c",
    skuPattern: /\bUEX3C-KIT\b/i,
    brandPattern: /\bBlustream\b/i,
    transport: "USB_EXTENSION",
    role: "EXTENDER_TX",
    comparisonDomain: "EXTENDER",
    comparisonUseCase: "EXTENSION",
    comparisonHints: EXTENDER_HINTS,
    notes: "Blustream UEX3C-KIT is a USB extender kit and should compare against USB extension, not video transport.",
  },
  {
    id: "zeevee-zyper-uhd60",
    skuPattern: /\bZUHD60\b|\bZyPerUHD60\b/i,
    brandPattern: /\bZeeVee\b/i,
    transport: "AVOIP",
    avoipSubtype: "JPEG2000",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
    notes: "ZeeVee ZyPerUHD60 is the 1G compressed distribution tier with built-in wall support and collaboration-friendly options.",
  },
  {
    id: "zeevee-zyper4k",
    skuPattern: /\b(?:ZY-4K-(?:ENC|DEC)|Z4KDEC\w+|Z4KENC\w+)\b/i,
    brandPattern: /\bZeeVee\b/i,
    transport: "AVOIP",
    avoipSubtype: "SDVOE",
    comparisonDomain: "AVOIP",
    comparisonUseCase: "DISTRIBUTION",
    comparisonHints: AVOIP_HINTS,
    notes: "ZeeVee ZyPer4K is the premium 10G uncompressed SDVoE tier with multiview and video-wall support.",
  },
  {
    id: "zeevee-z4kmp48",
    skuPattern: /\bZ4KMP48\b/i,
    brandPattern: /\bZeeVee\b/i,
    transport: "UNKNOWN",
    comparisonDomain: "CONTROL",
    comparisonUseCase: "CONTROL",
    comparisonHints: CONTROL_HINTS,
    notes: "ZeeVee Z4KMP48 is an AV over IP management platform, not a transport endpoint.",
  },
  {
    id: "barco-clickshare",
    skuPattern: /\bClickShare\b|\bC-\d+\b|\bCX-\d+\b|\bVideo Bar Pro\b/i,
    brandPattern: /\bBarco\b/i,
    transport: "HDMI_DISTRIBUTION",
    role: "SWITCHER",
    comparisonDomain: "PRESENTATION",
    comparisonUseCase: "COLLABORATION",
    comparisonHints: PRESENTATION_HINTS,
    notes: "Barco ClickShare is a BYOD / conferencing family; compare against meeting-room collaboration workflows.",
  },
];
