# tools/fix-nav-and-comparison.ps1
# Fixes:
# 1) src/data/navigation.ts: remove invalid TOOLS section object and add orphan routes as flat NavItem entries
# 2) src/pages/ComparisonPage.tsx: remove PageHeader eyebrow prop
#
# Run:
#   pwsh -NoProfile -ExecutionPolicy Bypass -File tools\fix-nav-and-comparison.ps1
#   npm run typecheck

$ErrorActionPreference = "Stop"

function Backup-File([string]$path) {
  if (Test-Path -LiteralPath $path) {
    $stamp = Get-Date -Format "yyyyMMdd_HHmmss"
    Copy-Item -LiteralPath $path -Destination ($path + ".bak_" + $stamp) -Force
    Write-Host ("Backup: {0}.bak_{1}" -f $path, $stamp)
  }
}

function WriteUtf8NoBom([string]$path, [string]$content) {
  $dir = Split-Path -Parent $path
  if ($dir -and !(Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  [IO.File]::WriteAllText($path, $content, (New-Object System.Text.UTF8Encoding($false)))
  Write-Host ("Wrote: {0}" -f $path)
}

function Require-RepoRoot() {
  if (!(Test-Path -LiteralPath "package.json")) {
    throw "Run this from repo root (where package.json exists). Current: $((Get-Location).Path)"
  }
}

Require-RepoRoot

# -----------------------------
# 1) navigation.ts
# -----------------------------
$navPath = "src\data\navigation.ts"
if (!(Test-Path -LiteralPath $navPath)) { throw "Missing: $navPath" }

Backup-File $navPath
$nav = [IO.File]::ReadAllText($navPath)

# A) Remove the invalid TOOLS section object (flat NavItem[] cannot contain {title, items})
# This removes any object containing title:"TOOLS" and items:[...]
$rxToolsObj = [regex]::new(
  '(?s)\{\s*title\s*:\s*"TOOLS"\s*,\s*items\s*:\s*\[(?:.*?)\]\s*,?\s*\}\s*,?',
  [System.Text.RegularExpressions.RegexOptions]::Singleline
)
$nav2 = $rxToolsObj.Replace($nav, "")

if ($nav2 -ne $nav) {
  Write-Host "navigation.ts: Removed invalid TOOLS section object."
} else {
  Write-Host "navigation.ts: No invalid TOOLS section object matched (maybe already removed or formatted differently)."
}

# B) Insert orphan routes as flat NavItems into the first exported array (export const X = [ ... ])
$targets = @(
  @{ key="templates"; label="Room Templates"; path="/templates"; tooltip="Browse vertical-market starting points" },
  @{ key="training";  label="Training Hub";   path="/training";  tooltip="Sales enablement and AV knowledge" },
  @{ key="compare";   label="Competitor Compare"; path="/compare"; tooltip="Compare WyreStorm vs competitors" },
  @{ key="discovery"; label="Customer Discovery"; path="/discovery"; tooltip="Capture room requirements" },
  @{ key="videowall"; label="Video Wall Tool"; path="/videowall"; tooltip="Design video wall solutions" },
  @{ key="survey";    label="Survey Import"; path="/survey"; tooltip="Import or capture survey data" },
  @{ key="analytics"; label="Analytics"; path="/analytics"; tooltip="Internal analytics" },
  @{ key="ask";       label="Ask Guru"; path="/ask"; tooltip="Quick AV questions" },
  @{ key="setup";     label="Project Setup"; path="/setup"; tooltip="Create a project brief" },
  @{ key="agent";     label="Agent Input"; path="/agent"; tooltip="Internal (advanced)" }
)

function Has-NavPath([string]$text, [string]$path) {
  return ($text -match [regex]::Escape('path: "' + $path + '"'))
}
function Has-NavKey([string]$text, [string]$key) {
  return ($text -match [regex]::Escape('key: "' + $key + '"'))
}

$rxExportArray = [regex]::new('export\s+const\s+(?<name>[A-Za-z0-9_]+)\s*=\s*\[', 'Singleline')
$m = $rxExportArray.Match($nav2)
if (-not $m.Success) {
  throw "navigation.ts: Could not find 'export const <NAME> = [' to insert NavItems into."
}

$insertPos = $m.Index + $m.Length
$existing = $nav2

$linesToInsert = New-Object System.Collections.Generic.List[string]
$linesToInsert.Add("") | Out-Null
$linesToInsert.Add("  // Auto-wired orphan routes (generated by tools/fix-nav-and-comparison.ps1)") | Out-Null

$added = 0
foreach ($t in $targets) {
  if (Has-NavPath $existing $t.path) { continue }
  if (Has-NavKey  $existing $t.key)  { continue }

  $tooltip = ($t.tooltip -replace '"','\"')
  $linesToInsert.Add(('  { key: "{0}", label: "{1}", path: "{2}", tooltip: "{3}", status: "active" },' -f $t.key, $t.label, $t.path, $tooltip)) | Out-Null
  $added++
}

if ($added -gt 0) {
  $block = ($linesToInsert.ToArray() -join "`r`n") + "`r`n"
  $nav3 = $nav2.Substring(0, $insertPos) + $block + $nav2.Substring($insertPos)
  Write-Host ("navigation.ts: Inserted {0} NavItem(s) into exported array '{1}'." -f $added, $m.Groups["name"].Value)
} else {
  $nav3 = $nav2
  Write-Host "navigation.ts: No new NavItems inserted (targets already present)."
}

# Keep file tidy: collapse 3+ blank lines to 2
$nav3 = [regex]::Replace($nav3, "(\r?\n){3,}", "`r`n`r`n")

# Safety check: nav must not still contain title:"TOOLS"
if ($nav3 -match 'title:\s*"TOOLS"') {
  throw 'navigation.ts: Still contains title: "TOOLS". The block is formatted differently; paste the first 60 lines of src/data/navigation.ts.'
}

WriteUtf8NoBom $navPath $nav3

# -----------------------------
# 2) ComparisonPage.tsx
# -----------------------------
$cmpPath = "src\pages\ComparisonPage.tsx"
if (!(Test-Path -LiteralPath $cmpPath)) { throw "Missing: $cmpPath" }

Backup-File $cmpPath
$cmp = [IO.File]::ReadAllText($cmpPath)

# Remove eyebrow=... from PageHeader usage, tolerant of whitespace/newlines.
# Matches: eyebrow="Competitive" OR eyebrow={...}
$cmp2 = [regex]::Replace(
  $cmp,
  '(?s)\s+eyebrow\s*=\s*(?:"[^"]*"|\{[^}]*\})',
  '',
  [System.Text.RegularExpressions.RegexOptions]::Singleline
)

if ($cmp2 -eq $cmp) {
  Write-Host "ComparisonPage.tsx: No eyebrow attribute matched (may already be removed or formatted unexpectedly)."
} else {
  WriteUtf8NoBom $cmpPath $cmp2
  Write-Host "ComparisonPage.tsx: Removed eyebrow attribute."
}

if ($cmp2 -match 'eyebrow\s*=') {
  throw "ComparisonPage.tsx: eyebrow attribute still present; paste lines around the PageHeader component."
}

Write-Host ""
Write-Host "Done."
Write-Host "Next:"
Write-Host "  npm run typecheck"
