# tools/fix-nav-and-comparison-v2.ps1
# Fixes:
# - src\data\navigation.ts: remove invalid { title:"TOOLS", items:[...] } block; add orphan routes as flat NavItems
# - src\pages\ComparisonPage.tsx: remove PageHeader eyebrow prop
#
# Run:
#   pwsh -NoProfile -ExecutionPolicy Bypass -File tools\fix-nav-and-comparison-v2.ps1
#   npm run typecheck

$ErrorActionPreference = "Stop"

function Backup-File([string]$path) {
  if (Test-Path -LiteralPath $path) {
    $stamp = Get-Date -Format "yyyyMMdd_HHmmss"
    Copy-Item -LiteralPath $path -Destination ($path + ".bak_" + $stamp) -Force
    Write-Host ("Backup: {0}.bak_{1}" -f $path, $stamp)
  }
}

function WriteUtf8NoBom([string]$path, [string]$content) {
  $dir = Split-Path -Parent $path
  if ($dir -and !(Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  [IO.File]::WriteAllText($path, $content, (New-Object System.Text.UTF8Encoding($false)))
  Write-Host ("Wrote: {0}" -f $path)
}

function Require-RepoRoot() {
  if (!(Test-Path -LiteralPath "package.json")) {
    throw "Run from repo root (where package.json exists). Current: $((Get-Location).Path)"
  }
}

Require-RepoRoot

# -----------------------------
# 1) navigation.ts
# -----------------------------
$navPath = "src\data\navigation.ts"
if (!(Test-Path -LiteralPath $navPath)) { throw "Missing: $navPath" }
Backup-File $navPath

$navText = [IO.File]::ReadAllText($navPath)

# A) Remove invalid TOOLS block (line-based, anchored on title:"TOOLS")
$lines = $navText -split "(`r`n|`n)"
$idxTitle = -1
for ($i=0; $i -lt $lines.Count; $i++) {
  if ($lines[$i] -match '^\s*title\s*:\s*"TOOLS"\s*,?\s*$') { $idxTitle = $i; break }
}

if ($idxTitle -ge 0) {
  # Find object start '{' above
  $objStart = $idxTitle
  for ($j=$idxTitle; $j -ge 0; $j--) {
    if ($lines[$j].Trim() -eq "{") { $objStart = $j; break }
  }
  # Find object end '},' below
  $objEnd = $idxTitle
  for ($k=$idxTitle; $k -lt $lines.Count; $k++) {
    if ($lines[$k].Trim() -match '^\},\s*$') { $objEnd = $k; break }
  }
  if ($objEnd -lt $objStart) { throw "navigation.ts: Found TOOLS title but could not find closing '},'." }

  Write-Host ("navigation.ts: Removing invalid TOOLS object lines {0}-{1}" -f ($objStart+1), ($objEnd+1))

  $before = @()
  if ($objStart -gt 0) { $before = $lines[0..($objStart-1)] }
  $after = @()
  if ($objEnd -lt ($lines.Count-1)) { $after = $lines[($objEnd+1)..($lines.Count-1)] }
  $lines = @($before + $after)
  $navText = ($lines -join "`r`n")
} else {
  # B) Regex fallback (handles odd formatting)
  $rxToolsObj = [regex]::new('(?s)\{\s*title\s*:\s*"TOOLS"\s*,\s*items\s*:\s*\[(?:.*?)\]\s*,?\s*\}\s*,?', 'Singleline')
  $navText2 = $rxToolsObj.Replace($navText, "")
  if ($navText2 -ne $navText) {
    Write-Host "navigation.ts: Removed invalid TOOLS object (regex fallback)."
    $navText = $navText2
  } else {
    Write-Host "navigation.ts: No TOOLS block found (may already be removed)."
  }
}

# C) Insert orphan routes as FLAT NavItems into first exported array opening '['
# Supports: export const X: Type = [   OR export const X = [
$targets = @(
  @{ key="templates"; label="Room Templates"; path="/templates"; tooltip="Browse vertical-market starting points" },
  @{ key="training";  label="Training Hub";   path="/training";  tooltip="Sales enablement and AV knowledge" },
  @{ key="compare";   label="Competitor Compare"; path="/compare"; tooltip="Compare WyreStorm vs competitors" },
  @{ key="discovery"; label="Customer Discovery"; path="/discovery"; tooltip="Capture room requirements" },
  @{ key="videowall"; label="Video Wall Tool"; path="/videowall"; tooltip="Design video wall solutions" },
  @{ key="survey";    label="Survey Import"; path="/survey"; tooltip="Import or capture survey data" },
  @{ key="analytics"; label="Analytics"; path="/analytics"; tooltip="Internal analytics" },
  @{ key="ask";       label="Ask Guru"; path="/ask"; tooltip="Quick AV questions" },
  @{ key="setup";     label="Project Setup"; path="/setup"; tooltip="Create a project brief" },
  @{ key="agent";     label="Agent Input"; path="/agent"; tooltip="Internal (advanced)" }
)

function Has-NavPath([string]$text, [string]$path) {
  return ($text -match [regex]::Escape('path: "' + $path + '"'))
}
function Has-NavKey([string]$text, [string]$key) {
  return ($text -match [regex]::Escape('key: "' + $key + '"'))
}

# Find insertion point: first occurrence of "export const <name> ... = [" (allow optional ": Type")
$rxExportArrayOpen = [regex]::new('export\s+const\s+(?<name>[A-Za-z0-9_]+)\s*(?::[^=]+)?=\s*\[', 'Singleline')
$m = $rxExportArrayOpen.Match($navText)
if (-not $m.Success) {
  throw "navigation.ts: Could not find an exported array like 'export const X = [' or 'export const X: Type = ['."
}

$exportName = $m.Groups["name"].Value
$insertPos = $m.Index + $m.Length

$toInsert = New-Object System.Text.StringBuilder
[void]$toInsert.AppendLine("")
[void]$toInsert.AppendLine("  // Auto-wired orphan routes (generated by tools/fix-nav-and-comparison-v2.ps1)")

$added = 0
foreach ($t in $targets) {
  if (Has-NavPath $navText $t.path) { continue }
  if (Has-NavKey  $navText $t.key)  { continue }

  $tooltip = ($t.tooltip -replace '"','\"')
  [void]$toInsert.AppendLine(('  { key: "{0}", label: "{1}", path: "{2}", tooltip: "{3}", status: "active" },' -f $t.key, $t.label, $t.path, $tooltip))
  $added++
}

if ($added -gt 0) {
  $navText = $navText.Substring(0, $insertPos) + $toInsert.ToString() + $navText.Substring($insertPos)
  Write-Host ("navigation.ts: Inserted {0} NavItem(s) into '{1}'." -f $added, $exportName)
} else {
  Write-Host "navigation.ts: No new NavItems inserted (targets already present)."
}

# Tidy: collapse 3+ blank lines
$navText = [regex]::Replace($navText, "(\r?\n){3,}", "`r`n`r`n")

WriteUtf8NoBom $navPath $navText

# Verification: TOOLS title must be gone
if ($navText -match 'title\s*:\s*"TOOLS"') {
  throw 'navigation.ts: Still contains title: "TOOLS". Paste lines 1-40 of src/data/navigation.ts.'
}

# -----------------------------
# 2) ComparisonPage.tsx
# -----------------------------
$cmpPath = "src\pages\ComparisonPage.tsx"
if (!(Test-Path -LiteralPath $cmpPath)) { throw "Missing: $cmpPath" }
Backup-File $cmpPath

$cmp = [IO.File]::ReadAllText($cmpPath)

# Remove eyebrow=... anywhere (string or JSX expression), whitespace/newlines tolerant
$cmp2 = [regex]::Replace($cmp, '(?s)\s+eyebrow\s*=\s*(?:"[^"]*"|\{[^}]*\})', '', 'Singleline')

if ($cmp2 -ne $cmp) {
  WriteUtf8NoBom $cmpPath $cmp2
  Write-Host "ComparisonPage.tsx: Removed eyebrow attribute."
} else {
  Write-Host "ComparisonPage.tsx: No eyebrow attribute found (may already be removed)."
}

# Verification: eyebrow must be gone
$cmpAfter = [IO.File]::ReadAllText($cmpPath)
if ($cmpAfter -match 'eyebrow\s*=') {
  throw "ComparisonPage.tsx: eyebrow attribute still present. Paste lines around the PageHeader usage."
}

Write-Host ""
Write-Host "OK: navigation.ts and ComparisonPage.tsx patched."
Write-Host "Next:"
Write-Host "  npm run typecheck"

