export const WM_ROUTES = {
  dashboard: "/app/dashboard",
  projects: "/app/projects",
  projectLauncher: "/app/projects/new",
  newProject: "/app/tools/room-wizard/new",
  tools: "/app/tools",
  navigator: "/app/tools/navigator",
  discovery: "/app/tools/discovery",
  importIntake: "/app/tools/import-intake",
  templates: "/app/tools/templates",
  roomDesigner: "/app/tools/room-wizard",
  proposals: "/app/tools/proposal",
  completion: "/app/workflow/completion",
  guru: "/app/tools/guru",
  catalogue: "/app/tools/catalog",
  videowall: "/app/tools/video-wall",
  competitorCompare: "/app/tools/compare",
  training: "/app/tools/training",
} as const;
