import type { CustomerRequestRecord } from "./types";

export const seedCustomerRequests: CustomerRequestRecord[] = [
  {
    id: "ENQ-001",
    title: "Vague huddle-room refresh request",
    vertical: "Corporate",
    complexity: "Simple",
    channel: "email",
    customerRequest:
      "Customer wants a simple AV upgrade for a small meeting room, probably 4 to 6 people. One screen is fine. They want to plug in a laptop and ideally share wirelessly as well. Must be dead easy to use because visitors use the room.",
    expectedSignals: ["small meeting room", "single display", "laptop input", "wireless sharing", "easy to use"],
    likelySolutionCategories: ["Wireless Presentation", "Control System / Touch Panel"],
    expectedRoomType: "Huddle Room",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-002",
    title: "Teams room with table connectivity and room peripherals",
    vertical: "Corporate",
    complexity: "Medium",
    channel: "phone note",
    customerRequest:
      "Need a proper Teams room for around 12 people. Front of room camera, table microphones, soundbar or speakers, and users need HDMI and USB-C at the table. Rack may be in comms room about 25m away.",
    expectedSignals: ["Teams room", "12 people", "camera", "microphones", "USB-C", "25m rack distance"],
    likelySolutionCategories: ["UC Room Integration", "HDBaseT Extension", "USB Extension / Routing"],
    expectedRoomType: "Meeting Room",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-003",
    title: "Boardroom dual-display consultant note",
    vertical: "Corporate",
    complexity: "Complex",
    channel: "consultant brief",
    customerRequest:
      "Executive boardroom, 16 seats, dual 98 inch displays. Requirement to show same image on both displays or split content between local presentation and VC far-end. Touch control required. BYOM support desirable.",
    expectedSignals: ["boardroom", "16 seats", "dual 98 inch displays", "independent content", "touch control", "BYOM"],
    likelySolutionCategories: ["Matrix Switching", "UC Room Integration", "Control System / Touch Panel"],
    expectedRoomType: "Boardroom",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-004",
    title: "Divisible training suite with local plates and combined mode",
    vertical: "Corporate",
    complexity: "Complex",
    channel: "site survey",
    customerRequest:
      "Training suite can open into one large space or split into two rooms. Each side needs local laptop input and wireless presentation. When opened up, trainer wants one source on both displays or separate content left/right. Keep operation simple.",
    expectedSignals: ["divisible room", "local laptop input", "wireless presentation", "combined mode", "simple operation"],
    likelySolutionCategories: ["Matrix Switching", "Control System / Touch Panel", "AV over IP"],
    expectedRoomType: "Training Room",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-005",
    title: "Hybrid classroom with lecture capture",
    vertical: "Education",
    complexity: "Complex",
    channel: "email",
    customerRequest:
      "Classroom for 40 students. Lecturer laptop plus document camera. Need projector and confidence display, wireless presentation, camera, ceiling mics, recording and occasional live stream for remote learners.",
    expectedSignals: ["classroom", "40 students", "document camera", "projector", "confidence display", "recording", "streaming"],
    likelySolutionCategories: ["Lecture Capture Support", "UC Room Integration", "Audio DSP / Reinforcement"],
    expectedRoomType: "Classroom",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-006",
    title: "University tender for standard teaching spaces",
    vertical: "Consultant / Tender",
    complexity: "Tender",
    channel: "tender",
    customerRequest:
      "Please price AV systems for 18 standard teaching rooms, 6 seminar rooms, one lecture theatre, associated signage, and central monitoring. Preference for standardised user experience, remote support, and future expansion across the campus estate.",
    expectedSignals: ["tender", "18 teaching rooms", "seminar rooms", "lecture theatre", "signage", "central monitoring", "standardised user experience"],
    likelySolutionCategories: ["AV over IP", "Central Monitoring / Management", "Lecture Capture Support", "Digital Signage Distribution"],
    expectedRoomType: "Teaching Spaces",
    expectedDeploymentScale: "Campus / Estate",
  },
  {
    id: "ENQ-007",
    title: "Hotel ballroom with stage feeds and overflow displays",
    vertical: "Hospitality",
    complexity: "Complex",
    channel: "phone note",
    customerRequest:
      "Hotel ballroom for events. Need main screens, side repeater displays, lectern HDMI and USB-C, wireless presentation, stage confidence monitor and simple staff control. Some distances will be long because equipment is in a side room.",
    expectedSignals: ["ballroom", "repeater displays", "lectern HDMI and USB-C", "wireless presentation", "staff control", "long distances"],
    likelySolutionCategories: ["HDBaseT Extension", "Matrix Switching", "Control System / Touch Panel"],
    expectedRoomType: "Ballroom",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-008",
    title: "Retail rollout with local override signage",
    vertical: "Retail",
    complexity: "Complex",
    channel: "consultant brief",
    customerRequest:
      "Rollout of promotional displays to 55 stores. Head office content control required, but store managers need a local override option for campaigns. Some flagship locations may add LED feature walls later.",
    expectedSignals: ["55 stores", "head office content control", "local override", "flagship LED walls"],
    likelySolutionCategories: ["Digital Signage Distribution", "Central Monitoring / Management", "Video Wall Processing"],
    expectedRoomType: "Retail Signage",
    expectedDeploymentScale: "Portfolio rollout",
  },
  {
    id: "ENQ-009",
    title: "Government committee chamber with hybrid attendance",
    vertical: "Government",
    complexity: "Complex",
    channel: "email",
    customerRequest:
      "Committee chamber needs delegate microphones, public display screens, remote participant support via Teams or Zoom, recording of proceedings, and a simple control surface because the room is run by non-technical staff.",
    expectedSignals: ["committee chamber", "delegate microphones", "public display screens", "hybrid attendance", "recording", "simple control"],
    likelySolutionCategories: ["UC Room Integration", "Audio DSP / Reinforcement", "Control System / Touch Panel", "Streaming / Recording"],
    expectedRoomType: "Council Chamber",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-010",
    title: "Control room with operator desks and overview wall",
    vertical: "Control Room",
    complexity: "Complex",
    channel: "site survey",
    customerRequest:
      "Operations room with 8 operator positions and a large overview wall. Need multiple PC and IP video sources routed between desks and wall. 24/7 environment so resilience is important. Consultant mentions managed network is available.",
    expectedSignals: ["8 operator positions", "overview wall", "multiple PC and IP sources", "24/7", "managed network"],
    likelySolutionCategories: ["AV over IP", "Video Wall Processing", "Central Monitoring / Management"],
    expectedRoomType: "Control Room",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-011",
    title: "Reception signage plus live events mode",
    vertical: "Corporate",
    complexity: "Medium",
    channel: "email",
    customerRequest:
      "Reception needs two signage displays for normal messaging but marketing also wants one of them to switch to live event feeds occasionally. Content scheduling matters but front desk staff also need a quick manual override.",
    expectedSignals: ["reception", "two signage displays", "live event feeds", "manual override", "content scheduling"],
    likelySolutionCategories: ["Digital Signage Distribution", "Matrix Switching", "Control System / Touch Panel"],
    expectedRoomType: "Reception / Lobby",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-012",
    title: "BYOM collaboration space with room USB devices",
    vertical: "Corporate",
    complexity: "Complex",
    channel: "email",
    customerRequest:
      "Open collaboration room for 8 to 10 people. Users bring their own laptop and need to use the room camera, mics, soundbar, and dual screens. We do not want a dedicated in-room PC. Cable route from table to display wall is around 12m.",
    expectedSignals: ["BYOM", "camera", "mics", "soundbar", "dual screens", "12m cable route"],
    likelySolutionCategories: ["USB Extension / Routing", "UC Room Integration", "Matrix Switching"],
    expectedRoomType: "Collaboration Space",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-013",
    title: "Hospital training suite with remote observation",
    vertical: "Healthcare",
    complexity: "Complex",
    channel: "consultant brief",
    customerRequest:
      "Simulation and training suite requires procedure cameras, local displays, observation room feeds, recording for review, and remote specialist consultation support. The brief is light on exact room dimensions.",
    expectedSignals: ["simulation suite", "procedure cameras", "observation room feeds", "recording", "remote consultation"],
    likelySolutionCategories: ["Streaming / Recording", "AV over IP", "UC Room Integration"],
    expectedRoomType: "Simulation Suite",
    expectedDeploymentScale: "Single space",
  },
  {
    id: "ENQ-014",
    title: "Consultant mixed-use civic building tender",
    vertical: "Consultant / Tender",
    complexity: "Tender",
    channel: "tender",
    customerRequest:
      "AV tender for a mixed-use civic building including meeting rooms, a divisible training suite, public signage, emergency briefing room, and control/monitoring capability from a central support office. Please allow for phased rollout and future expansion.",
    expectedSignals: ["mixed-use civic building", "meeting rooms", "divisible training suite", "public signage", "briefing room", "central support", "future expansion"],
    likelySolutionCategories: ["AV over IP", "Central Monitoring / Management", "Digital Signage Distribution", "UC Room Integration"],
    expectedRoomType: "Mixed-Use Civic Building",
    expectedDeploymentScale: "Programme / Tender",
  },
];
