export const discoveryResponseSchema = {
  type: "object",
  properties: {
    briefVersion: { type: "string" },
    summary: { type: "string" },
    solutionIntent: {
      type: "string",
      enum: ["extender", "splitter", "matrix", "presentation-switching", "avoip", "video-wall", "unknown"],
    },
    roomProfile: {
      type: "object",
      properties: {
        roomType: {
          type: "string",
          enum: ["meeting-room", "boardroom", "classroom", "retail", "control-room", "hospitality", "residential", "unknown"],
        },
        displayCount: { type: "integer" },
        sourceCount: { type: "integer" },
        zones: { type: "integer" },
        maxDistanceM: { type: "integer" },
        videoWall: { type: "boolean" },
        videoWallLayout: { type: "string", enum: ["none", "2x2", "3x3", "4x4", "4x2", "custom"] },
        usbRequired: { type: "boolean" },
        audioBreakoutRequired: { type: "boolean" },
        controlRequired: { type: "boolean" },
      },
      required: [
        "roomType",
        "displayCount",
        "sourceCount",
        "zones",
        "maxDistanceM",
        "videoWall",
        "videoWallLayout",
        "usbRequired",
        "audioBreakoutRequired",
        "controlRequired",
      ],
    },
    commercialProfile: {
      type: "object",
      properties: {
        budgetLevel: { type: "string", enum: ["entry", "mid", "premium", "unknown"] },
        priority: { type: "string", enum: ["cost", "simplicity", "flexibility", "performance", "unknown"] },
      },
      required: ["budgetLevel", "priority"],
    },
    constraints: {
      type: "array",
      items: {
        type: "object",
        properties: {
          type: { type: "string", enum: ["distance", "bandwidth", "mounting", "rack-space", "power", "network", "budget", "other"] },
          detail: { type: "string" },
        },
        required: ["type", "detail"],
      },
    },
    missingInformation: { type: "array", items: { type: "string" } },
    assumptions: { type: "array", items: { type: "string" } },
    confidence: { type: "number" },
    recommendedNextAction: { type: "string", enum: ["architect"] },
  },
  required: [
    "briefVersion",
    "summary",
    "solutionIntent",
    "roomProfile",
    "commercialProfile",
    "constraints",
    "missingInformation",
    "assumptions",
    "confidence",
    "recommendedNextAction",
  ],
};
