
export type NavItem = {
  path: string;
  label: string;
  end?: boolean;
};

export const NAV_LINKS: NavItem[] = [
  // Tools hub (generated by tools/implement-tools-menu-welcome-and-toolhub.ps1)
  { label: "Tools", path: "/app/toolhub" },

  // Auto-wired orphan routes (generated by tools/fix-nav-and-comparison-v3.ps1)
  { label: "Room Templates", path: "/app/tools/templates"},
  { label: "Training Hub", path: "/app/tools/training"},
  { label: "Competitor Compare", path: "/app/tools/compare"},
  { label: "Customer Discovery", path: "/discovery"},
  { label: "Video Wall Tool", path: "/app/tools/videowall"},
  { label: "Survey Import", path: "/app/survey-import"},
  { label: "Analytics", path: "/analytics"},
  { label: "Ask Guru", path: "/ask"},
  { label: "Project Setup", path: "/app/setup"},
  { label: "Agent Input", path: "/app/tools/agent"},

  { path: '/', label: 'Dashboard', end: true },
  { path: '/app/setup', label: 'New Project', end: false },
  { path: '/app/tools/agent', label: 'Analyze Intel', end: false },
  { path: '/app/tools/templates', label: 'Templates', end: false },
  { path: '/app/tools/videowall', label: 'Video Wall', end: false },
  { path: '/analytics', label: 'Analytics', end: false },
  { path: '/app/tools/training', label: 'Training', end: false },
];



