$ErrorActionPreference = "Stop"
$ROOT = "C:\Users\steve\wingman"
Set-Location $ROOT
if (!(Test-Path "package.json")) { throw "Run from repo root: C:\Users\steve\wingman" }

function Ensure-Dir([string]$p){ if(!(Test-Path $p)){ New-Item -ItemType Directory -Path $p | Out-Null } }
function Backup-File([string]$p){
  if(Test-Path $p){
    $s = Get-Date -Format "yyyyMMdd_HHmmss"
    Copy-Item $p "$p.bak_$s" -Force
  }
}
function Write-Utf8NoBom([string]$path, [string[]]$lines){
  $dir = Split-Path $path -Parent
  Ensure-Dir $dir
  $enc = New-Object System.Text.UTF8Encoding($false)
  $content = ($lines -join "`r`n") + "`r`n"
  [System.IO.File]::WriteAllText($path, $content, $enc)
}

Ensure-Dir "src\competitor"

# -------------------------------------------------------------------
# 1) types.ts
# -------------------------------------------------------------------
$types = "src\competitor\types.ts"
Backup-File $types
Write-Utf8NoBom $types @(
'export type CompetitorCategory = "AVoIP" | "Matrix" | "Switcher" | "Extender" | "VideoWall" | "Control" | "Accessory";',
'export type CompetitorRole = "TX" | "RX" | "TRX" | "Controller" | "Processor" | "Matrix" | "Switcher" | "Accessory";',
'',
'export type CompetitorVideoCaps = {',
'  maxResolution?: "1080p60" | "4K30" | "4K60" | "4K120";',
'  hdmi?: "1.4" | "2.0" | "2.1";',
'  hdr?: boolean;',
'};',
'',
'export type CompetitorItem = {',
'  brand: string;',
'  model: string;',
'  name: string;',
'  category: CompetitorCategory;',
'  role: CompetitorRole;',
'  tags?: string[];',
'  video?: CompetitorVideoCaps;',
'  notes?: string[];',
'};',
'',
'export type MatchResult = {',
'  competitor: CompetitorItem;',
'  sku: string;',
'  name: string;',
'  confidence: number; // 0..100',
'  reasons: string[];',
'};'
)

# -------------------------------------------------------------------
# 2) competitors.json (starter dataset - expand later)
# -------------------------------------------------------------------
$dataset = "src\competitor\competitors.json"
Backup-File $dataset
Write-Utf8NoBom $dataset @(
'[',
'  {',
'    "brand": "Extron",',
'    "model": "NAV E 501",',
'    "name": "AV over IP Encoder",',
'    "category": "AVoIP",',
'    "role": "TX",',
'    "tags": ["AVoIP", "4K60", "managed-network"],',
'    "video": { "maxResolution": "4K60", "hdmi": "2.0", "hdr": true },',
'    "notes": ["Typical enterprise AVoIP encoder use-case."]',
'  },',
'  {',
'    "brand": "Extron",',
'    "model": "NAV SD 501",',
'    "name": "AV over IP Decoder",',
'    "category": "AVoIP",',
'    "role": "RX",',
'    "tags": ["AVoIP", "4K60", "managed-network"],',
'    "video": { "maxResolution": "4K60", "hdmi": "2.0", "hdr": true }',
'  },',
'  {',
'    "brand": "Crestron",',
'    "model": "DM-NVX-E30",',
'    "name": "AV over IP Encoder",',
'    "category": "AVoIP",',
'    "role": "TX",',
'    "tags": ["AVoIP", "4K60", "low-latency"],',
'    "video": { "maxResolution": "4K60", "hdmi": "2.0", "hdr": true }',
'  },',
'  {',
'    "brand": "Crestron",',
'    "model": "DM-NVX-D30",',
'    "name": "AV over IP Decoder",',
'    "category": "AVoIP",',
'    "role": "RX",',
'    "tags": ["AVoIP", "4K60", "low-latency"],',
'    "video": { "maxResolution": "4K60", "hdmi": "2.0", "hdr": true }',
'  },',
'  {',
'    "brand": "Kramer",',
'    "model": "KDS-EN7",',
'    "name": "AV over IP Encoder",',
'    "category": "AVoIP",',
'    "role": "TX",',
'    "tags": ["AVoIP", "4K60"],',
'    "video": { "maxResolution": "4K60", "hdmi": "2.0", "hdr": true }',
'  },',
'  {',
'    "brand": "Kramer",',
'    "model": "KDS-DEC7",',
'    "name": "AV over IP Decoder",',
'    "category": "AVoIP",',
'    "role": "RX",',
'    "tags": ["AVoIP", "4K60"],',
'    "video": { "maxResolution": "4K60", "hdmi": "2.0", "hdr": true }',
'  },',
'  {',
'    "brand": "Atlona",',
'    "model": "OmniStream AT-OMNI-121",',
'    "name": "AV over IP Decoder",',
'    "category": "AVoIP",',
'    "role": "RX",',
'    "tags": ["AVoIP", "4K60"],',
'    "video": { "maxResolution": "4K60", "hdmi": "2.0", "hdr": true }',
'  },',
'  {',
'    "brand": "Extron",',
'    "model": "DTP CrossPoint 84",',
'    "name": "Matrix Switcher",',
'    "category": "Matrix",',
'    "role": "Matrix",',
'    "tags": ["matrix", "switching"],',
'    "notes": ["Typical fixed matrix/switching requirement."]',
'  },',
'  {',
'    "brand": "Crestron",',
'    "model": "DM-MD8X8",',
'    "name": "Matrix Switcher",',
'    "category": "Matrix",',
'    "role": "Matrix",',
'    "tags": ["matrix", "switching"]',
'  },',
'  {',
'    "brand": "Extron",',
'    "model": "IN1608",',
'    "name": "Presentation Switcher",',
'    "category": "Switcher",',
'    "role": "Switcher",',
'    "tags": ["switcher", "presentation"]',
'  }',
']'
)

# -------------------------------------------------------------------
# 3) CompetitorMatchService.ts (catalog-backed scoring)
# -------------------------------------------------------------------
$svc = "src\competitor\CompetitorMatchService.ts"
Backup-File $svc
Write-Utf8NoBom $svc @(
'import competitorsRaw from "./competitors.json";',
'import type { CompetitorItem, MatchResult } from "./types";',
'import { listAll, isSelectable } from "@/catalog/CatalogService";',
'import type { Product } from "@/catalog/types";',
'',
'const COMPETITORS: CompetitorItem[] = competitorsRaw as any;',
'',
'function norm(s: string){ return (s || "").toLowerCase().trim(); }',
'',
'function scoreResolution(a?: string, b?: string){',
'  const order: Record<string, number> = { "1080p60": 1, "4K30": 2, "4K60": 3, "4K120": 4 };',
'  if(!a || !b) return { score: 0, reason: "No resolution data" };',
'  const sa = order[a] || 0;',
'  const sb = order[b] || 0;',
'  if(sa === 0 || sb === 0) return { score: 0, reason: "Unknown resolution enum" };',
'  if(sb >= sa) return { score: 10, reason: `Meets/exceeds ${a}` };',
'  return { score: -15, reason: `Below ${a}` };',
'}',
'',
'function overlapTags(a?: string[], b?: string[]){',
'  const A = new Set((a || []).map(norm));',
'  const B = new Set((b || []).map(norm));',
'  let hit = 0;',
'  for(const t of A){ if(B.has(t)) hit++; }',
'  return hit;',
'}',
'',
'function baseCategoryScore(cCat: string, p: Product){',
'  if(p.category === cCat) return { score: 35, reason: "Category match" };',
'  // light mapping',
'  if(cCat === "Switcher" && p.category === "Matrix") return { score: 18, reason: "Switcher→Matrix adjacent" };',
'  if(cCat === "Matrix" && p.category === "Switcher") return { score: 18, reason: "Matrix→Switcher adjacent" };',
'  return { score: -10, reason: "Category mismatch" };',
'}',
'',
'function roleScore(cRole: string, p: Product){',
'  if(p.role === cRole) return { score: 20, reason: "Role match" };',
'  // TRX is flexible',
'  if(cRole === "TX" && p.role === "TRX") return { score: 14, reason: "TRX can act as TX" };',
'  if(cRole === "RX" && p.role === "TRX") return { score: 14, reason: "TRX can act as RX" };',
'  return { score: -8, reason: "Role mismatch" };',
'}',
'',
'function lifecyclePenalty(p: Product){',
'  if(p.lifecycle === "eol") return { score: -100, reason: "EoL blocked" };',
'  if(p.lifecycle === "legacy") return { score: -8, reason: "Legacy penalty" };',
'  return { score: 0, reason: "Current lifecycle" };',
'}',
'',
'export function listCompetitors(): CompetitorItem[] {',
'  return [...COMPETITORS].sort((a,b) => (a.brand+a.model).localeCompare(b.brand+b.model));',
'}',
'',
'export function searchCompetitors(q: string): CompetitorItem[] {',
'  const s = norm(q);',
'  if(!s) return listCompetitors();',
'  return COMPETITORS.filter(c => {',
'    const hay = norm([c.brand, c.model, c.name, c.category, c.role, ...(c.tags||[]), ...(c.notes||[])].join(" "));',
'    return hay.includes(s);',
'  });',
'}',
'',
'export function matchToCatalog(competitor: CompetitorItem, topN = 5): MatchResult[] {',
'  const catalog = listAll();',
'  const scored = catalog.map(p => {',
'    let score = 0;',
'    const reasons: string[] = [];',
'',
'    const cat = baseCategoryScore(competitor.category, p);',
'    score += cat.score; reasons.push(cat.reason);',
'',
'    const rol = roleScore(competitor.role, p);',
'    score += rol.score; reasons.push(rol.reason);',
'',
'    const res = scoreResolution(competitor.video?.maxResolution, p.video?.maxResolution);',
'    score += res.score; if(res.score !== 0) reasons.push(res.reason);',
'',
'    const tagHits = overlapTags(competitor.tags, p.tags);',
'    if(tagHits > 0){ score += Math.min(12, tagHits * 4); reasons.push(`Tag overlap x${tagHits}`); }',
'',
'    const life = lifecyclePenalty(p);',
'    score += life.score; reasons.push(life.reason);',
'',
'    // Clamp + convert to confidence',
'    const clamped = Math.max(-100, Math.min(100, score));',
'    const confidence = Math.max(0, Math.min(100, Math.round((clamped + 10) * 0.9)));',
'',
'    return { p, confidence, reasons };',
'  })',
'  .filter(x => x.confidence > 0)',
'  .sort((a,b) => b.confidence - a.confidence)',
'  .slice(0, topN);',
'',
'  return scored.map(x => ({',
'    competitor,',
'    sku: x.p.sku,',
'    name: x.p.name,',
'    confidence: x.confidence,',
'    reasons: x.reasons.filter(Boolean),',
'  }));',
'}',
'',
'export function canAddSku(sku: string): boolean {',
'  const p = listAll().find(x => x.sku === sku);',
'  if(!p) return false;',
'  return isSelectable(p);',
'}'
)

# -------------------------------------------------------------------
# 4) Rebuild CompetitorComparePage.tsx (tool UI)
# -------------------------------------------------------------------
$page = "src\pages\tools\CompetitorComparePage.tsx"
Backup-File $page
Write-Utf8NoBom $page @(
'import React, { useMemo, useState } from "react";',
'import { searchCompetitors, matchToCatalog, canAddSku } from "@/competitor/CompetitorMatchService";',
'import type { CompetitorItem } from "@/competitor/types";',
'import { Chip } from "@/components/catalog/Chips";',
'',
'// Optional basket integration if present',
'let addToBasket: ((p: any)=>void) | null = null;',
'try {',
'  // eslint-disable-next-line @typescript-eslint/no-var-requires',
'  addToBasket = require("@/components/catalog/DesignBasket").addToBasket;',
'} catch {',
'  addToBasket = null;',
'}',
'',
'export default function CompetitorComparePage(){',
'  const [q, setQ] = useState("");',
'  const [selected, setSelected] = useState<CompetitorItem | null>(null);',
'',
'  const list = useMemo(() => searchCompetitors(q).slice(0, 30), [q]);',
'  const matches = useMemo(() => (selected ? matchToCatalog(selected, 6) : []), [selected]);',
'',
'  return (',
'    <div>',
'      <div className="wm-kicker">Tool</div>',
'      <div className="wm-h1" style={{ marginTop: 6 }}>Competitor Compare</div>',
'      <div className="wm-p" style={{ marginTop: 6 }}>',
'        Search a competitor model and get ranked WyreStorm alternatives with confidence + reasons.',
'      </div>',
'',
'      <div className="wm-divider" />',
'',
'      <div style={{ display: "grid", gridTemplateColumns: "420px 1fr", gap: 12, alignItems: "start" }}>',
'        <div className="wm-card wm-card-pad">',
'          <div className="wm-section-title">Competitor model</div>',
'          <div className="wm-field">',
'            <label>Search</label>',
'            <input className="wm-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="e.g. NVX, NAV, KDS, matrix..." />',
'          </div>',
'',
'          <div style={{ marginTop: 10, display: "grid", gap: 8 }}>',
'            {list.map((c) => (',
'              <button',
'                key={c.brand + c.model}',
'                className="wm-btn"',
'                style={{ justifyContent: "space-between" }}',
'                onClick={() => setSelected(c)}',
'              >',
'                <span style={{ textAlign: "left" }}>',
'                  <div style={{ fontWeight: 700 }}>{c.brand} — {c.model}</div>',
'                  <div style={{ opacity: 0.75, fontSize: 12 }}>{c.category} • {c.role} • {c.name}</div>',
'                </span>',
'                <span style={{ opacity: 0.7 }}>Select</span>',
'              </button>',
'            ))}',
'          </div>',
'        </div>',
'',
'        <div>',
'          {!selected ? (',
'            <div className="wm-card wm-card-pad">',
'              <div className="wm-p">Select a competitor model to see matches.</div>',
'            </div>',
'          ) : (',
'            <div>',
'              <div className="wm-card wm-card-pad wm-card-primary">',
'                <div className="wm-section-title">Selected competitor</div>',
'                <div style={{ display: "flex", justifyContent: "space-between", gap: 10, alignItems: "baseline" }}>',
'                  <div>',
'                    <div style={{ fontWeight: 800, fontSize: 16 }}>{selected.brand} — {selected.model}</div>',
'                    <div className="wm-p" style={{ marginTop: 4 }}>{selected.name}</div>',
'                  </div>',
'                  <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>',
'                    <Chip label={selected.category} />',
'                    <Chip label={selected.role} />',
'                    {selected.video?.maxResolution && <Chip label={selected.video.maxResolution} />}',
'                  </div>',
'                </div>',
'              </div>',
'',
'              <div style={{ marginTop: 12 }} className="wm-grid wm-grid-3">',
'                {matches.map(m => {',
'                  const ok = canAddSku(m.sku);',
'                  return (',
'                    <div key={m.sku} className="wm-card wm-card-pad">',
'                      <div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}>',
'                        <div>',
'                          <div className="wm-kicker">WyreStorm match</div>',
'                          <div className="wm-h2" style={{ marginTop: 6 }}>{m.sku}</div>',
'                          <div className="wm-p" style={{ marginTop: 4, opacity: 0.9 }}>{m.name}</div>',
'                        </div>',
'                        <div style={{ display: "flex", alignItems: "flex-start" }}>',
'                          <Chip label={`${m.confidence}%`} tone={m.confidence >= 75 ? "accent" : "neutral"} />',
'                        </div>',
'                      </div>',
'',
'                      <div style={{ marginTop: 10, display: "grid", gap: 6 }}>',
'                        <div className="wm-kicker">Reasons</div>',
'                        <ul className="wm-p" style={{ paddingLeft: 18, margin: 0 }}>',
'                          {m.reasons.slice(0,4).map((r,i) => <li key={i} style={{ marginTop: 4 }}>{r}</li>)}',
'                        </ul>',
'                      </div>',
'',
'                      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 12 }}>',
'                        <div className="wm-p" style={{ fontSize: 12, opacity: 0.7 }}>Confidence reflects category/role/spec alignment.</div>',
'                        <button',
'                          className={"wm-btn " + (ok ? "wm-btn-primary" : "")}',
'                          onClick={() => {',
'                            if(!ok) return;',
'                            if(addToBasket){ addToBasket({ sku: m.sku, name: m.name }); alert(`Added ${m.sku} to design basket`); }',
'                            else { alert(`Basket not available. (SKU: ${m.sku})`); }',
'                          }}',
'                          disabled={!ok}',
'                        >',
'                          {ok ? "Add to design" : "Blocked"}',
'                        </button>',
'                      </div>',
'                    </div>',
'                  );',
'                })}',
'              </div>',
'            </div>',
'          )}',
'        </div>',
'      </div>',
'    </div>',
'  );',
'}'
)

# -------------------------------------------------------------------
# 5) Ensure AppRoutes has the competitor tool import without ".tsx"
# -------------------------------------------------------------------
$appRoutes = "src\AppRoutes.tsx"
if(Test-Path $appRoutes){
  Backup-File $appRoutes
  $txt = Get-Content $appRoutes -Raw

  # If it imports with .tsx, remove it (Vite is happier without extension)
  $txt2 = $txt -replace 'import\("(@\/pages\/tools\/CompetitorComparePage)\.tsx"\)', 'import("$1")'
  $txt2 = $txt2 -replace 'import\("(@\/pages\/tools\/CompetitorComparePage)\.tsx"\);', 'import("$1");'
  if($txt2 -ne $txt){
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($appRoutes, $txt2, $enc)
  }
}

Write-Host ""
Write-Host "Installed: catalog-backed Competitor Compare." -ForegroundColor Green
Write-Host "Open: http://localhost:3000/tools/competitor-compare" -ForegroundColor Cyan
