import { normaliseSkuKey, resolveWyrestormSkuAlias } from "./skuAliasResolver";

export interface KnownWyrestormCompareProfile {
  sku: string;
  aliases: readonly string[];
  name: string;
  family: string;
  productClass: string;
  systemRole: string;
  matrixSize: string;
  routedInputCount: number;
  routedOutputCount: number;
  inputTypes: readonly string[];
  outputTypes: readonly string[];
  routedOutputTypes: readonly string[];
  transport: readonly string[];
  technologyFamily: string;
  maxResolution: string;
  resolution: string;
  chroma: string;
  hdmiVersion: string;
  hdcpVersion: string;
  distanceClass: string;
  mirroredOutputCount: number;
  mirroredOutputTypes: readonly string[];
  loopOutputCount: number;
  loopOutputTypes: readonly string[];
  receiverPackage: string;
  control: readonly string[];
  audio: readonly string[];
  power: readonly string[];
  comparisonNotes: readonly string[];
  dataSource: string;
}

const PROFILES: readonly KnownWyrestormCompareProfile[] = [
  {
    sku: "MXV-0808-H2A-V3",
    aliases: ["MXV-0808-H2A", "MXV0808H2A", "MXV-0808-H2A-V3"],
    name: "MXV-0808-H2A-V3 8x8 HDBaseT Matrix",
    family: "MXV Matrix",
    productClass: "HDBaseT matrix",
    systemRole: "8x8 fixed I/O matrix for routing HDMI sources to remote displays over HDBaseT.",
    matrixSize: "8x8",
    routedInputCount: 8,
    routedOutputCount: 8,
    inputTypes: ["HDMI"],
    outputTypes: ["HDBaseT"],
    routedOutputTypes: ["HDBaseT"],
    transport: ["HDMI", "HDBaseT"],
    technologyFamily: "HDBaseT Matrix",
    maxResolution: "Verify datasheet",
    resolution: "Verify datasheet",
    chroma: "Verify datasheet",
    hdmiVersion: "Verify datasheet",
    hdcpVersion: "Verify datasheet",
    distanceClass: "Standard HDBaseT matrix distance class - verify datasheet",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "Matrix product. Confirm receiver requirement separately.",
    control: ["IR - verify", "RS-232 - verify", "LAN/IP - verify"],
    audio: ["Audio support - verify datasheet"],
    power: ["PoC/PoH/PSU - verify datasheet"],
    comparisonNotes: ["Primary 8x8 HDBaseT matrix candidate for C88CS-style opportunities."],
    dataSource: "known-wyrestorm-compare-profile",
  },
  {
    sku: "MXV-0808-H2A-70-V3",
    aliases: ["MXV-0808-70-H2A", "MXV080870H2A", "MXV-0808-H2A-70", "MXV-0808-H2A-70-V3"],
    name: "MXV-0808-H2A-70-V3 8x8 Class A HDBaseT Matrix",
    family: "MXV Matrix",
    productClass: "HDBaseT matrix",
    systemRole: "8x8 fixed I/O matrix for longer-distance HDBaseT routing.",
    matrixSize: "8x8",
    routedInputCount: 8,
    routedOutputCount: 8,
    inputTypes: ["HDMI"],
    outputTypes: ["HDBaseT"],
    routedOutputTypes: ["HDBaseT"],
    transport: ["HDMI", "HDBaseT"],
    technologyFamily: "HDBaseT Matrix",
    maxResolution: "Verify datasheet",
    resolution: "Verify datasheet",
    chroma: "Verify datasheet",
    hdmiVersion: "Verify datasheet",
    hdcpVersion: "Verify datasheet",
    distanceClass: "Longer-distance / Class A HDBaseT direction - verify exact datasheet distance",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "Matrix product. Confirm receiver requirement separately.",
    control: ["IR - verify", "RS-232 - verify", "LAN/IP - verify"],
    audio: ["Audio support - verify datasheet"],
    power: ["PoC/PoH/PSU - verify datasheet"],
    comparisonNotes: ["Longer-distance 8x8 HDBaseT matrix candidate."],
    dataSource: "known-wyrestorm-compare-profile",
  },
  {
    sku: "MXV-0808-H2A-KIT",
    aliases: ["MXV-0808-H2A-KIT", "MXV0808H2AKIT"],
    name: "MXV-0808-H2A-KIT 8x8 HDBaseT Matrix Kit",
    family: "MXV Matrix Kit",
    productClass: "HDBaseT matrix kit",
    systemRole: "8x8 HDBaseT matrix package where receivers are included.",
    matrixSize: "8x8",
    routedInputCount: 8,
    routedOutputCount: 8,
    inputTypes: ["HDMI"],
    outputTypes: ["HDBaseT"],
    routedOutputTypes: ["HDBaseT"],
    transport: ["HDMI", "HDBaseT"],
    technologyFamily: "HDBaseT Matrix Kit",
    maxResolution: "Verify datasheet",
    resolution: "Verify datasheet",
    chroma: "Verify datasheet",
    hdmiVersion: "Verify datasheet",
    hdcpVersion: "Verify datasheet",
    distanceClass: "Verify kit distance class and receiver type",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "KIT SKU: receivers included. Do not classify as TX-only or RX-only.",
    control: ["IR - verify", "RS-232 - verify", "LAN/IP - verify"],
    audio: ["Audio support - verify datasheet"],
    power: ["PoC/PoH/PSU - verify datasheet"],
    comparisonNotes: ["Package/kit candidate where included receivers matter."],
    dataSource: "known-wyrestorm-compare-profile",
  },
  {
    sku: "MX-0808-KIT-V2",
    aliases: ["MX-0808-KIT", "MX0808KIT", "MX-0808-KIT-V2"],
    name: "MX-0808-KIT-V2 8x8 HDBaseT Matrix Kit",
    family: "MX Matrix Kit",
    productClass: "HDBaseT matrix kit",
    systemRole: "8x8 HDBaseT matrix package with mirrored HDMI outputs and included receiver package.",
    matrixSize: "8x8",
    routedInputCount: 8,
    routedOutputCount: 8,
    inputTypes: ["HDMI"],
    outputTypes: ["HDBaseT"],
    routedOutputTypes: ["HDBaseT"],
    transport: ["HDMI", "HDBaseT"],
    technologyFamily: "HDBaseT Matrix Kit",
    maxResolution: "4K60 4:2:0 - verify datasheet",
    resolution: "4K60 4:2:0 - verify datasheet",
    chroma: "4:2:0 - verify datasheet",
    hdmiVersion: "Verify datasheet",
    hdcpVersion: "Verify datasheet",
    distanceClass: "Verify kit distance class from datasheet",
    mirroredOutputCount: 4,
    mirroredOutputTypes: ["HDMI"],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "KIT SKU: receivers included in the box. Mirrored HDMI outputs are features, not extra matrix outputs.",
    control: ["IR - verify", "RS-232 - verify", "LAN/IP - verify"],
    audio: ["Audio support - verify datasheet"],
    power: ["PoC/PoH/PSU - verify datasheet"],
    comparisonNotes: ["Mirrored HDMI outputs must not be counted as independent routed outputs."],
    dataSource: "known-wyrestorm-compare-profile",
  },
  {
    sku: "MXV-0404-H2A-KIT-V2",
    aliases: ["MXV-0404-H2A-KIT-V2", "MXV0404H2AKITV2"],
    name: "MXV-0404-H2A-KIT-V2 4x4 HDBaseT Matrix Kit",
    family: "MXV Matrix Kit",
    productClass: "HDBaseT matrix kit",
    systemRole: "4x4 fixed I/O matrix kit for routing four HDMI sources to four independently routed HDBaseT display zones.",
    matrixSize: "4x4",
    routedInputCount: 4,
    routedOutputCount: 4,
    inputTypes: ["HDMI"],
    outputTypes: ["HDBaseT"],
    routedOutputTypes: ["HDBaseT"],
    transport: ["HDMI", "HDBaseT"],
    technologyFamily: "HDBaseT Matrix Kit",
    maxResolution: "4K60 4:4:4 - verify datasheet",
    resolution: "4K60 4:4:4 - verify datasheet",
    chroma: "4:4:4 - verify datasheet",
    hdmiVersion: "18Gbps HDMI - verify datasheet",
    hdcpVersion: "Verify datasheet",
    distanceClass: "35m/115ft 4K direction from local product intelligence - verify datasheet",
    mirroredOutputCount: 1,
    mirroredOutputTypes: ["HDMI"],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "KIT SKU: receivers included. Mirrored HDMI is a feature and must not increase the 4x4 matrix size.",
    control: ["CEC", "IR - verify", "RS-232 - verify", "LAN/IP - verify"],
    audio: ["Audio de-embed - verify datasheet"],
    power: ["PoH - verify datasheet", "AC power - verify datasheet"],
    comparisonNotes: ["Routed outputs are four HDBaseT zones. Mirrored HDMI is not a fifth routed matrix output."],
    dataSource: "known-wyrestorm-compare-profile",
  },
  {
    sku: "MXV-0404-H2A-KIT",
    aliases: ["MXV-0404-H2A-KIT", "MXV0404H2AKIT"],
    name: "MXV-0404-H2A-KIT 4x4 HDBaseT Matrix Kit",
    family: "MXV Matrix Kit",
    productClass: "HDBaseT matrix kit",
    systemRole: "4x4 fixed I/O matrix kit for routing four HDMI sources to four independently routed HDBaseT display zones.",
    matrixSize: "4x4",
    routedInputCount: 4,
    routedOutputCount: 4,
    inputTypes: ["HDMI"],
    outputTypes: ["HDBaseT"],
    routedOutputTypes: ["HDBaseT"],
    transport: ["HDMI", "HDBaseT"],
    technologyFamily: "HDBaseT Matrix Kit",
    maxResolution: "4K60 4:4:4 - verify datasheet",
    resolution: "4K60 4:4:4 - verify datasheet",
    chroma: "4:4:4 - verify datasheet",
    hdmiVersion: "18Gbps HDMI - verify datasheet",
    hdcpVersion: "Verify datasheet",
    distanceClass: "35m/115ft 4K direction from 2026 catalog - verify datasheet",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "KIT SKU: includes four receivers per 2026 catalog direction - verify exact package.",
    control: ["CEC - verify", "IR - verify", "RS-232 - verify", "LAN/IP - verify"],
    audio: ["Audio de-embed - verify datasheet"],
    power: ["PoH - verify datasheet"],
    comparisonNotes: ["Routed outputs are four HDBaseT zones; do not derive output count from accessory or package lines."],
    dataSource: "2026-wyrestorm-sku-catalog-known-topology",
  },
  {
    sku: "MX-0404-KIT",
    aliases: ["MX0404KIT", "MX-0404-KIT"],
    name: "MX-0404-KIT 4x4 HDBaseT/HDMI Matrix Kit",
    family: "MX Matrix Kit",
    productClass: "HDBaseT / HDMI matrix kit",
    systemRole: "4x4 fixed I/O matrix kit with three HDBaseT outputs and one HDMI output.",
    matrixSize: "4x4",
    routedInputCount: 4,
    routedOutputCount: 4,
    inputTypes: ["HDMI"],
    outputTypes: ["HDBaseT", "HDMI"],
    routedOutputTypes: ["HDBaseT", "HDMI"],
    transport: ["HDMI", "HDBaseT"],
    technologyFamily: "HDBaseT Matrix Kit",
    maxResolution: "4K60 4:2:0 - verify datasheet",
    resolution: "4K60 4:2:0 - verify datasheet",
    chroma: "4:2:0 - verify datasheet",
    hdmiVersion: "Verify datasheet",
    hdcpVersion: "Verify datasheet",
    distanceClass: "35m/114ft 4K, 70m/228ft 1080p direction from 2026 catalog - verify datasheet",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "KIT SKU: includes three receivers per 2026 catalog direction - verify exact package.",
    control: ["Control features - verify datasheet"],
    audio: ["Audio de-embed - verify datasheet"],
    power: ["PoH - verify datasheet"],
    comparisonNotes: ["Routed outputs are four total: three HDBaseT plus one HDMI. This is not a pure four-output HDBaseT matrix."],
    dataSource: "2026-wyrestorm-sku-catalog-known-topology",
  },
  {
    sku: "MX-0404-HDMI",
    aliases: ["MX0404HDMI", "MX-0404-HDMI"],
    name: "MX-0404-HDMI 4x4 HDMI Matrix",
    family: "MX Matrix",
    productClass: "HDMI matrix",
    systemRole: "4x4 fixed HDMI matrix for routing four HDMI sources to four independently routed HDMI destinations.",
    matrixSize: "4x4",
    routedInputCount: 4,
    routedOutputCount: 4,
    inputTypes: ["HDMI"],
    outputTypes: ["HDMI"],
    routedOutputTypes: ["HDMI"],
    transport: ["HDMI"],
    technologyFamily: "HDMI Matrix",
    maxResolution: "4K60 4:4:4",
    resolution: "4K60 4:4:4",
    chroma: "4:4:4",
    hdmiVersion: "18Gbps HDMI - verify datasheet",
    hdcpVersion: "HDCP 2.2 - verify datasheet",
    distanceClass: "Local HDMI matrix. Confirm cable distance separately.",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "No receiver kit assumption. Treat as local HDMI matrix unless project notes say otherwise.",
    control: ["CEC", "WebUI/API - verify datasheet"],
    audio: ["Audio de-embed", "S/PDIF - verify datasheet"],
    power: ["12V DC power supply - verify datasheet"],
    comparisonNotes: ["Routed outputs are four HDMI destinations. Do not count audio or control connectors as outputs."],
    dataSource: "2026-wyrestorm-sku-catalog-known-topology",
  },
  {
    sku: "MX-0404-SCL",
    aliases: ["MX0404SCL", "MX-0404-SCL"],
    name: "MX-0404-SCL 4x4 Seamless Scaling Matrix",
    family: "MX Scaling Matrix",
    productClass: "HDMI scaling matrix",
    systemRole: "4x4 seamless scaling matrix for routing four sources to four independently routed HDMI destinations.",
    matrixSize: "4x4",
    routedInputCount: 4,
    routedOutputCount: 4,
    inputTypes: ["HDMI"],
    outputTypes: ["HDMI"],
    routedOutputTypes: ["HDMI"],
    transport: ["HDMI"],
    technologyFamily: "Seamless Scaling Matrix",
    maxResolution: "4K60 4:4:4",
    resolution: "4K60 4:4:4",
    chroma: "4:4:4",
    hdmiVersion: "Verify datasheet",
    hdcpVersion: "Verify datasheet",
    distanceClass: "Local HDMI matrix. Confirm cable distance separately.",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "No receiver kit assumption. Treat as local HDMI matrix unless project notes say otherwise.",
    control: ["Control features - verify datasheet"],
    audio: ["Balanced audio de-embed", "S/PDIF audio de-embed"],
    power: ["Power method - verify datasheet"],
    comparisonNotes: ["Scaling and multiview features do not increase matrix size; routed outputs remain four."],
    dataSource: "2026-wyrestorm-sku-catalog-known-topology",
  },
  {
    sku: "MX-0808-H2A-MK2",
    aliases: ["MX-0808-H2A", "MX0808H2A", "MX-0808-H2A-MK2", "MX0808H2AMK2"],
    name: "MX-0808-H2A-MK2 8x8 HDMI Matrix",
    family: "MX Matrix",
    productClass: "HDMI matrix",
    systemRole: "8x8 fixed HDMI matrix for routing eight HDMI sources to eight independently routed HDMI destinations.",
    matrixSize: "8x8",
    routedInputCount: 8,
    routedOutputCount: 8,
    inputTypes: ["HDMI"],
    outputTypes: ["HDMI"],
    routedOutputTypes: ["HDMI"],
    transport: ["HDMI"],
    technologyFamily: "HDMI Matrix",
    maxResolution: "4K60 4:4:4",
    resolution: "4K60 4:4:4",
    chroma: "4:4:4",
    hdmiVersion: "18Gbps HDMI - verify datasheet",
    hdcpVersion: "Verify datasheet",
    distanceClass: "Local HDMI matrix. Confirm cable distance separately.",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "No receiver kit assumption. Treat as local HDMI matrix unless project notes say otherwise.",
    control: ["CEC", "Sygma control - verify datasheet"],
    audio: ["Balanced audio de-embed", "ARC - verify datasheet"],
    power: ["Internal/PSU power - verify datasheet"],
    comparisonNotes: ["Do not infer 16x16 from total physical HDMI ports. This is an 8 input / 8 output matrix."],
    dataSource: "2026-wyrestorm-sku-catalog-known-topology",
  },
  {
    sku: "MX-0808-SCL",
    aliases: ["MX0808SCL", "MX-0808-SCL"],
    name: "MX-0808-SCL 8x8 Seamless Scaling Matrix",
    family: "MX Scaling Matrix",
    productClass: "HDMI / USB-C scaling matrix",
    systemRole: "8x8 seamless scaling matrix for routing eight sources to eight independently routed HDMI destinations.",
    matrixSize: "8x8",
    routedInputCount: 8,
    routedOutputCount: 8,
    inputTypes: ["HDMI", "USB-C"],
    outputTypes: ["HDMI"],
    routedOutputTypes: ["HDMI"],
    transport: ["HDMI", "USB-C"],
    technologyFamily: "Seamless Scaling Matrix",
    maxResolution: "4K60 4:4:4",
    resolution: "4K60 4:4:4",
    chroma: "4:4:4",
    hdmiVersion: "Verify datasheet",
    hdcpVersion: "HDCP 2.3",
    distanceClass: "Local HDMI matrix. Confirm cable distance separately.",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "No receiver kit assumption. Treat as local HDMI matrix unless project notes say otherwise.",
    control: ["Control features - verify datasheet"],
    audio: ["Audio de-embed", "USB-C audio support - verify datasheet"],
    power: ["Power method - verify datasheet"],
    comparisonNotes: ["USB-C is source/input capability here; it must not inflate routed output count."],
    dataSource: "2026-wyrestorm-sku-catalog-known-topology",
  },
  {
    sku: "MX-0812-SCL",
    aliases: ["MX0812SCL", "MX-0812-SCL"],
    name: "MX-0812-SCL 8x12 Advanced Seamless Scaling Matrix",
    family: "MX Scaling Matrix",
    productClass: "HDMI scaling matrix",
    systemRole: "8x12 advanced seamless scaling matrix for routing eight sources to twelve independently routed HDMI destinations.",
    matrixSize: "8x12",
    routedInputCount: 8,
    routedOutputCount: 12,
    inputTypes: ["HDMI"],
    outputTypes: ["HDMI"],
    routedOutputTypes: ["HDMI"],
    transport: ["HDMI"],
    technologyFamily: "Advanced Seamless Scaling Matrix",
    maxResolution: "4K60 4:4:4",
    resolution: "4K60 4:4:4",
    chroma: "4:4:4",
    hdmiVersion: "Verify datasheet",
    hdcpVersion: "HDCP 2.3",
    distanceClass: "Local HDMI matrix. Confirm cable distance separately.",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "No receiver kit assumption. Treat as local HDMI matrix unless project notes say otherwise.",
    control: ["Control features - verify datasheet"],
    audio: ["Audio de-embed - verify datasheet"],
    power: ["Power method - verify datasheet"],
    comparisonNotes: ["Matrix size is 8x12 routed I/O; do not derive it from total connector count."],
    dataSource: "2026-wyrestorm-sku-catalog-known-topology",
  },
  {
    sku: "EXP-MX-0402-H2",
    aliases: ["EXPMX0402H2", "EXP-MX-0402-H2"],
    name: "EXP-MX-0402-H2 4x2 HDMI Matrix Switch",
    family: "Essentials Matrix",
    productClass: "HDMI matrix",
    systemRole: "4x2 HDMI matrix switch for routing four HDMI sources to two independently routed HDMI destinations.",
    matrixSize: "4x2",
    routedInputCount: 4,
    routedOutputCount: 2,
    inputTypes: ["HDMI"],
    outputTypes: ["HDMI"],
    routedOutputTypes: ["HDMI"],
    transport: ["HDMI"],
    technologyFamily: "HDMI Matrix",
    maxResolution: "4K60 4:4:4",
    resolution: "4K60 4:4:4",
    chroma: "4:4:4",
    hdmiVersion: "18Gbps HDMI",
    hdcpVersion: "HDCP 2.2",
    distanceClass: "Local HDMI matrix. Confirm cable distance separately.",
    mirroredOutputCount: 0,
    mirroredOutputTypes: [],
    loopOutputCount: 0,
    loopOutputTypes: [],
    receiverPackage: "No receiver package. Local HDMI matrix switch.",
    control: ["ARC", "CEC", "IR/RS-232 - verify datasheet"],
    audio: ["Analog audio de-embed", "Digital audio de-embed", "ARC"],
    power: ["5V DC power supply - verify datasheet"],
    comparisonNotes: ["Do not count audio, control or accessory ports as matrix outputs."],
    dataSource: "official-product-page-known-topology",
  },
];

export function findKnownWyrestormCompareProfile(sku: string): KnownWyrestormCompareProfile | undefined {
  const canonical = resolveWyrestormSkuAlias(sku);
  const key = normaliseSkuKey(canonical);

  return PROFILES.find((profile) => {
    return normaliseSkuKey(profile.sku) === key || profile.aliases.some((alias) => normaliseSkuKey(alias) === key);
  });
}

export function hydrateWyrestormCompareProfile<T extends Record<string, unknown>>(input: T): T & Record<string, unknown> {
  const rawSku = String(input.sku ?? input.model ?? input.partNumber ?? "");
  const profile = findKnownWyrestormCompareProfile(rawSku);

  if (!profile) {
    return input;
  }

  return {
    ...input,
    ...profile,
    sku: profile.sku,
    name: profile.name,
    title: profile.name,
    family: profile.family,
    category: profile.productClass,
    role: profile.systemRole,
    inputCount: profile.routedInputCount,
    outputCount: profile.routedOutputCount,
    inputs: profile.routedInputCount,
    outputs: profile.routedOutputCount,
    sourceCount: profile.routedInputCount,
    displayCount: profile.routedOutputCount,
    sourceType: profile.inputTypes.join(", "),
    outputTransport: profile.outputTypes.join(", "),
    specTier: profile.dataSource,
  };
}

export function knownWyrestormCompareProfileSkus(): string[] {
  return PROFILES.map((profile) => profile.sku);
}
