export type TemplateBomType = "Required" | "Optional" | "Validate";

export type TemplateBomRow = {
  id: string;
  sku: string;
  description: string;
  role: string;
  qty: number;
  type: TemplateBomType;
  status: string;
  evidence: string;
  notes: string;
};

export type RoomTemplate = {
  id: string;
  name: string;
  vertical: string;
  application: string;
  scale: string;
  summary: string;
  customerNarrative: string;
  architecture: string;
  bom: TemplateBomRow[];
  designNotes: Array<{
    label: string;
    description: string;
  }>;
  assumptions: string[];
  validationItems: string[];
  upgradePaths: string[];
};

export const roomTemplates: RoomTemplate[] = [
  {
    id: "corporate-huddle-apollo",
    name: "Corporate Huddle Room - Apollo BYOD",
    vertical: "Corporate",
    application: "Small meeting room with USB-C, HDMI, wireless presentation, camera, mic, and local display.",
    scale: "4-6 people",
    summary: "Compact meeting room boilerplate for fast deployment where the customer needs a simple join, present, and meet experience.",
    customerNarrative:
      "The room is built around a single WyreStorm Apollo collaboration core so users can walk in with a laptop, connect over USB-C/HDMI or wireless presentation, and use the room camera, speakers, and microphone without a complex control system.",
    architecture:
      "Local presentation and UC appliance at the display, with table cable access, optional wireless dongles, and display audio handled by the room bar unless a separate audio system is specified.",
    bom: [
      {
        id: "apollovx20",
        sku: "APO-VX20-UC",
        description: "Apollo video bar and switcher",
        role: "Room UC and presentation core",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Huddle rooms need a compact camera, audio, switching, and wireless presentation path.",
        notes: "Confirm display input, room width, mounting height, and whether wireless conferencing is required.",
      },
      {
        id: "apovx20mnt",
        sku: "APO-VX20-MNT",
        description: "Apollo video bar wall mounting kit",
        role: "Mounting accessory",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Mounting method depends on display, wall construction, and camera height.",
        notes: "Use where wall mounting is required; otherwise confirm display or furniture mounting.",
      },
      {
        id: "apodg2",
        sku: "APO-DG2",
        description: "Apollo wireless conferencing dongle",
        role: "Optional wireless BYOM accessory",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Wireless collaboration can reduce desk cabling in small meeting spaces.",
        notes: "Confirm whether customer wants dongle-based wireless conferencing or wired-only operation.",
      },
      {
        id: "idb300",
        sku: "IDB-300",
        description: "Dual channel in-desk cable box",
        role: "Table cable access",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Small rooms often need tidy USB-C/HDMI access at the table.",
        notes: "Confirm furniture cut-out, cable tails, and local power availability.",
      },
    ],
    designNotes: [
      { label: "Display", description: "Single flat panel by others, sized for viewing distance and camera position." },
      { label: "Network", description: "Client network for wireless presentation and Teams/Zoom device policies where required." },
      { label: "Power and mounting", description: "Local display power, cable containment, and wall reinforcement by installer." },
    ],
    assumptions: ["Single display", "Local room UC", "No matrix routing", "No ceiling microphone system unless added"],
    validationItems: ["Display mounting height", "USB-C laptop charging expectations", "Wireless presentation policy", "Acoustic suitability"],
    upgradePaths: ["Add APO-COM-MIC for larger table pickup", "Add APO-DG-DOCK for managed dongle storage", "Move to a NetworkHD 500 design if room routing expands"],
  },
  {
    id: "corporate-boardroom-networkhd500",
    name: "Corporate Boardroom - NetworkHD 500",
    vertical: "Corporate",
    application: "Executive boardroom with multiple sources, multiple displays, USB routing, camera support, and high-quality 4K distribution.",
    scale: "12-20 people",
    summary: "Premium boardroom boilerplate for flexible source-to-display routing with a clear UC and presentation pathway.",
    customerNarrative:
      "The room uses NetworkHD 500 to route high-quality 4K sources to multiple displays while keeping USB, control, and future expansion in the design path.",
    architecture:
      "AV-over-IP routing over a managed AV network, with transmitters at source locations, receivers at displays, a NetworkHD controller, and separate USB/camera handling where needed.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "NetworkHD systems need governed control and configuration.",
        notes: "Confirm network isolation, control UI, and commissioning ownership.",
      },
      {
        id: "nhd500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Source endpoint",
        qty: 4,
        type: "Required",
        status: "included",
        evidence: "Four source positions are assumed for boardroom presentation and room PC inputs.",
        notes: "Adjust quantity to confirmed physical sources.",
      },
      {
        id: "nhd500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Three displays are assumed: main display, confidence display, and side/rear display.",
        notes: "Adjust quantity to confirmed display count.",
      },
      {
        id: "nhdusbtrx",
        sku: "NHD-USB-TRX",
        description: "USB over IP transceiver",
        role: "USB transport",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "USB routing is usually required where cameras or room peripherals are shared.",
        notes: "Confirm USB host location, peripheral bandwidth, and whether USB 2.0 is sufficient.",
      },
      {
        id: "cam210ptz",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Room camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Executive rooms commonly need a controllable front-of-room camera.",
        notes: "Confirm platform certification requirements and camera field of view.",
      },
    ],
    designNotes: [
      { label: "Displays", description: "Main and confidence displays by others, sized for table length and content type." },
      { label: "Audio", description: "DSP, microphones, speakers, and amplifier by others unless the design is expanded into a WyreStorm UC path." },
      { label: "Network", description: "Managed AV network with multicast handling, VLAN plan, PoE budget, and commissioning access." },
      { label: "Control", description: "Touch panel or third-party control by others, integrated to NetworkHD presets and display power." },
    ],
    assumptions: ["Managed AV network is available", "Four source endpoints", "Three display endpoints", "USB sharing may be required"],
    validationItems: ["Network readiness", "Source count", "Display count", "USB topology", "Control ownership", "Audio DSP scope"],
    upgradePaths: ["Add NHD-0401-MV for multiview monitoring", "Use NHD-500-DNT-TX where Dante/AES67 workflow is required", "Move to NetworkHD 600 for 10G lossless zero-latency routing"],
  },
  {
    id: "education-classroom-hdbaset",
    name: "Education Classroom - Front-of-Room HDBaseT",
    vertical: "Education",
    application: "Teaching room with wall plate input, USB-C/HDMI presentation, projector or display, and optional room USB.",
    scale: "Standard classroom",
    summary: "Repeatable classroom boilerplate for simple teaching spaces where a lecturer needs reliable front-of-room presentation.",
    customerNarrative:
      "The classroom gives teachers a familiar wall input point with HDMI/USB-C presentation and an HDBaseT path to the display or projector.",
    architecture:
      "In-wall presentation transmitter to a compatible receiver at the display/projector, with USB receiver choice governed by distance and whether USB transport is required.",
    bom: [
      {
        id: "sw130",
        sku: "SW-130-TX-UK",
        description: "In-wall HDMI and USB-C HDBaseT transmitter",
        role: "Teaching input point",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Classrooms need a robust lecturer connection point at the teaching wall or desk.",
        notes: "Confirm regional wall box format, cable path, and whether USB is required.",
      },
      {
        id: "rx500",
        sku: "RX-500",
        description: "Short-distance HDBaseT receiver with USB",
        role: "Receiver path for shorter USB-required runs",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "RX-500 can be used for shorter SW-130 receiver connections where USB is required.",
        notes: "If USB is not required, value-engineer to any compatible WyreStorm HDBT 2.0 receiver that fits distance and resolution.",
      },
      {
        id: "rx700",
        sku: "RX-700",
        description: "Longer-distance HDBaseT receiver with USB",
        role: "Receiver path for longer USB-required runs",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "RX-700 is the longer-distance SW-130 receiver path.",
        notes: "Use when the cable run or design requirement needs the longer SW-130 receive path.",
      },
      {
        id: "cam210",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Optional lecture camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Hybrid teaching may require a controllable camera.",
        notes: "Confirm whether lecture capture or conferencing is in scope.",
      },
    ],
    designNotes: [
      { label: "Display/projector", description: "Interactive display or projector by others, selected by room size and content legibility." },
      { label: "Audio", description: "Classroom speakers, amplifier, assistive listening, and microphones by others." },
      { label: "Control", description: "Simple display power/input control or third-party room control by others." },
      { label: "Cabling", description: "Certified category cabling and containment between wall plate and display/projector." },
    ],
    assumptions: ["Single teaching display path", "One lecturer input point", "USB may or may not be required"],
    validationItems: ["USB requirement", "Cable distance", "Display type", "Control scope", "Room audio owner"],
    upgradePaths: ["Use SW-120-TX3 with RX3-100 for HDBaseT 3.0 performance", "Add camera and USB extension for hybrid teaching", "Move to NetworkHD 100/500 for multi-room routing"],
  },
  {
    id: "education-lecture-capture-networkhd",
    name: "Education Lecture Capture - NetworkHD 100",
    vertical: "Education",
    application: "Lecture theatre with source distribution, confidence display, capture/overflow display, and multiview monitoring.",
    scale: "Lecture theatre",
    summary: "Cost-effective lecture theatre template for source distribution and monitoring using NetworkHD 100.",
    customerNarrative:
      "The theatre routes teaching sources across local displays and monitoring points while keeping source and display endpoints scalable.",
    architecture:
      "NetworkHD 100 encoders at sources, decoders at displays, a multiview decoder for monitoring, and a NetworkHD controller on a governed AV network.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "NetworkHD endpoint routing needs a controller.",
        notes: "Confirm network isolation and AV/IT ownership.",
      },
      {
        id: "nhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Source endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes lectern PC, laptop input, and document/source feed.",
        notes: "Adjust to confirmed source count.",
      },
      {
        id: "nhd120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display endpoint",
        qty: 4,
        type: "Required",
        status: "included",
        evidence: "Assumes projector/display, confidence monitor, overflow, and capture/preview display.",
        notes: "Adjust to confirmed display and capture endpoints.",
      },
      {
        id: "nhd150rx",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Monitoring multiview",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Lecture support staff often need a multiview of active sources.",
        notes: "Confirm source window count and monitoring display location.",
      },
      {
        id: "camndi",
        sku: "CAM-210-NDI-PTZ",
        description: "NDI PTZ camera",
        role: "Lecture capture camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Lecture capture may require a PTZ camera with network workflow support.",
        notes: "Confirm NDI, USB, HDMI, or capture appliance input path.",
      },
    ],
    designNotes: [
      { label: "Capture appliance", description: "Recording/streaming appliance or platform by others if not part of the WyreStorm scope." },
      { label: "Audio", description: "Lectern mic, radio mic, ceiling mics, DSP, and PA integration by others." },
      { label: "Network", description: "Managed AV VLAN, multicast handling, PoE budget, and AV/IT commissioning window." },
    ],
    assumptions: ["Three source endpoints", "Four display endpoints", "One multiview support monitor", "Managed AV network"],
    validationItems: ["Capture workflow", "Camera output format", "Source count", "Display count", "Network readiness", "Audio handoff"],
    upgradePaths: ["Move to NetworkHD 500 for 4K60 4:4:4 and stronger USB workflows", "Add more NHD-150-RX decoders for multiple monitoring positions", "Use NetworkHD 600 where lossless zero-latency routing is required"],
  },
  {
    id: "retail-signage-networkhd100",
    name: "Retail Multi-Zone Signage - NetworkHD 100",
    vertical: "Retail",
    application: "Store signage rollout with one or more media sources feeding several display zones.",
    scale: "Single store or rollout template",
    summary: "Retail boilerplate for flexible signage distribution without building a complex control-room style system.",
    customerNarrative:
      "NetworkHD 100 gives the store a scalable way to route signage content to multiple zones and add displays over time.",
    architecture:
      "Central signage sources encode onto a managed AV network, with a decoder at each display or zone and a controller for routing presets.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Store signage routing needs simple preset management.",
        notes: "Confirm whether the store or central IT team owns presets.",
      },
      {
        id: "nhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Signage source endpoint",
        qty: 2,
        type: "Required",
        status: "included",
        evidence: "Assumes two signage/media player feeds.",
        notes: "Adjust to confirmed media player count.",
      },
      {
        id: "nhd120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display zone endpoint",
        qty: 8,
        type: "Required",
        status: "included",
        evidence: "Assumes eight display zones across retail floor, window, and service areas.",
        notes: "Adjust to zone/display count.",
      },
      {
        id: "nhdrack4",
        sku: "NHD-000-RACK4",
        description: "NetworkHD rack mount",
        role: "Rack mounting",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Rack mounting keeps endpoint hardware organized in rollout installs.",
        notes: "Confirm rack space and whether endpoints are central or display-mounted.",
      },
    ],
    designNotes: [
      { label: "Displays", description: "Commercial displays and mounts by others, chosen for brightness, orientation, and runtime." },
      { label: "Media players", description: "Signage players or CMS endpoints by others unless WyreStorm source hardware is specified." },
      { label: "Network", description: "Store network must support AV-over-IP bandwidth, multicast behaviour, VLAN policy, and PoE budget." },
    ],
    assumptions: ["Two signage sources", "Eight display zones", "Preset routing", "No USB transport"],
    validationItems: ["Exact display count", "Source/player count", "Network readiness", "Mounting and local power", "Content management ownership"],
    upgradePaths: ["Use NHD-150-RX for multiview signage monitoring", "Move to NetworkHD 500 for higher-quality 4K60 paths", "Add dedicated wall processors for fixed LCD walls"],
  },
  {
    id: "retail-lcd-wall-processor",
    name: "Retail Feature Wall - Dedicated LCD Processor",
    vertical: "Retail",
    application: "Entrance or promotional LCD video wall with fixed or semi-flexible layouts.",
    scale: "2x2 to 1x4 wall",
    summary: "Dedicated video wall template where a processor is a cleaner fit than a full AV-over-IP design.",
    customerNarrative:
      "The feature wall uses a dedicated WyreStorm processor to create a simple high-impact display canvas without unnecessary network complexity.",
    architecture:
      "One or more source feeds enter a dedicated wall processor, with outputs feeding each display in the wall. AV-over-IP is only added if routing flexibility is required.",
    bom: [
      {
        id: "sw0204",
        sku: "SW-0204-VW",
        description: "Preset-layout video wall processor",
        role: "Basic wall processor",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Basic 1x4 or 2x2 LCD walls can be served by a dedicated preset-layout processor.",
        notes: "Use when layouts are simple and fixed.",
      },
      {
        id: "sw0206",
        sku: "SW-0206-VW",
        description: "Flexible 6-output video wall processor",
        role: "Alternative wall processor",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "More flexible fixed walls may need the larger dedicated processor path.",
        notes: "Use instead of SW-0204-VW when output count or layout flexibility requires it.",
      },
      {
        id: "exp0401",
        sku: "EXP-SW-0401-8K",
        description: "4x1 HDMI switcher",
        role: "Optional local source switching",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Some retail walls need simple local source selection ahead of the wall processor.",
        notes: "Confirm source count and resolution requirements.",
      },
    ],
    designNotes: [
      { label: "Displays", description: "Matched-bezel displays, wall mounts, power, and display calibration by others." },
      { label: "Source", description: "Media player, signage player, or local source by others unless included separately." },
      { label: "Control", description: "Web GUI/RS-232 handoff to local control or store operations as required." },
    ],
    assumptions: ["Fixed LCD wall", "Simple source behaviour", "No per-display independent routing unless upgraded"],
    validationItems: ["Wall geometry", "Source count", "Canvas vs mirrored content", "Control handoff", "Display bezel compensation"],
    upgradePaths: ["Use SW-0206-VW for more outputs or custom layouts", "Use NetworkHD for per-display routing or distributed content", "Add a local switcher where multiple sources are needed"],
  },
  {
    id: "hospitality-sports-bar-networkhd",
    name: "Hospitality Sports Bar - Multi-Zone AV",
    vertical: "Hospitality",
    application: "Bar or hospitality venue with multiple TV zones, source routing, and optional multiview displays.",
    scale: "8-16 displays",
    summary: "Sports bar boilerplate for flexible source routing to many displays without fixed matrix I/O limits.",
    customerNarrative:
      "NetworkHD lets staff route sports, signage, and venue content to different display zones while keeping the system expandable.",
    architecture:
      "AV-over-IP endpoints at sources and displays, controller presets for common events, and optional multiview decoder for featured screens.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Multi-zone hospitality routing needs preset control.",
        notes: "Confirm operator interface and who changes presets.",
      },
      {
        id: "nhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Source endpoint",
        qty: 6,
        type: "Required",
        status: "included",
        evidence: "Assumes six venue sources such as satellite boxes, signage, media, or house feed.",
        notes: "Adjust to source count and rights-management workflow.",
      },
      {
        id: "nhd120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display endpoint",
        qty: 12,
        type: "Required",
        status: "included",
        evidence: "Assumes twelve displays across bar, booth, and feature areas.",
        notes: "Adjust to confirmed display count and zone behaviour.",
      },
      {
        id: "nhd150",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Feature multiview display",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Sports bars often want a feature screen showing multiple games.",
        notes: "Confirm source windows, display location, and desired layout.",
      },
    ],
    designNotes: [
      { label: "Displays", description: "Venue TVs, mounts, local power, and IR/control needs by others." },
      { label: "Audio", description: "Venue audio zoning, DSP, amplifiers, and speakers by others; confirm audio follows video or fixed zones." },
      { label: "Network", description: "Managed AV network with PoE and suitable multicast configuration." },
    ],
    assumptions: ["Six sources", "Twelve displays", "Preset routing", "Audio zoning by others"],
    validationItems: ["Display count", "Source rights and boxes", "Audio-follow-video behaviour", "Network readiness", "Staff control method"],
    upgradePaths: ["Move to NetworkHD 500 for premium 4K60 venue paths", "Add extra NHD-150-RX for multiple feature screens", "Use seamless matrix where fixed I/O is preferred"],
  },
  {
    id: "hospitality-ballroom-hybrid",
    name: "Hospitality Ballroom - Divisible Room",
    vertical: "Hospitality",
    application: "Hotel ballroom or event space with divisible zones, lectern inputs, display routing, USB, and mixed event modes.",
    scale: "Divisible event room",
    summary: "Event-space boilerplate where a hybrid matrix and HDBaseT approach can be simpler than full AV-over-IP.",
    customerNarrative:
      "The ballroom supports different room divides and event layouts while keeping source switching, local inputs, and display routing under a single structured design.",
    architecture:
      "Hybrid matrix core with local HDBaseT transmitter/receiver paths, scalable displays, USB where required, and control presets for common room modes.",
    bom: [
      {
        id: "mx1007",
        sku: "MX-1007-HYB",
        description: "10x7 hybrid seamless matrix",
        role: "Room routing and processing core",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Divisible spaces often benefit from a hybrid matrix core with mixed input/output paths.",
        notes: "Confirm exact I/O, divide modes, audio DSP role, and control integration.",
      },
      {
        id: "sw120",
        sku: "SW-120-TX3",
        description: "HDBaseT 3.0 transmitter",
        role: "Remote event input",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Event rooms usually need remote presenter inputs at lectern or wall positions.",
        notes: "Confirm input locations and whether wall-plate version is required.",
      },
      {
        id: "rx3100",
        sku: "RX3-100",
        description: "HDBaseT 3.0 receiver",
        role: "Remote receive path",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "SW-120-TX3 paths require a compatible receive side unless terminating into a compatible matrix path.",
        notes: "Confirm whether the receive path is RX3-100 or a matrix input/output path.",
      },
      {
        id: "cam210",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Event camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Hybrid events may need a camera feed for streaming or overflow.",
        notes: "Confirm camera control and platform requirements.",
      },
    ],
    designNotes: [
      { label: "Displays/projectors", description: "Projectors, displays, screens, lifts, and mounts by others." },
      { label: "Audio", description: "Ballroom microphones, DSP, amplifiers, and speaker zoning by others." },
      { label: "Control", description: "Room combine/divide presets, panel UI, and event support workflow by control contractor." },
    ],
    assumptions: ["Divisible room", "Multiple presenter positions", "Fixed I/O routing preferred over full AV-over-IP"],
    validationItems: ["Room divide modes", "Exact source/display I/O", "Audio zoning", "Control presets", "USB/camera requirements"],
    upgradePaths: ["Use NetworkHD 500 for more flexible distributed routing", "Add more SW-120-TX3/RX3-100 paths for remote inputs", "Add NHD-0401-MV where event preview monitoring is required"],
  },
  {
    id: "healthcare-simulation-lab",
    name: "Healthcare Simulation Lab - Capture and Review",
    vertical: "Healthcare",
    application: "Clinical simulation room with cameras, source capture, local review, and observation display routing.",
    scale: "Simulation room plus observation",
    summary: "Healthcare training template for routing cameras and room sources to observation, recording, and review displays.",
    customerNarrative:
      "The lab captures clinical training activity and routes it to observation and review spaces while preserving a clear technical handoff to recording and audio systems.",
    architecture:
      "NetworkHD 500 endpoints for high-quality source/display routing, PTZ camera path, optional multiview monitoring, and governed USB/network handoff.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Simulation workflows need repeatable routing presets.",
        notes: "Confirm AV/IT ownership and network isolation.",
      },
      {
        id: "nhd500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Source/camera endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes camera/source feeds from simulation room to observation/review.",
        notes: "Adjust to camera and source count.",
      },
      {
        id: "nhd500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Observation/review display endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes observation display, review display, and room confidence display.",
        notes: "Adjust to confirmed display count.",
      },
      {
        id: "nhd0401",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Observation multiview",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Observers may need a composite view of multiple feeds.",
        notes: "Confirm source window count and observation workflow.",
      },
      {
        id: "camndi",
        sku: "CAM-210-NDI-PTZ",
        description: "NDI PTZ camera",
        role: "Training camera",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Simulation labs often need multiple controllable camera views.",
        notes: "Confirm NDI/HDMI/USB capture path and medical privacy requirements.",
      },
    ],
    designNotes: [
      { label: "Recording platform", description: "Simulation recording, annotation, and debrief platform by others." },
      { label: "Audio", description: "Room microphones, observation audio, DSP, and privacy controls by others." },
      { label: "Network/security", description: "Clinical network approval, VLANs, user access, and data handling by customer IT." },
    ],
    assumptions: ["Three routed feeds", "Three display endpoints", "Observation room included", "Recording system by others"],
    validationItems: ["Camera count", "Recording platform inputs", "Privacy requirements", "Audio capture", "Network/security approval"],
    upgradePaths: ["Move to NetworkHD 600 for lossless zero-latency critical review", "Add NHD-USB-TRX for USB peripheral sharing", "Add more NHD-0401-MV outputs for multi-room observation"],
  },
  {
    id: "government-control-room-networkhd600",
    name: "Government Control Room - NetworkHD 600",
    vertical: "Government",
    application: "Command and control space with low-latency source routing, wall displays, operator positions, and monitoring.",
    scale: "Control room",
    summary: "High-performance control-room boilerplate for demanding routing and display-wall environments.",
    customerNarrative:
      "NetworkHD 600 provides a high-performance AVoIP backbone for mission-style rooms where latency, quality, and flexible routing matter.",
    architecture:
      "10G AV-over-IP transceivers at sources and displays, governed network switching, controller, and optional fibre transceivers where distances or topology require them.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Control rooms need governed routing and preset control.",
        notes: "Confirm security, network isolation, and control UI requirements.",
      },
      {
        id: "nhd600trx",
        sku: "NHD-600-TRX",
        description: "NetworkHD 600 10G transceiver",
        role: "10G source/display endpoint",
        qty: 10,
        type: "Required",
        status: "included",
        evidence: "Assumes mixed source and display endpoints for a control room backbone.",
        notes: "Split final quantity by source/display positions after layout confirmation.",
      },
      {
        id: "nhd600trxf",
        sku: "NHD-600-TRXF",
        description: "NetworkHD 600 fibre transceiver",
        role: "Fibre endpoint option",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Fibre may be required for distance, isolation, or rack topology.",
        notes: "Confirm fibre plant, optics, and endpoint locations.",
      },
      {
        id: "nhdrack1u",
        sku: "NHD-RACK-1U",
        description: "NetworkHD rack mount",
        role: "Endpoint mounting",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Rack mounting is commonly required for centralized endpoint hardware.",
        notes: "Confirm rack layout and endpoint mounting positions.",
      },
    ],
    designNotes: [
      { label: "Video wall", description: "Display wall, mounts, power, wall controller needs, and calibration by others unless a WyreStorm wall processor is selected." },
      { label: "Network", description: "10G switching, multicast handling, VLANs, security hardening, and fibre/optics design by AV/IT team." },
      { label: "Operator audio/control", description: "Audio monitoring, KVM, operator consoles, and control UI by others or separate design scope." },
    ],
    assumptions: ["10 endpoints", "10G AV network", "Control room display wall", "Security review required"],
    validationItems: ["Endpoint count", "10G network design", "Fibre requirement", "Wall behaviour", "Control/security policy"],
    upgradePaths: ["Add dedicated SW-0206-VW where fixed wall processing is preferable", "Add additional NHD-600 endpoints by operator position", "Use NetworkHD 500 for less demanding rooms"],
  },
  {
    id: "venue-worship-overflow-networkhd500",
    name: "Venue Worship - Overflow and Stage Feeds",
    vertical: "Venue",
    application: "House of worship or performance venue with camera/source routing to overflow, confidence, lobby, and recording displays.",
    scale: "Medium venue",
    summary: "Venue boilerplate for routing stage and camera feeds around a building without locking into fixed matrix I/O.",
    customerNarrative:
      "NetworkHD 500 routes service or event feeds to overflow and support areas, with optional multiview monitoring for production staff.",
    architecture:
      "NetworkHD 500 encoders at production/source locations, decoders at displays, controller presets, and optional PTZ camera and multiview processor.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Venue routing needs simple route presets for services and events.",
        notes: "Confirm volunteer/operator control method.",
      },
      {
        id: "nhd500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Production source endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes program feed, camera feed, and presentation feed.",
        notes: "Adjust to confirmed production outputs.",
      },
      {
        id: "nhd500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display endpoint",
        qty: 5,
        type: "Required",
        status: "included",
        evidence: "Assumes lobby, overflow, nursery, confidence, and production monitor displays.",
        notes: "Adjust to display count and zones.",
      },
      {
        id: "nhd0401",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Production multiview",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Production teams often need a multiview of program, camera, and presentation feeds.",
        notes: "Confirm source count and output display.",
      },
      {
        id: "camndi",
        sku: "CAM-210-NDI-PTZ",
        description: "NDI PTZ camera",
        role: "Venue camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "PTZ camera can support overflow and recording workflows.",
        notes: "Confirm camera control and production switcher integration.",
      },
    ],
    designNotes: [
      { label: "Production system", description: "Switcher, recording/streaming platform, comms, and broadcast audio by others." },
      { label: "Displays", description: "Lobby, overflow, confidence, and support displays by others." },
      { label: "Network", description: "Managed AV network and any separation from general venue IT by others." },
    ],
    assumptions: ["Three production feeds", "Five display endpoints", "Managed AV network", "Audio handled by venue system"],
    validationItems: ["Production source outputs", "Display count", "Network readiness", "Camera control", "Audio embedding/de-embedding needs"],
    upgradePaths: ["Move to NetworkHD 600 for zero-latency high-performance routing", "Add more NHD-0401-MV monitoring positions", "Use dedicated HDMI/HDBaseT extension for simple point-to-point overflow"],
  },
  {
    id: "transport-operations-signage",
    name: "Transport Operations - Status Displays",
    vertical: "Transport",
    application: "Transport office or station back-of-house with status dashboards, service feeds, and staff information displays.",
    scale: "Operations suite",
    summary: "Transport template for routing live information displays and operational sources across staff areas.",
    customerNarrative:
      "The system routes operational dashboards and video feeds to multiple staff-facing displays, supporting quick updates and clear zone control.",
    architecture:
      "NetworkHD 100 for cost-effective AV-over-IP distribution, with a controller, source encoders, display decoders, and optional multiview display for supervisors.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Operational display routing needs managed presets and control.",
        notes: "Confirm whether operations or IT owns route changes.",
      },
      {
        id: "nhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Operational source endpoint",
        qty: 4,
        type: "Required",
        status: "included",
        evidence: "Assumes status dashboard, CCTV/service feed, timetable feed, and staff message source.",
        notes: "Adjust to confirmed source systems.",
      },
      {
        id: "nhd120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display endpoint",
        qty: 6,
        type: "Required",
        status: "included",
        evidence: "Assumes six staff displays across operations, break, and supervisor spaces.",
        notes: "Adjust to display count and security zones.",
      },
      {
        id: "nhd150",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Supervisor multiview",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Supervisors may need multiple status feeds on one screen.",
        notes: "Confirm feed count and layout requirements.",
      },
    ],
    designNotes: [
      { label: "Data/source systems", description: "Timetable, CCTV, dashboard, and status systems by others." },
      { label: "Displays", description: "Commercial displays and mounts by others, selected for runtime and visibility." },
      { label: "Security", description: "Network access, source permissions, and operational security policy by customer IT." },
    ],
    assumptions: ["Four operational sources", "Six displays", "No USB transport", "Managed AV network"],
    validationItems: ["Source system outputs", "Display count", "Security zones", "Network readiness", "Control ownership"],
    upgradePaths: ["Use NetworkHD 500 for higher-quality 4K60 dashboard feeds", "Add more NHD-150-RX multiview points", "Use dedicated processors for fixed wall displays"],
  },
  {
    id: "residential-media-matrix",
    name: "Residential Media Room - Local Matrix",
    vertical: "Residential",
    application: "Premium media room with several HDMI sources, main display/projector, secondary display, and local audio handoff.",
    scale: "Single media room",
    summary: "Residential-style boilerplate for a fixed-I/O media room where a simple local matrix is better than AV-over-IP.",
    customerNarrative:
      "The room uses a compact WyreStorm HDMI matrix to route local sources to the main display and secondary display path without unnecessary network complexity.",
    architecture:
      "Local HDMI matrix with optional switcher ahead of it, display/projector outputs, ARC/audio handoff as required, and control integration by others.",
    bom: [
      {
        id: "expmx0402",
        sku: "EXP-MX-0402-H2",
        description: "4x2 HDMI matrix",
        role: "Local source routing",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Fixed media rooms often need several HDMI sources to feed two display paths.",
        notes: "Confirm source count, display count, audio return, and control requirements.",
      },
      {
        id: "expsw0401",
        sku: "EXP-SW-0401-8K",
        description: "4x1 HDMI switcher",
        role: "Optional local source expansion",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Useful where additional local HDMI source selection is required.",
        notes: "Confirm bandwidth and source compatibility before adding.",
      },
      {
        id: "rx70",
        sku: "RX-70-4K",
        description: "HDBaseT receiver",
        role: "Optional remote display receive path",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "A remote projector/display may need HDBaseT extension.",
        notes: "Confirm transmitter/output compatibility, distance, and cable grade.",
      },
    ],
    designNotes: [
      { label: "Sources", description: "Media players, game consoles, set-top boxes, and AVR by others." },
      { label: "Displays/audio", description: "Projector/display, AVR, speakers, and subwoofer system by others." },
      { label: "Control", description: "Residential control processor, handheld remote, or app control by others." },
    ],
    assumptions: ["Four HDMI sources", "Two display paths", "Fixed local routing", "No USB transport"],
    validationItems: ["Source bandwidth", "ARC/eARC expectations", "Projector distance", "Control integration", "HDR/HDCP requirements"],
    upgradePaths: ["Use an 8x8 seamless matrix for more sources/displays", "Move to HDBaseT or AV-over-IP where sources are distributed", "Add dedicated audio de-embedding where AVR handoff requires it"],
  },
];

export const roomTemplateVerticals = ["All", ...Array.from(new Set(roomTemplates.map((template) => template.vertical)))];

