import type { RoomTemplate } from "./roomTemplates";
import { byOthersRow, completeDesignPlaceholders } from "./roomTemplatePlaceholders";

export const extraRoomTemplates: RoomTemplate[] = [
  {
    id: "corporate-reception-townhall-networkhd100",
    name: "Corporate Reception and Town Hall Displays - NetworkHD 100",
    vertical: "Corporate",
    application: "Reception, staff cafe or town hall area with signage, company announcements, live laptop inputs and occasional all-hands presentation feeds.",
    scale: "Corporate front-of-house / all-hands area",
    summary: "Recognisable corporate template for lobby signage and town hall display routing using a cost-effective NetworkHD 100 backbone.",
    customerNarrative:
      "The customer can route signage, welcome messages, company updates and occasional presentation feeds to reception, staff cafe and all-hands displays without building a complex boardroom system.",
    architecture:
      "NetworkHD 100 encoders sit at signage/player and presentation source locations. Decoders feed reception, cafe and town hall displays. A controller provides basic routing and presets for normal signage, event mode and all-hands presentation mode.",
    bom: [
      {
        id: "corp-reception-ctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP routing and preset control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Reception and town hall display systems need simple preset control for signage and event modes.",
        notes: "Confirm whether presets are controlled by facilities, reception, IT or AV support.",
      },
      {
        id: "corp-reception-120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Signage and presentation source endpoints",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes signage player, presentation laptop/PC and event feed source.",
        notes: "Adjust to confirmed signage, event and local input source count.",
      },
      {
        id: "corp-reception-120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display endpoints",
        qty: 6,
        type: "Required",
        status: "included",
        evidence: "Assumes displays in reception, cafe, waiting area and all-hands space.",
        notes: "Adjust to confirmed display count and display locations.",
      },
      {
        id: "corp-reception-150rx",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Optional welcome / event multiview output",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Reception or town hall displays may need mixed layouts during company events.",
        notes: "Confirm whether one screen needs to show multiple sources at the same time.",
      },
      ...completeDesignPlaceholders("corp-reception", [
        byOthersRow(
          "corp-reception",
          "signage-cms-player",
          "Digital signage CMS, media players and content management licences",
          "Content source by others",
          "Replace with the customer's signage platform, media player hardware and content ownership model.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Operational modes", description: "Define normal signage, visitor welcome, all-hands, emergency message and local presentation modes." },
      { label: "Content ownership", description: "Confirm whether marketing, reception, HR, facilities or IT owns the displayed content." },
      { label: "Network", description: "NetworkHD 100 is suitable where a cost-effective routed display system is needed and the network can support it." },
      { label: "Audio", description: "Town hall audio should be designed separately if microphones, PA or Teams/Zoom audio are required." },
    ],
    assumptions: ["Three source endpoints", "Six display endpoints", "Preset routing", "Signage platform by others"],
    validationItems: ["Display count", "Signage source count", "Who controls presets", "Network readiness", "Event audio requirement"],
    upgradePaths: ["Move to NetworkHD 500 where higher quality or USB is needed", "Add NHD-150-RX for multiview event layouts", "Add camera/capture equipment for all-hands streaming"],
  },
  {
    id: "corporate-training-suite-matrix-uc",
    name: "Corporate Training Suite - Matrix, UC and Capture Ready",
    vertical: "Corporate",
    application: "Training room with trainer source, delegate display, confidence monitor, camera path, optional recording and hybrid meeting support.",
    scale: "Training room / seminar room",
    summary: "Corporate training room template where fixed source/display behaviour makes matrix or hybrid matrix simpler than full AV-over-IP.",
    customerNarrative:
      "The room gives trainers a reliable presentation path, display routing, camera support and optional hybrid or recording capability without overcomplicating the design.",
    architecture:
      "A hybrid matrix or local switching core handles the main source/display paths. HDBaseT transmitter/receiver paths support remote presenter or display locations. Camera and USB/capture paths are validated against the training workflow.",
    bom: [
      {
        id: "corp-training-mx1007",
        sku: "MX-1007-HYB",
        description: "Hybrid seamless matrix",
        role: "Room routing and processing core",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Training rooms often have fixed I/O but need polished source/display routing.",
        notes: "Confirm exact input/output count before locking matrix model.",
      },
      {
        id: "corp-training-sw120",
        sku: "SW-120-TX3",
        description: "HDBaseT 3.0 transmitter",
        role: "Remote trainer or floor box input",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Training rooms often need remote presenter positions or floor/table inputs.",
        notes: "Confirm input locations and receiver/matrix termination path.",
      },
      {
        id: "corp-training-rx3100",
        sku: "RX3-100",
        description: "HDBaseT 3.0 receiver",
        role: "Remote receive path",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "HDBaseT receivers are required where remote display/input paths do not terminate directly into compatible hardware.",
        notes: "Confirm distance, cable type and endpoint location.",
      },
      {
        id: "corp-training-camndi",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Trainer-tracking camera feeding the capture bridge",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "CAM-0402-BRG requires a camera source; add this PTZ camera when hybrid/recording is selected.",
        notes: "Add only when CAM-0402-BRG is included. Confirm camera count and mounting position.",
      },
      {
        id: "corp-training-cambridge",
        sku: "CAM-0402-BRG",
        description: "Camera bridge / mixer",
        role: "Camera and capture bridge",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Hybrid training or recording may require a clean camera/capture feed.",
        notes: "Confirm camera count, USB host, HDMI/USB output and meeting platform. Requires CAM-210-PTZ (or equivalent) as its camera source.",
      },
      ...completeDesignPlaceholders("corp-training", [
        byOthersRow(
          "corp-training",
          "recording-platform",
          "Recording, lecture capture or webinar platform",
          "Capture platform by others",
          "Replace with Panopto, Teams, Zoom, hardware recorder, streaming encoder or customer-approved capture system.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Room modes", description: "Define Present, Hybrid Training, Recording, Group Discussion and Breakout modes." },
      { label: "USB/camera", description: "Confirm whether the USB host is a laptop, room PC, Teams device or capture appliance." },
      { label: "Matrix vs AVoIP", description: "Use matrix where I/O is predictable; move to AVoIP if more rooms, overflow areas or flexible routing are added." },
    ],
    assumptions: ["Fixed training room I/O", "Hybrid/capture possible", "Audio and conferencing platform by others"],
    validationItems: ["Exact source/display count", "Camera workflow", "USB host location", "Recording platform", "Audio DSP scope"],
    upgradePaths: ["Move to NetworkHD 500 for flexible multi-room routing", "Add NHD-0401-MV for trainer/support multiview", "Add Dante-capable audio path where DSP integration requires it"],
  },
  {
    id: "education-library-learning-commons-networkhd100",
    name: "Education Library and Learning Commons - NetworkHD 100",
    vertical: "Education",
    application: "Library or open learning area with signage, study-zone displays, helpdesk display, presentation input and occasional event content.",
    scale: "Library / learning commons",
    summary: "Education template for flexible low-bandwidth distribution across open learning areas and student-facing display zones.",
    customerNarrative:
      "The library can route signage, announcements, study support content and presentation feeds to multiple display zones while keeping the system easy to expand later.",
    architecture:
      "NetworkHD 100 encoders handle signage and occasional presentation sources. Decoders sit behind each display zone. Presets route content to quiet study, helpdesk, entrance and event areas.",
    bom: [
      {
        id: "library-ctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing and preset control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Shared learning zones need simple preset routing rather than manual repatching.",
        notes: "Confirm whether library staff, IT or AV support controls presets.",
      },
      {
        id: "library-120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Source endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes signage player, helpdesk PC and occasional presentation source.",
        notes: "Adjust to confirmed source count.",
      },
      {
        id: "library-120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display zone endpoint",
        qty: 7,
        type: "Required",
        status: "included",
        evidence: "Assumes entrance, helpdesk, study zones and event display positions.",
        notes: "Adjust to confirmed display count and zoning.",
      },
      {
        id: "library-wireless",
        sku: "SW-640L-TX-W",
        description: "Wireless presentation system",
        role: "Optional student/staff sharing source",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Open learning areas may need occasional wireless sharing without fixed lectern cabling.",
        notes: "Confirm wireless policy, guest network and screen-sharing expectations.",
      },
      ...completeDesignPlaceholders("education-library", [
        byOthersRow(
          "education-library",
          "digital-signage-platform",
          "School digital signage platform and media players",
          "Content platform by others",
          "Replace with the selected signage software, player hardware and content management responsibility.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Zones", description: "Define entrance, helpdesk, quiet study, group work and event display zones." },
      { label: "Noise", description: "Most library zones are visual-first; audio should be considered only where it is operationally acceptable." },
      { label: "Expansion", description: "NetworkHD 100 is a practical fit where more display zones may be added later." },
    ],
    assumptions: ["Three sources", "Seven display zones", "Low-bandwidth routed display system", "Mostly visual content"],
    validationItems: ["Display count", "Content source count", "Wireless sharing policy", "Network readiness", "Audio/noise policy"],
    upgradePaths: ["Move to NetworkHD 500 for higher quality or stronger USB needs", "Add NHD-150-RX for helpdesk/source monitoring", "Add camera/capture for library events"],
  },
  {
    id: "education-esports-media-lab-networkhd500",
    name: "Education eSports and Media Lab - NetworkHD 500",
    vertical: "Education",
    application: "eSports, media or digital arts lab with multiple PCs, displays, instructor monitoring, recording and flexible source routing.",
    scale: "eSports / media teaching lab",
    summary: "Specialist education template for routing student, instructor and production feeds around a media or eSports lab.",
    customerNarrative:
      "The lab allows instructors or support staff to route student PCs, instructor content, production feeds and review outputs to displays or monitoring points for teaching, coaching and recording.",
    architecture:
      "NetworkHD 500 provides the routed AV layer, with encoders at selected PCs or production sources and decoders at instructor displays, preview monitors and room displays. USB/KVM and capture are validated separately.",
    bom: [
      {
        id: "esports-ctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing and preset control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Labs with multiple PCs and displays need controlled routing and repeatable teaching presets.",
        notes: "Confirm control method and whether students have any routing control.",
      },
      {
        id: "esports-500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "PC / production source endpoint",
        qty: 6,
        type: "Validate",
        status: "validate",
        evidence: "Assumes instructor PC, production PC and selected student or observer feeds.",
        notes: "Adjust to confirmed routed PC/source count.",
      },
      {
        id: "esports-500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display / monitoring endpoint",
        qty: 6,
        type: "Required",
        status: "included",
        evidence: "Assumes instructor display, room display, production preview and observer displays.",
        notes: "Adjust to confirmed display and monitoring positions.",
      },
      {
        id: "esports-mv",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Instructor or production multiview",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "eSports and media labs often need several sources visible at once.",
        notes: "Confirm source window count and where the multiview output is displayed.",
      },
      {
        id: "esports-usb",
        sku: "NHD-USB-TRX",
        description: "USB over IP transceiver",
        role: "Optional KVM / USB interaction path",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Some labs need USB/KVM interaction between instructor, production and selected PCs.",
        notes: "Confirm USB speed, host/device locations and whether USB 2.0 is acceptable.",
      },
      ...completeDesignPlaceholders("education-esports", [
        byOthersRow(
          "education-esports",
          "pcs-and-capture",
          "Gaming PCs, production PCs, capture cards and streaming platform",
          "eSports/media production equipment by others",
          "Replace with the selected PCs, capture hardware, audio interface, streaming platform and software licences.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Latency", description: "Confirm whether routed feeds are for teaching/preview or live play; live play may require local display paths." },
      { label: "USB/KVM", description: "Do not assume USB follows the video route; define host and peripheral locations." },
      { label: "Production", description: "Streaming, recording and shoutcaster workflows are normally a separate production design." },
    ],
    assumptions: ["Six routed sources", "Six display endpoints", "Instructor/production monitoring", "Production equipment by others"],
    validationItems: ["Latency tolerance", "Which PCs are routed", "Display count", "USB/KVM scope", "Streaming/capture platform"],
    upgradePaths: ["Move critical low-latency paths to NetworkHD 600", "Add more NHD-0401-MV outputs for observer displays", "Add camera bridge for presenter/shoutcaster camera workflows"],
  },
  {
    id: "hospitality-hotel-meeting-room-apollo-hdbaset",
    name: "Hotel Meeting Room - Apollo UC and HDBaseT Display Path",
    vertical: "Hospitality",
    application: "Bookable hotel meeting room with laptop presentation, simple video conferencing, one or two displays and tidy guest operation.",
    scale: "Small to medium hotel meeting room",
    summary: "Hospitality meeting-room template for simple guest operation using Apollo UC with optional HDBaseT extension.",
    customerNarrative:
      "The meeting room gives hotel guests a simple laptop, wireless or USB-C meeting experience while allowing the installer to extend display paths neatly where equipment cannot sit at the screen.",
    architecture:
      "Apollo handles the local UC and presentation workflow. HDBaseT or local display connection is selected based on equipment location and cable distance. Audio, room booking and hotel IT policy are validated separately.",
    bom: [
      {
        id: "hotel-meet-apollo",
        sku: "APO-VX20-UC-V2",
        description: "Apollo video bar and switcher",
        role: "Room UC and presentation core",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Hotel meeting rooms need a simple guest-friendly presentation and conferencing experience.",
        notes: "Confirm room size, camera position, laptop connection method and platform expectations.",
      },
      {
        id: "hotel-meet-idb",
        sku: "IDB-300",
        description: "Dual channel in-desk cable box",
        role: "Guest table cable access",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Hotel rooms need tidy user-facing cable access that survives repeated use.",
        notes: "Confirm table type, cable tails, charging expectations and service access.",
      },
      {
        id: "hotel-meet-sw130",
        sku: "SW-130-TX-UK",
        description: "In-wall HDMI and USB-C HDBaseT transmitter",
        role: "Optional remote input point",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Some hotel meeting rooms need a wall or lectern input separate from the display location.",
        notes: "Confirm wall box format, receiver choice and USB requirement.",
      },
      {
        id: "hotel-meet-rx500",
        sku: "RX-500",
        description: "HDBaseT receiver with USB",
        role: "Optional display receive path",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Receiver choice depends on cable distance and USB requirement.",
        notes: "Validate compatibility with the chosen transmitter and required transport features.",
      },
      ...completeDesignPlaceholders("hotel-meeting", [
        byOthersRow(
          "hotel-meeting",
          "room-booking-signage",
          "Room booking panel, signage or hotel event schedule integration",
          "Hotel booking/signage by others",
          "Replace with the hotel-approved room booking, signage or event schedule platform if required.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Guest operation", description: "The control model should be obvious to a first-time user; avoid exposing technical routing." },
      { label: "Hotel IT", description: "Wireless, guest network, Teams/Zoom policy and device management must be confirmed." },
      { label: "Serviceability", description: "Hotel rooms need robust cable access, clear support handoff and easy reset behaviour." },
    ],
    assumptions: ["One room display path", "Guest laptop workflow", "Simple UC requirement", "Audio expansion by others if needed"],
    validationItems: ["Room size", "Laptop connection method", "Hotel wireless policy", "Display location (site survey checklist)", "USB/camera expectation"],
    upgradePaths: ["Add APO-COM-MIC for larger tables", "Use NetworkHD 100/500 where meeting rooms share central sources", "Add PTZ camera for larger training/event rooms"],
  },
  {
    id: "hospitality-restaurant-bar-matrix",
    name: "Restaurant and Bar TV System - Matrix Switching",
    vertical: "Hospitality",
    application: "Restaurant, pub or bar with several screens, local sources, sports boxes, music video, signage and simple staff control.",
    scale: "4-8 display venue",
    summary: "Smaller hospitality template where a fixed matrix can be more practical than AV-over-IP.",
    customerNarrative:
      "The venue can route sports, signage and local sources to several screens using a familiar matrix-style approach that suits smaller fixed systems.",
    architecture:
      "A central matrix routes sources to displays. HDBaseT outputs or receivers are used where display distances require extension. Staff control is kept simple through presets or a third-party control interface.",
    bom: [
      {
        id: "restaurant-mx0808",
        sku: "MX-0808-KIT-V2",
        description: "8x8 HDBaseT matrix kit",
        role: "Central source-to-display routing",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Smaller pubs and restaurants often suit fixed matrix routing better than a full AV-over-IP system.",
        notes: "Confirm current SKU availability, required HDMI version, source count and display distances before quoting.",
      },
      {
        id: "restaurant-nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller for the optional multiview sub-system",
        role: "AV-over-IP routing and preset control for the feature screen",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Required when the optional NetworkHD multiview decoder is included.",
        notes: "Only needed if the NHD-150-RX feature-screen path is added. Controls routing and presets for the parallel AVoIP sub-system.",
      },
      {
        id: "restaurant-nhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder for the optional multiview sub-system",
        role: "Source encoder for the feature-screen multiview path",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Each source feeding the multiview decoder needs its own encoder.",
        notes: "Add one encoder per source that should appear on the feature screen. Confirm source count before quoting.",
      },
      {
        id: "restaurant-nhd150",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Alternative feature-screen multiview path (separate AVoIP sub-system, not fed by the matrix)",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Some bars want a feature screen showing multiple games at once via NetworkHD multiview.",
        notes: "This decoder needs its own NetworkHD 100 encoders (NHD-120-TX) and an NHD-CTL-PRO-V2 controller to function - it does not connect to the matrix. Only add this whole encoder/decoder/controller set together as a parallel system, or omit entirely if the matrix already meets the feature-screen need.",
      },
      {
        id: "restaurant-aoc",
        sku: "CAB-HAOC-20",
        description: "Active optical HDMI cable",
        role: "Optional local long HDMI run",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Some local screen runs can be solved with active optical HDMI rather than additional electronics.",
        notes: "Confirm distance, route, bend radius and bandwidth requirement.",
      },
      ...completeDesignPlaceholders("restaurant-bar", [
        byOthersRow(
          "restaurant-bar",
          "source-receivers",
          "Satellite/IPTV boxes, media players, music video sources and signage players",
          "Venue source devices by others",
          "Replace with the actual Sky/IPTV, media player, signage and licensing-approved source devices.",
        ),
        byOthersRow(
          "restaurant-bar",
          "audio-zoning",
          "Venue audio matrix, mixer, amplifiers and speakers",
          "Hospitality audio by others",
          "Confirm whether audio follows video, is fixed by zone, or is mixed separately by the venue audio system.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Commercial fit", description: "For small fixed venues, matrix can remain the correct cost and simplicity choice." },
      { label: "Audio", description: "Audio zoning is often the hidden design risk; confirm whether each TV zone needs independent audio." },
      { label: "Control", description: "Staff should use named presets such as Main Bar Football, Dining Signage, Private Event and Close Down." },
    ],
    assumptions: ["Up to eight sources and displays", "Central rack", "Mostly fixed routing", "Venue audio by others"],
    validationItems: ["Exact source count", "Display distance", "Audio follows video or fixed zones", "Control method", "Content licensing"],
    upgradePaths: ["Move to NetworkHD 100/500 for larger venues or flexible expansion", "Add multiview feature display", "Use active optical HDMI where one-off cable routes fit"],
  },
  {
    id: "retail-qsr-menu-boards-networkhd100",
    name: "QSR Menu Boards and Order Pickup - NetworkHD 100",
    vertical: "Retail",
    application: "Quick-service restaurant with menu boards, promotional displays, order pickup screens and back-of-house display feeds.",
    scale: "Single QSR site or rollout",
    summary: "Retail/QSR template for routing menu and promotional content to multiple screens using NetworkHD 100.",
    customerNarrative:
      "The site can feed menu boards, promotional displays and order pickup screens from a central set of media players while keeping a repeatable rollout model.",
    architecture:
      "NetworkHD 100 encoders take menu board, promotion and order display sources. Decoders feed each display zone. Presets or fixed routes support daypart menu changes and promotion modes.",
    bom: [
      {
        id: "qsr-ctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Display routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "QSR display estates need repeatable routing and support visibility.",
        notes: "Confirm whether routes are fixed, scheduled or manually changed.",
      },
      {
        id: "qsr-120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Menu/promo source endpoint",
        qty: 4,
        type: "Required",
        status: "included",
        evidence: "Assumes breakfast/lunch menu, promotions, order status and local media source feeds.",
        notes: "Adjust to confirmed media player/source count.",
      },
      {
        id: "qsr-120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Menu board / display endpoint",
        qty: 8,
        type: "Required",
        status: "included",
        evidence: "Assumes multiple menu boards, pickup displays and promotional screens.",
        notes: "Adjust to display count and orientation.",
      },
      {
        id: "qsr-wall",
        sku: "SW-0204-VW",
        description: "Preset-layout video wall processor",
        role: "Optional grouped menu board processor",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Some menu boards behave as a combined display canvas rather than independent screens.",
        notes: "Use only where the menu board wall needs a processor-style canvas rather than independent display feeds. If added, the SW-0204-VW drives its own wall of displays directly and reduces the number of standalone NHD-120-RX decoders required for that wall - it does not add to the 8x NHD-120-RX count. Confirm final RX quantity once the wall vs. independent-screen split is set.",
      },
      ...completeDesignPlaceholders("qsr-menu", [
        byOthersRow(
          "qsr-menu",
          "menu-cms",
          "Menu board CMS, media players and daypart scheduling platform",
          "QSR content system by others",
          "Replace with the approved CMS, players and scheduling platform.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Dayparts", description: "Breakfast, lunch, dinner and promotion modes may require different source/display behaviour." },
      { label: "Rollout", description: "Create a standard model that can be repeated across stores with adjusted display counts." },
      { label: "Display orientation", description: "Portrait/landscape, brightness and mounting height affect the display and content system choice." },
    ],
    assumptions: ["Four content sources", "Eight display endpoints", "Content CMS by others", "Mostly fixed routes"],
    validationItems: ["Number of menu boards", "CMS/player model", "Portrait/landscape orientation", "Network policy", "Rollout standard"],
    upgradePaths: ["Add dedicated wall processor for grouped menu boards", "Move to NetworkHD 500 for higher-quality motion content", "Add monitoring decoder for manager/source preview"],
  },
  {
    id: "retail-car-showroom-customer-experience-networkhd500",
    name: "Car Showroom Customer Experience - NetworkHD 500",
    vertical: "Retail",
    application: "Automotive showroom with feature wall, sales desk displays, finance area display, handover bay and customer presentation sources.",
    scale: "Retail showroom",
    summary: "Premium retail template for showroom displays, feature content and customer presentation spaces.",
    customerNarrative:
      "The showroom can route brand video, finance content, handover videos and sales presentation sources to feature displays and customer areas while keeping premium image quality.",
    architecture:
      "NetworkHD 500 routes showroom sources to feature displays and customer presentation areas. A dedicated wall processor can be added for a fixed feature wall where that is cleaner than per-display AVoIP routing.",
    bom: [
      {
        id: "showroom-ctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Showroom routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Showroom zones need simple routing presets for brand, sales and handover modes.",
        notes: "Confirm whether sales staff, reception or managers operate routes.",
      },
      {
        id: "showroom-500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Showroom source endpoint",
        qty: 5,
        type: "Required",
        status: "included",
        evidence: "Assumes brand player, sales PC, finance PC, handover source and local presentation input.",
        notes: "Adjust to confirmed source count.",
      },
      {
        id: "showroom-500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display endpoint",
        qty: 8,
        type: "Required",
        status: "included",
        evidence: "Assumes showroom feature displays, sales desk displays and handover display zones.",
        notes: "Adjust to display count and customer journey.",
      },
      {
        id: "showroom-vw",
        sku: "SW-0206-VW",
        description: "Dedicated video wall processor",
        role: "Optional feature wall processor",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "A fixed showroom feature wall may be better served by a dedicated processor.",
        notes: "Confirm wall size, canvas behaviour and whether per-display routing is needed. If added, the SW-0206-VW drives the feature wall directly and reduces the number of standalone NHD-500-RX decoders required for that wall - it does not add to the 8x NHD-500-RX count. Confirm final RX quantity once the wall vs. independent-display split is set.",
      },
      {
        id: "showroom-mv",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Optional manager/source preview",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "A manager or reception position may need preview of multiple showroom sources.",
        notes: "Confirm monitoring workflow.",
      },
      ...completeDesignPlaceholders("car-showroom", [
        byOthersRow(
          "car-showroom",
          "interactive-kiosks",
          "Interactive kiosks, sales PCs and manufacturer content players",
          "Customer journey sources by others",
          "Replace with OEM brand content players, sales PCs, finance systems and customer presentation sources.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Customer journey", description: "Map reception, sales desk, vehicle handover, finance and feature wall zones." },
      { label: "Feature wall", description: "Decide whether the wall needs full-canvas processing, independent displays or simple signage." },
      { label: "Control", description: "Sales staff need simple named modes rather than engineering source names." },
    ],
    assumptions: ["Five sources", "Eight displays", "Premium visual quality", "Feature wall optional"],
    validationItems: ["Display estate", "Feature wall behaviour", "Source ownership", "Control user", "Brand content platform"],
    upgradePaths: ["Add SW-0206-VW for dedicated wall processing", "Add more NHD-500 endpoints for expansion", "Move to NetworkHD 600 for ultra-premium zero-latency visualisation"],
  },
  {
    id: "government-courtroom-hearing-room-matrix",
    name: "Courtroom and Hearing Room - Evidence, Presentation and Recording",
    vertical: "Government",
    application: "Courtroom, hearing room or inquiry space with evidence presentation, judge/committee displays, public display, recording and assistive audio requirements.",
    scale: "Courtroom / public hearing room",
    summary: "Public sector template for formal hearing spaces where source routing, evidence display and recording handoff must be controlled.",
    customerNarrative:
      "The room can route evidence, presentation and camera feeds to the correct displays while maintaining a clear handoff to recording, audio and control systems.",
    architecture:
      "A hybrid matrix handles predictable evidence and display routing. HDBaseT paths support remote input/display positions. Camera and recording feeds are validated with the court or hearing platform.",
    bom: [
      {
        id: "court-mx1007",
        sku: "MX-1007-HYB",
        description: "Hybrid seamless matrix",
        role: "Evidence and display routing core",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Courtrooms often need fixed controlled routing rather than open-ended AVoIP.",
        notes: "Confirm input/output count, scaling, recording output and display behaviour.",
      },
      {
        id: "court-sw130",
        sku: "SW-130-TX-UK",
        description: "In-wall HDMI and USB-C HDBaseT transmitter",
        role: "Evidence / presenter input point",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Presenter, advocate or evidence positions may need fixed input points.",
        notes: "Confirm physical wall/furniture format and USB requirement.",
      },
      {
        id: "court-rx700",
        sku: "RX-700",
        description: "HDBaseT receiver",
        role: "Remote display or receive path",
        qty: 3,
        type: "Validate",
        status: "validate",
        evidence: "Courtroom displays may be remote from the rack or evidence desk. RX-700 is the correct receiver generation for the SW-130-TX-UK transmitter above (RX3-100 is a different HDBaseT 3.0 generation and is not a compatible pairing).",
        notes: "Confirm cable distance and endpoint compatibility.",
      },
      {
        id: "court-cam",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Room camera",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Hearing rooms may require controlled camera feeds for recording or remote attendance.",
        notes: "Confirm privacy, recording and platform requirements.",
      },
      ...completeDesignPlaceholders("courtroom", [
        byOthersRow(
          "courtroom",
          "recording-transcription",
          "Recording, transcription, evidence management and remote hearing platform",
          "Legal/court platform by others",
          "Replace with the approved recording, transcription, evidence and remote attendance systems.",
        ),
        byOthersRow(
          "courtroom",
          "assistive-listening",
          "Assistive listening, hearing loop and accessibility audio",
          "Accessibility equipment by others",
          "Confirm hearing loop, assisted listening, accessibility and public sector compliance requirements.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Governance", description: "Evidence sources may need restricted routing and formal operator control." },
      { label: "Recording", description: "Recording and transcription are usually separate systems but need defined AV handoff." },
      { label: "Accessibility", description: "Assistive listening and accessibility requirements should be captured before design sign-off." },
    ],
    assumptions: ["Controlled evidence routing", "Multiple formal display positions", "Recording platform by others"],
    validationItems: ["Evidence source count", "Display count", "Recording handoff", "Accessibility requirements", "Operator control model"],
    upgradePaths: ["Use NetworkHD 500 where rooms need flexible distributed routing", "Add multiview for clerk/operator monitoring", "Add more cameras for remote hearing workflows"],
  },
  {
    id: "government-emergency-briefing-room-networkhd500",
    name: "Emergency Briefing Room - NetworkHD 500",
    vertical: "Government",
    application: "Emergency planning or incident briefing room with dashboards, map sources, local laptops, VC source and multiple displays.",
    scale: "Briefing / incident response room",
    summary: "Public sector briefing room template for routing dashboards and local sources to multiple displays during incidents or planning meetings.",
    customerNarrative:
      "The room can move quickly between normal briefing, incident response and collaboration modes, routing maps, dashboards, VC and presentation sources to the right screens.",
    architecture:
      "NetworkHD 500 provides high-quality routed AV between sources and displays. Presets support Briefing, Incident, Map Review, VC and All Screens modes. Audio, control and network security are validated separately.",
    bom: [
      {
        id: "briefing-ctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing and preset control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Emergency rooms need reliable presets rather than ad-hoc source selection.",
        notes: "Confirm operator roles, security policy and preset list.",
      },
      {
        id: "briefing-500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Dashboard / map / VC source endpoint",
        qty: 5,
        type: "Required",
        status: "included",
        evidence: "Assumes maps, dashboards, local PC, laptop input and VC/meeting source.",
        notes: "Adjust to confirmed source count and security policy.",
      },
      {
        id: "briefing-500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display endpoint",
        qty: 5,
        type: "Required",
        status: "included",
        evidence: "Assumes main displays plus side/confidence displays around the room.",
        notes: "Adjust to display count and physical layout.",
      },
      {
        id: "briefing-mv",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Incident source overview display",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Incident rooms often need maps, dashboards and VC visible together.",
        notes: "Confirm layout, source count and display resolution.",
      },
      {
        id: "briefing-cam",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Briefing / VC camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Remote participants may need a controllable room camera.",
        notes: "Confirm Teams/Zoom/codec/capture workflow.",
      },
      ...completeDesignPlaceholders("emergency-briefing", [
        byOthersRow(
          "emergency-briefing",
          "secure-sources",
          "Secure PCs, dashboards, map systems and collaboration platform",
          "Secure customer systems by others",
          "Replace with the approved emergency planning, GIS, dashboard and collaboration systems.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Presets", description: "Agree modes such as Briefing, Incident, Map Review, VC and All Displays." },
      { label: "Security", description: "Some sources may be sensitive and must not route to every display." },
      { label: "Resilience", description: "Emergency rooms may need UPS, backup sources and clear failure behaviour." },
    ],
    assumptions: ["Five sources", "Five display endpoints", "Preset-based operation", "Secure systems by others"],
    validationItems: ["Source sensitivity", "Display layout", "Control permissions", "Network security", "VC/camera workflow"],
    upgradePaths: ["Move to NetworkHD 600 for zero-latency critical operation", "Add more NHD-0401-MV processors for monitoring", "Integrate third-party secure control where required"],
  },
  {
    id: "healthcare-telemedicine-consult-room-apollo",
    name: "Telemedicine Consultation Room - Apollo UC",
    vertical: "Healthcare",
    application: "Clinical consultation room with video call, local patient display, laptop/PC input, room camera/audio and simple user operation.",
    scale: "Consultation room",
    summary: "Healthcare template for simple telemedicine rooms where usability, privacy and IT policy matter more than complex routing.",
    customerNarrative:
      "The room allows clinicians to run a reliable video consultation using room camera/audio and a local display while keeping the operation simple and supportable.",
    architecture:
      "Apollo provides the local UC and presentation path. The clinical PC, laptop or codec connects according to the hospital IT policy. Privacy, platform compliance and audio capture are validated before issue.",
    bom: [
      {
        id: "telemed-apollo",
        sku: "APO-VX20-UC-V2",
        description: "Apollo video bar and switcher",
        role: "Telemedicine UC and presentation core",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Consultation rooms need simple camera, microphone, speaker and display operation.",
        notes: "Confirm approved video platform, mounting position and privacy policy.",
      },
      {
        id: "telemed-mic",
        sku: "APO-COM-MIC",
        description: "Apollo expansion microphone",
        role: "Optional table microphone",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Some consultation rooms need better table pickup depending on furniture and acoustic conditions.",
        notes: "Confirm room size, clinician/patient seating and table layout.",
      },
      {
        id: "telemed-idb",
        sku: "IDB-300",
        description: "Dual channel in-desk cable box",
        role: "Clinical desk cable access",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Clinicians may need a tidy laptop or clinical PC connection point.",
        notes: "Confirm furniture, infection control policy and cable management.",
      },
      ...completeDesignPlaceholders("telemedicine", [
        byOthersRow(
          "telemedicine",
          "clinical-pc-platform",
          "Clinical PC, telemedicine platform, EHR access and approved peripherals",
          "Healthcare IT equipment by others",
          "Replace with the hospital-approved clinical PC, EHR, telemedicine platform and security peripherals.",
        ),
        byOthersRow(
          "telemedicine",
          "infection-control",
          "Clinical mounting, wipeable accessories and infection-control hardware",
          "Healthcare installation accessories by others",
          "Confirm infection-control requirements for mounts, cabling, table boxes, microphones and user touch points.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Privacy", description: "Confirm visual privacy, audio privacy and camera field of view before positioning equipment." },
      { label: "Healthcare IT", description: "The platform and clinical PC are often customer-controlled and must be validated." },
      { label: "Usability", description: "Clinicians need a simple room workflow; avoid complex source selection." },
    ],
    assumptions: ["One clinical display", "One video consultation platform", "Local UC only", "Clinical PC by others"],
    validationItems: ["Approved platform", "Privacy policy", "Mounting and infection-control requirements (site survey checklist)", "Audio pickup", "Clinical PC location"],
    upgradePaths: ["Add PTZ camera for larger consultation/training rooms", "Move to NetworkHD 500 where rooms require routed observation/review displays", "Add separate USB extension where the host PC is remote"],
  },
  {
    id: "healthcare-theatre-observation-networkhd500",
    name: "Operating Theatre Observation and Training - NetworkHD 500",
    vertical: "Healthcare",
    application: "Clinical theatre or procedure room with camera/source feeds routed to observation, teaching, review or recording spaces.",
    scale: "Procedure room plus observation / training",
    summary: "Healthcare observation template for routing clinical video sources to training and review displays with clear medical-system handoff.",
    customerNarrative:
      "The system routes approved camera and procedure feeds to observation and training displays, supporting education and review without confusing the clinical equipment scope.",
    architecture:
      "NetworkHD 500 routes non-life-critical AV feeds from approved sources to observation and teaching displays. Camera, recorder, medical isolation and clinical platform interfaces are validated with the clinical engineering team.",
    bom: [
      {
        id: "theatre-ctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Observation routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Observation and training displays need repeatable routing presets.",
        notes: "Confirm who is allowed to route clinical feeds and where content may be shown.",
      },
      {
        id: "theatre-500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Clinical source endpoint",
        qty: 4,
        type: "Validate",
        status: "validate",
        evidence: "Assumes room camera, clinical camera output, procedure PC and capture/recorder feed.",
        notes: "Validate source type, isolation, compliance and whether each feed is permitted into AV distribution.",
      },
      {
        id: "theatre-500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Observation / teaching display endpoint",
        qty: 5,
        type: "Required",
        status: "included",
        evidence: "Assumes observation display, teaching display, review display and support preview outputs.",
        notes: "Adjust to confirmed observation and teaching spaces.",
      },
      {
        id: "theatre-mv",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Observation multiview display",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Training observers may need procedure, camera and data feeds visible together.",
        notes: "Confirm source windows, recording handoff and display resolution.",
      },
      {
        id: "theatre-cam",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Optional training camera",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Training rooms may need controlled camera views if approved by the clinical team. Uses the HDMI PTZ camera (not the NDI variant) since it feeds NetworkHD 500 TX encoders directly - the NDI version would require an NHD-128-NDI-TRX bridge, which is not included in this design.",
        notes: "Validate network policy, privacy, infection-control mounting and clinical approval.",
      },
      ...completeDesignPlaceholders("theatre-observation", [
        byOthersRow(
          "theatre-observation",
          "medical-video-systems",
          "Medical camera systems, surgical displays, recorders and clinical imaging outputs",
          "Medical AV equipment by others",
          "Replace with the approved medical-grade systems and confirm all signal handoffs with clinical engineering.",
        ),
        byOthersRow(
          "theatre-observation",
          "clinical-compliance",
          "Medical isolation, infection control, privacy and compliance accessories",
          "Clinical compliance scope by others",
          "Validate isolation, infection control, privacy, data handling and cleaning requirements before customer issue.",
        ),
      ]),
    ],
    designNotes: [
      { label: "Clinical boundary", description: "Clearly separate WyreStorm AV routing from medical-grade equipment ownership." },
      { label: "Privacy", description: "Observation routing must respect patient privacy and approved viewing locations." },
      { label: "Source validation", description: "Every clinical source needs format, compliance and permission validation before inclusion." },
    ],
    assumptions: ["Four source feeds", "Five display endpoints", "Observation/training use case", "Medical equipment by others"],
    validationItems: ["Clinical approval", "Source signal format", "Privacy and data handling", "Observation display count", "Medical isolation requirements"],
    upgradePaths: ["Move to NetworkHD 600 for zero-latency high-performance observation", "Add more NHD-0401-MV outputs for multiple teaching rooms", "Add dedicated recording/streaming equipment by approved clinical vendor"],
  },
];
