import type { RoomDeploymentDesign } from "./roomTemplateDeployment";

export const extraRoomDesigns: RoomDeploymentDesign[] = [
  {
    id: "corporate-reception-townhall-networkhd100",
    name: "Reception and Town Hall — Six Local Display Zones",
    vertical: "Corporate",
    space: "A 20m × 15m all-hands area adjoining a reception, with all six display routes within 35m of one rack.",
    construction: "Assume masonry perimeter walls, a serviceable ceiling and secure rack space; verify structural suspension points, daylight control, ventilation and room acoustics.",
    occupancy: "60–100 staff plus reception visitors",
    activity: "Staff show corporate information during normal hours and route the approved event programme to selected screens for an all-hands meeting.",
    transport: "matrix8",
    sources: [["Corporate information player HDMI",1,"rack"],["Event programme HDMI",1,"rack"],["Guest presentation HDMI",1,"presentation point"]],
    outputs: [["All-hands display",4,"event area"],["Reception display",2,"front desk/waiting"]],
    speakers: 8,
    microphones: 2,
    rationale: "Three sources and six local zones fit a fixed matrix. A separate campus-wide estate would justify revisiting network distribution.",
    alternative: "If displays need only repeated scheduled signage, use local managed players or splitters. Reconsider AV over IP only for long distributed routes, substantial expansion or campus sharing.",
    constraints: ["Include event camera/mixer if live production is required; segregate reception content from private meetings."],
    signage: true,
    accessibility: true,
    inputExtensions: 1,
    audio: {"approach":"distributed","experience":"Staff hear presenters clearly in the event area while reception retains its own background feed and level. Both zones use 100V speakers suited to speech and modest programme.","zones":[{"name":"All-hands speech","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":6,"topology":"100V","tapWatts":12,"amplifierWatts":120},{"name":"Reception background","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":2,"topology":"100V","tapWatts":6,"amplifierWatts":30}],"microphones":"Event presenter wireless microphone position","processing":"Provide source selection, gain structure, EQ, limiting and independently controlled output zones; apply delay where coverage overlaps. No AEC or conferencing function is inferred from an amplifier or video decoder.","connectivity":"Selected programme audio is extracted at the nominated source/receiver and mixed with the scheduled microphones, then sent by balanced line to each amplifier. Mute display loudspeakers to prevent duplicate delayed sound.","dante":false,"aec":false,"programmeFeeds":2,"routing":"Two feeds support independent event programme in the all-hands area and reception background content, with separate source, volume and mute controls. An event preset may link the zones only when authorised.","acousticTreatment":{"reason":"Clear teaching, briefing or recorded speech depends on a controlled acoustic environment; confirm whether the existing finishes provide enough absorption for the stated use.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
  {
    id: "corporate-training-suite-matrix-uc",
    name: "Training Suite — Local Presentation, UC and Capture",
    vertical: "Corporate",
    space: "A 12m × 9m training room with twenty-four desks and a front instructor position.",
    construction: "Assume reinforced stud or masonry display walls, an accessible suspended ceiling, carpet and controlled daylight; provide cable containment and acoustic absorption.",
    occupancy: "24 trainees and 1 instructor",
    activity: "The instructor combines PC, laptop and document-camera teaching with remote attendance; two front screens and a confidence monitor support delivery.",
    transport: "matrix4",
    sources: [["Instructor PC HDMI",1,"rack"],["Guest laptop HDMI",1,"instructor desk"],["Document camera HDMI",1,"instructor desk"],["Conferencing compute HDMI",1,"rack"]],
    outputs: [["75–86-inch teaching display",2,"front wall"],["Confidence monitor",1,"instructor desk"]],
    speakers: 6,
    microphones: 2,
    rationale: "Four sources and three displays fit a local 4×4 matrix; capture and conferencing are separately scoped host functions.",
    alternative: "If only one shared picture is needed, a switcher and splitter can replace the matrix. Move to a larger fixed matrix before proposing AV over IP for extra local I/O.",
    constraints: ["Provide HDMI content ingest, lecture camera and consent/retention controls; confirm USB switching and AEC routing."],
    uc: "room",
    recording: true,
    accessibility: true,
    inputExtensions: 2,
    audio: {"approach":"distributed","experience":"Distributed ceiling speakers carry remote participants and presentation audio evenly across the table or seating area. AEC microphones provide clear two-way calls; full-range movie sound is unnecessary.","zones":[{"name":"Meeting room ceiling","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":6,"topology":"100V","tapWatts":6,"amplifierWatts":60}],"microphones":"Table/ceiling conferencing pickup position with compatible DSP input","processing":"AEC on each conferencing microphone input, automixing, gain levelling, EQ and limiting; size channels for every pickup position. Far-end return feeds the room loudspeakers and AEC reference; near-end AEC microphone mix feeds USB transmit. Keep far-end audio out of the return send (mix-minus). Local voice lift, where needed, has separately commissioned gain and delay.","connectivity":"Selected programme audio and microphone inputs enter the DSP; DSP USB connects bidirectionally to the active conferencing host, and balanced outputs feed the room amplifiers. Commission double-talk, echo cancellation, lip-sync and content-audio sharing.","dante":false,"aec":true,"programmeFeeds":1,"routing":"One selected programme feed serves this room; conferencing return and microphone processing remain separately defined where provided.","acousticTreatment":{"reason":"Reflections from glazing, table surfaces and hard walls can reduce microphone clarity and make remote speech tiring. AEC controls echo in the signal path but does not shorten the room reverberation.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
  {
    id: "education-library-learning-commons-networkhd100",
    name: "Library Learning Commons — Seven Information Zones",
    vertical: "Education",
    space: "A 24m × 18m single-floor library with information, bookable group and event zones.",
    construction: "Assume reinforced stud or masonry display walls, an accessible suspended ceiling, carpet and controlled daylight; provide cable containment and acoustic absorption.",
    occupancy: "Seven display positions",
    activity: "Library staff route opening information, room status and event content to nominated screens; group-room personal content remains local and private.",
    transport: "matrix8",
    sources: [["Library CMS player HDMI",1,"communications cupboard"],["Room-status player HDMI",1,"cupboard"],["Event programme HDMI",1,"cupboard"]],
    outputs: [["Commercial information display",7,"entrance and circulation zones"]],
    speakers: 0,
    microphones: 0,
    rationale: "Three shared information feeds and seven fixed destinations fit a matrix if routes are within 35m; local CMS players are the alternative for longer routes.",
    alternative: "If displays need only repeated scheduled signage, use local managed players or splitters. Reconsider AV over IP only for long distributed routes, substantial expansion or campus sharing.",
    constraints: ["No shared microphone system is included; preserve the library quiet zones and separate group-room BYOD needs."],
    signage: true,
    audio: {"approach":"silent","experience":"Visual information is silent in this concept. Keep display audio muted; any paging, conferencing or room sound requirement needs a separately agreed audio scope.","zones":[],"microphones":"No room reinforcement microphones are included.","processing":"No audio processing is required in the base scope.","connectivity":"Video-only programme; display speakers remain muted.","dante":false,"aec":false,"programmeFeeds":0,"routing":"No programme-audio routing is included; the visual feeds remain silent."},
  },
  {
    id: "education-esports-media-lab-networkhd500",
    name: "Esports Teaching Lab — Spectator and Analysis Distribution",
    vertical: "Education",
    space: "A 15m × 10m lab with six gaming stations and six shared teaching/spectator screens.",
    construction: "Assume reinforced stud or masonry display walls, an accessible suspended ceiling, carpet and controlled daylight; provide cable containment and acoustic absorption.",
    occupancy: "12–18 learners",
    activity: "Players use direct local gaming monitors while the tutor sends approved capture outputs to shared review screens. The AV fabric supports analysis and spectators, not the competitive input-to-display loop.",
    transport: "nhd500",
    sources: [["Station spectator HDMI output or supported capture loop",6,"gaming desks"]],
    outputs: [["Shared analysis/spectator display",6,"perimeter walls"]],
    speakers: 6,
    microphones: 1,
    rationale: "Six distributed stations and six flexibly routed analysis screens justify sharing; primary low-latency/high-refresh gaming remains directly connected.",
    alternative: "Compare a fixed matrix and matched extension if all sources and destinations can be cabled back to one rack. Retain AV over IP only while distributed routing remains a requirement.",
    constraints: ["Include six local gaming monitors and compliant capture/loop interfaces; do not promise 4K120 through the spectator fabric.","Verify game/content permissions, HDCP behaviour and acceptable spectator delay."],
    additionalScope: [{"key":"gaming-monitors","description":"Direct-connected gaming monitors","qty":6,"notes":"One monitor at each gaming station; connect directly at the required refresh rate. These local playing screens are separate from the six AV-distributed spectator outputs."},{"key":"gaming-capture","description":"Supported spectator capture/loop interfaces","qty":6,"notes":"One per station: preserve the direct local gaming path and deliver a compatible HDMI feed to the NHD encoder; include scalers/adapters only where required and test delay/EDID."},{"key":"gaming-headsets","description":"Gaming headsets with station audio interfaces","qty":6,"notes":"One personal headset per gaming station; verify game/chat mixing, connector compatibility and hygiene provision."}],
    audio: {"approach":"distributed","experience":"Distributed 100V speakers carry tutor speech and selected spectator programme. Players use separate station headsets; those personal chat circuits are not mixed into the teaching speakers.","zones":[{"name":"Shared teaching audio","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":6,"topology":"100V","tapWatts":6,"amplifierWatts":60}],"microphones":"Tutor headset/lavalier microphone position","processing":"Provide source selection, gain structure, EQ, limiting and independently controlled output zones; apply delay where coverage overlaps. No AEC or conferencing function is inferred from an amplifier or video decoder.","connectivity":"Selected programme audio is extracted at the nominated source/receiver and mixed with the scheduled microphones, then sent by balanced line to each amplifier. Mute display loudspeakers to prevent duplicate delayed sound.","dante":false,"aec":false,"programmeFeeds":1,"routing":"One selected programme feed serves this room; conferencing return and microphone processing remain separately defined where provided.","acousticTreatment":{"reason":"Clear teaching, briefing or recorded speech depends on a controlled acoustic environment; confirm whether the existing finishes provide enough absorption for the stated use.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
  {
    id: "hospitality-hotel-meeting-room-apollo-hdbaset",
    name: "Hotel Meeting Room — Single-Screen BYOD",
    vertical: "Hospitality",
    space: "An 8m × 6m hotel meeting room with reconfigurable tables and a front display.",
    construction: "Assume reinforced stud or masonry display walls, an accessible suspended ceiling, carpet and controlled daylight; provide cable containment and acoustic absorption.",
    occupancy: "6–10 delegates",
    activity: "A guest connects a laptop to present or run a call through the room bar; hotel staff can reset the room without operating a video network.",
    transport: "apollo",
    sources: [["Guest laptop USB-C host",1,"front table connection"]],
    outputs: [["75-inch meeting display",1,"front wall"]],
    speakers: 0,
    microphones: 0,
    rationale: "One laptop and one display need a local bar with a tested USB-C route; adding unrelated HDBaseT switching duplicates the core function.",
    alternative: "If the room needs two independent screens or multiple cameras, redesign around a local presentation switcher and a separately selected conferencing package.",
    constraints: ["Confirm cable reach for each furniture layout and guest device support; provide an approved extension only where required."],
    uc: "byod",
    audio: {"approach":"integrated","experience":"The integrated bar provides two-way call audio and everyday presentation playback for the stated seating area; no external speaker or amplifier system is required.","zones":[],"microphones":"Integrated microphone array; confirm pickup in the actual room.","processing":"Use the bar’s integrated conferencing processing and verify microphone pickup at the furthest seat; do not cascade an external AEC processor.","connectivity":"The bar is the USB microphone and loudspeaker device for the connected host. Call return and microphone send travel over USB; use one active audio device.","dante":false,"aec":true,"programmeFeeds":0,"routing":"One USB conferencing return and the selected presentation audio use the integrated bar; no external zone matrix is required.","acousticTreatment":{"reason":"Reflections from glazing, table surfaces and hard walls can reduce microphone clarity and make remote speech tiring. AEC controls echo in the signal path but does not shorten the room reverberation.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
  {
    id: "hospitality-restaurant-bar-matrix",
    name: "Restaurant and Bar — Six-Zone Fixed Matrix",
    vertical: "Hospitality",
    space: "A 25m × 15m restaurant with a bar, dining room and six television positions.",
    construction: "Assume masonry perimeter walls, a serviceable ceiling and secure rack space; verify structural suspension points, daylight control, ventilation and room acoustics.",
    occupancy: "60–90 diners",
    activity: "Staff choose licensed entertainment or menus for each display, with low-level background audio in dining and a separately controlled bar programme.",
    transport: "matrix8",
    sources: [["Licensed receiver HDMI",2,"back-office rack"],["Menu/promotions player HDMI",1,"rack"],["Event HDMI feed",1,"rack"]],
    outputs: [["Commercial television",6,"bar and dining zones"]],
    speakers: 8,
    microphones: 0,
    rationale: "Four sources and six fixed zones fit the matrix kit; an optional NetworkHD controller/decoder package is not necessary for normal operation.",
    alternative: "If displays need only repeated scheduled signage, use local managed players or splitters. Reconsider AV over IP only for long distributed routes, substantial expansion or campus sharing.",
    constraints: ["Confirm 35m cable routes, content rights and audio spill between dining and bar."],
    signage: true,
    audio: {"approach":"distributed","experience":"Staff can feature television commentary in the bar while dining retains low-level background music; two 100V circuits provide appropriate commercial coverage.","zones":[{"name":"Bar programme","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":4,"topology":"100V","tapWatts":12,"amplifierWatts":120},{"name":"Dining background","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":4,"topology":"100V","tapWatts":6,"amplifierWatts":60}],"microphones":"No room reinforcement microphones are included.","processing":"Provide source selection, gain structure, EQ, limiting and independently controlled output zones; apply delay where coverage overlaps. No AEC or conferencing function is inferred from an amplifier or video decoder.","connectivity":"Selected programme audio is extracted at the nominated source/receiver and mixed with the scheduled microphones, then sent by balanced line to each amplifier. Mute display loudspeakers to prevent duplicate delayed sound.","dante":false,"aec":false,"programmeFeeds":4,"routing":"4 available programme feeds enter the audio matrix. Each of the 2 zones independently selects a feed, with local volume/mute and an agreed maximum level; stereo feeds are downmixed for mono 100V zones. Presets may link zones for an event and restore independent service afterwards. Video route changes must not silently change unrelated audio zones."},
  },
  {
    id: "retail-qsr-menu-boards-networkhd100",
    name: "Quick-Service Restaurant — Four Menu Feeds, Eight Screens",
    vertical: "Retail",
    space: "A 15m × 10m restaurant with four over-counter menu screens and four corresponding repeats in the queue area.",
    construction: "Assume a public commercial interior with solid mounting structure, concealed cable routes, lockable equipment storage and bright ambient light.",
    occupancy: "Single restaurant, two four-screen banks",
    activity: "The menu system supplies four distinct menu pages. Each page repeats in both screen banks; scheduled updates and pricing remain in the CMS.",
    transport: "matrix8",
    sources: [["Menu CMS player HDMI channel",4,"secure counter cabinet"]],
    outputs: [["High-brightness menu display",4,"counter menu bank"],["Queue repeat display",4,"queue bank"]],
    speakers: 0,
    microphones: 0,
    rationale: "Four feeds mirrored by routing presets onto eight outputs fit a fixed matrix. No cross-site video transport is needed for centrally managed menus.",
    alternative: "If displays need only repeated scheduled signage, use local managed players or splitters. Reconsider AV over IP only for long distributed routes, substantial expansion or campus sharing.",
    constraints: ["Explicitly pair outputs 1/5, 2/6, 3/7 and 4/8; eight different menu pages need eight content feeds.","Confirm heat/grease protection, orientation, brightness and 35m routes."],
    signage: true,
    audio: {"approach":"silent","experience":"Visual information is silent in this concept. Keep display audio muted; any paging, conferencing or room sound requirement needs a separately agreed audio scope.","zones":[],"microphones":"No room reinforcement microphones are included.","processing":"No audio processing is required in the base scope.","connectivity":"Video-only programme; display speakers remain muted.","dante":false,"aec":false,"programmeFeeds":0,"routing":"No programme-audio routing is included; the visual feeds remain silent."},
  },
  {
    id: "retail-car-showroom-customer-experience-networkhd500",
    name: "Car Showroom — Configurator and Brand Routing",
    vertical: "Retail",
    space: "A 30m × 20m showroom with eight display destinations in sales and vehicle zones.",
    construction: "Assume a public commercial interior with solid mounting structure, concealed cable routes, lockable equipment storage and bright ambient light.",
    occupancy: "Eight presentation positions",
    activity: "Sales staff route approved configurator, launch-video and branded content to the relevant customer area while other screens retain scheduled messaging.",
    transport: "matrix8",
    sources: [["Vehicle configurator PC HDMI",3,"sales desks via input extension"],["Brand content player HDMI",1,"rack"],["Launch/event programme HDMI",1,"rack"]],
    outputs: [["Commercial showroom display",8,"sales and vehicle zones"]],
    speakers: 8,
    microphones: 0,
    rationale: "Five feeds and eight fixed outputs fit one local matrix if cable routes remain within 35m; showroom branding alone does not require NetworkHD.",
    alternative: "If displays need only repeated scheduled signage, use local managed players or splitters. Reconsider AV over IP only for long distributed routes, substantial expansion or campus sharing.",
    constraints: ["Include three complete configurator input extension paths; use direct local high-detail outputs if interactive rendering needs exceed the matrix format.","Reconsider distributed routing only when the measured estate exceeds these fixed routes."],
    signage: true,
    inputExtensions: 3,
    audio: {"approach":"distributed","experience":"Separate 100V sales and vehicle-floor zones support restrained brand programme; the salesperson controls levels so nearby conversations remain comfortable.","zones":[{"name":"Sales desks","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":4,"topology":"100V","tapWatts":6,"amplifierWatts":60},{"name":"Vehicle floor","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":4,"topology":"100V","tapWatts":12,"amplifierWatts":120}],"microphones":"No room reinforcement microphones are included.","processing":"Provide source selection, gain structure, EQ, limiting and independently controlled output zones; apply delay where coverage overlaps. No AEC or conferencing function is inferred from an amplifier or video decoder.","connectivity":"Selected programme audio is extracted at the nominated source/receiver and mixed with the scheduled microphones, then sent by balanced line to each amplifier. Mute display loudspeakers to prevent duplicate delayed sound.","dante":false,"aec":false,"programmeFeeds":5,"routing":"5 available programme feeds enter the audio matrix. Each of the 2 zones independently selects a feed, with local volume/mute and an agreed maximum level; stereo feeds are downmixed for mono 100V zones. Presets may link zones for an event and restore independent service afterwards. Video route changes must not silently change unrelated audio zones."},
  },
  {
    id: "government-courtroom-hearing-room-matrix",
    name: "Courtroom — Controlled Evidence Presentation",
    vertical: "Government",
    space: "A 14m × 10m hearing room with judge/clerk positions, two advocate desks and a public gallery.",
    construction: "Assume masonry perimeter walls, a serviceable ceiling and secure rack space; verify structural suspension points, daylight control, ventilation and room acoustics.",
    occupancy: "20–35 participants",
    activity: "The clerk previews and releases approved evidence to nominated screens; remote participation, microphones and official recording have separate controlled workflows.",
    transport: "hybrid",
    sources: [["Court evidence PC HDMI",1,"secure rack"],["Advocate HDMI feed",2,"desk boxes via input extension"],["Remote witness platform HDMI",1,"secure rack"]],
    outputs: [["Judge monitor",1,"bench"],["Clerk preview monitor",1,"clerk desk"],["Participant display",2,"room sides"],["Public gallery display",1,"gallery"]],
    speakers: 8,
    microphones: 4,
    rationale: "Five local outputs use four HDMI extension paths and one native HDBaseT receiver; a local hybrid matrix provides the required bounded routing.",
    alternative: "A smaller local presentation switcher may suffice if the final input/output count falls. Add NetworkHD only for a separately specified remote source or destination.",
    constraints: ["Include two complete advocate-to-rack input extensions; one matrix HDBaseT input cannot accept two transmitters.","Engineer preview/release interlock, private-session mute and secure recording retention with the court."],
    uc: "room",
    recording: true,
    accessibility: true,
    inputExtensions: 2,
    audio: {"approach":"distributed","experience":"Distributed ceiling speakers carry remote participants and presentation audio evenly across the table or seating area. AEC microphones provide clear two-way calls; full-range movie sound is unnecessary.","zones":[{"name":"Meeting room ceiling","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":8,"topology":"100V","tapWatts":6,"amplifierWatts":60}],"microphones":"Table/ceiling conferencing pickup position with compatible DSP input","processing":"AEC on each conferencing microphone input, automixing, gain levelling, EQ and limiting; size channels for every pickup position. Far-end return feeds the room loudspeakers and AEC reference; near-end AEC microphone mix feeds USB transmit. Keep far-end audio out of the return send (mix-minus). Local voice lift, where needed, has separately commissioned gain and delay.","connectivity":"Selected programme audio and microphone inputs enter the DSP; DSP USB connects bidirectionally to the active conferencing host, and balanced outputs feed the room amplifiers. Commission double-talk, echo cancellation, lip-sync and content-audio sharing.","dante":false,"aec":true,"programmeFeeds":1,"routing":"One selected programme feed serves this room; conferencing return and microphone processing remain separately defined where provided.","acousticTreatment":{"reason":"Reflections from glazing, table surfaces and hard walls can reduce microphone clarity and make remote speech tiring. AEC controls echo in the signal path but does not shorten the room reverberation.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
  {
    id: "government-emergency-briefing-room-networkhd500",
    name: "Incident Briefing Room — Five-Feed Local Matrix",
    vertical: "Government",
    space: "A 14m × 10m briefing room with five shared displays and a central decision table.",
    construction: "Assume a secure continuously staffed room with reinforced display structure, raised-floor or overhead containment, controlled light and a ventilated equipment room.",
    occupancy: "18–24 staff",
    activity: "The chair selects incident maps, dashboards and authorised liaison feeds for each display while a separate conferencing system supports remote agencies.",
    transport: "matrix8",
    sources: [["Incident management PC HDMI",2,"secure rack"],["Map workstation HDMI",1,"rack"],["Authorised liaison feed HDMI",1,"rack"],["Conferencing compute HDMI",1,"rack"]],
    outputs: [["75-inch briefing display",4,"front and side walls"],["Chair confidence monitor",1,"table"]],
    speakers: 6,
    microphones: 2,
    rationale: "Five feeds and five local destinations fit an 8×8 matrix; an incident-response application does not inherently need a network-video fabric.",
    alternative: "If displays need only repeated scheduled signage, use local managed players or splitters. Reconsider AV over IP only for long distributed routes, substantial expansion or campus sharing.",
    constraints: ["Verify secure source boundaries, USB/camera paths and 35m output routes; specify recovery procedures."],
    uc: "room",
    resilience: true,
    audio: {"approach":"distributed","experience":"Distributed ceiling speakers carry remote participants and presentation audio evenly across the table or seating area. AEC microphones provide clear two-way calls; full-range movie sound is unnecessary.","zones":[{"name":"Meeting room ceiling","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":6,"topology":"100V","tapWatts":6,"amplifierWatts":60}],"microphones":"Table/ceiling conferencing pickup position with compatible DSP input","processing":"AEC on each conferencing microphone input, automixing, gain levelling, EQ and limiting; size channels for every pickup position. Far-end return feeds the room loudspeakers and AEC reference; near-end AEC microphone mix feeds USB transmit. Keep far-end audio out of the return send (mix-minus). Local voice lift, where needed, has separately commissioned gain and delay.","connectivity":"Selected programme audio and microphone inputs enter the DSP; DSP USB connects bidirectionally to the active conferencing host, and balanced outputs feed the room amplifiers. Commission double-talk, echo cancellation, lip-sync and content-audio sharing.","dante":false,"aec":true,"programmeFeeds":1,"routing":"One selected programme feed serves this room; conferencing return and microphone processing remain separately defined where provided.","acousticTreatment":{"reason":"Reflections from glazing, table surfaces and hard walls can reduce microphone clarity and make remote speech tiring. AEC controls echo in the signal path but does not shorten the room reverberation.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
  {
    id: "healthcare-telemedicine-consult-room-apollo",
    name: "Telemedicine Consultation — Local Video Visit",
    vertical: "Healthcare",
    space: "A 4.5m × 4m private consultation room with a desk and patient seating.",
    construction: "Assume cleanable solid partitions and sealed ceiling penetrations, service access outside the treatment zone and an approved infection-control installation method.",
    occupancy: "Clinician and 1–2 visitors",
    activity: "The clinician starts a remote consultation from an approved laptop, using the room camera and audio while sharing authorised documents on one screen.",
    transport: "apollo",
    sources: [["Approved clinical laptop USB-C host",1,"consultation desk"]],
    outputs: [["55-inch consultation display",1,"front wall"]],
    speakers: 0,
    microphones: 0,
    rationale: "One consultation endpoint needs local conferencing; the AV system is not a diagnostic camera or examination instrument.",
    alternative: "If the room needs two independent screens or multiple cameras, redesign around a local presentation switcher and a separately selected conferencing package.",
    constraints: ["Approve privacy, cleaning, patient consent and platform policy; separately scope medical peripherals and any clinical certification."],
    uc: "byod",
    audio: {"approach":"integrated","experience":"The integrated bar provides two-way call audio and everyday presentation playback for the stated seating area; no external speaker or amplifier system is required.","zones":[],"microphones":"Integrated microphone array; confirm pickup in the actual room.","processing":"Use the bar’s integrated conferencing processing and verify microphone pickup at the furthest seat; do not cascade an external AEC processor.","connectivity":"The bar is the USB microphone and loudspeaker device for the connected host. Call return and microphone send travel over USB; use one active audio device.","dante":false,"aec":true,"programmeFeeds":0,"routing":"One USB conferencing return and the selected presentation audio use the integrated bar; no external zone matrix is required.","acousticTreatment":{"reason":"Reflections from glazing, table surfaces and hard walls can reduce microphone clarity and make remote speech tiring. AEC controls echo in the signal path but does not shorten the room reverberation.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
  {
    id: "healthcare-theatre-observation-networkhd500",
    name: "Procedure Observation — Approved Training Feeds",
    vertical: "Healthcare",
    space: "A procedure room adjoining observation and seminar rooms, with protected service routes between them.",
    construction: "Assume cleanable solid partitions and sealed ceiling penetrations, service access outside the treatment zone and an approved infection-control installation method.",
    occupancy: "4 observers and 12 trainees",
    activity: "Authorised procedure-camera and workstation presentation feeds are distributed for observation and teaching; clinical control and diagnostic displays remain on their original approved systems.",
    transport: "nhd500",
    sources: [["Approved procedure camera interface HDMI",2,"isolated AV handoff"],["Authorised clinical presentation HDMI",1,"isolated handoff"],["Teaching PC HDMI",1,"seminar room"]],
    outputs: [["Observation display",2,"observation room"],["Seminar display",2,"teaching room"],["Facilitator monitor",1,"staff desk"]],
    speakers: 6,
    microphones: 2,
    rationale: "Five destinations across clinical boundaries and separate teaching spaces justify distributed routing, subject to isolation and explicit authorised video handoffs.",
    alternative: "Compare a fixed matrix and matched extension if all sources and destinations can be cabled back to one rack. Retain AV over IP only while distributed routing remains a requirement.",
    constraints: ["Include approved clinical isolation/conversion interfaces; no unapproved tap into medical devices.","Obtain privacy/consent and recording approval; shared AV pictures are not primary diagnostic outputs."],
    recording: true,
    resilience: true,
    audio: {"approach":"distributed","experience":"Teaching speech and approved procedure programme are heard in observation and seminar rooms on independently controlled 100V circuits. No clinical alarm or treatment-room communications path is replaced.","zones":[{"name":"Observation","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":2,"topology":"100V","tapWatts":6,"amplifierWatts":30},{"name":"Seminar","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":4,"topology":"100V","tapWatts":6,"amplifierWatts":60}],"microphones":"Teaching/facilitator microphone position","processing":"Provide source selection, gain structure, EQ, limiting and independently controlled output zones; apply delay where coverage overlaps. No AEC or conferencing function is inferred from an amplifier or video decoder.","connectivity":"Selected programme audio is extracted at the nominated source/receiver and mixed with the scheduled microphones, then sent by balanced line to each amplifier. Mute display loudspeakers to prevent duplicate delayed sound.","dante":false,"aec":false,"programmeFeeds":1,"routing":"Zones carry the same selected event programme unless an independent source is explicitly scheduled; each circuit retains independent level, mute, delay and speech/programme mixing. Room-combine presets must respect partition state and microphone routing.","acousticTreatment":{"reason":"Clear teaching, briefing or recorded speech depends on a controlled acoustic environment; confirm whether the existing finishes provide enough absorption for the stated use.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
];
