import type { RoomDeploymentDesign } from "./roomTemplateDeployment";

export const emergencyRoomDesigns: RoomDeploymentDesign[] = [
  {
    id: "emergency-station-briefing-hdbaset",
    name: "Station Briefing Room — Local HDBaseT",
    vertical: "Emergency Services",
    space: "An 8m × 5m station briefing room with a table, front screen and lockable cupboard.",
    construction: "Assume reinforced stud or masonry display walls, an accessible suspended ceiling, carpet and controlled daylight; provide cable containment and acoustic absorption.",
    occupancy: "6–12 staff",
    activity: "The duty team briefs from a station PC or visiting laptop on one screen, with clear speech and programme audio for shift handover.",
    transport: "hdbt",
    sources: [["Station PC HDMI",1,"briefing input point"],["Guest laptop USB-C",1,"briefing input point"]],
    outputs: [["75-inch briefing display",1,"front wall"]],
    speakers: 2,
    microphones: 0,
    rationale: "Two selectable sources and one screen need a single HDBaseT path, not control-room infrastructure.",
    alternative: "For a short table-to-screen route, compare direct HDMI/USB-C switching; use a newer matched transmitter/receiver if 4K60 or higher USB bandwidth is required.",
    constraints: ["Any central incident feed is an added source with an explicitly approved handoff, not an assumed IP connection."],
    resilience: true,
    audio: {"approach":"distributed","experience":"A modest room speaker system handles selected programme and speech playback. Size it for intelligibility and the stated audience rather than cinema output.","zones":[{"name":"Programme zone","purpose":"Front-of-room programme playback with one loudspeaker per amplifier channel.","speakers":2,"topology":"lowZ","amplifierWatts":30}],"microphones":"No room reinforcement microphones are included.","processing":"Provide source selection, gain structure, EQ, limiting and independently controlled output zones; apply delay where coverage overlaps. No AEC or conferencing function is inferred from an amplifier or video decoder.","connectivity":"Selected programme audio is extracted at the nominated source/receiver and mixed with the scheduled microphones, then sent by balanced line to each amplifier. Mute display loudspeakers to prevent duplicate delayed sound.","dante":false,"aec":false,"programmeFeeds":1,"routing":"One selected programme feed serves this room; conferencing return and microphone processing remain separately defined where provided."},
  },
  {
    id: "emergency-tactical-coordination-hybrid",
    name: "Tactical Coordination Room — Local 4×4 Matrix",
    vertical: "Emergency Services",
    space: "A 10m × 8m coordination room with a U-shaped table and two front displays.",
    construction: "Assume a secure continuously staffed room with reinforced display structure, raised-floor or overhead containment, controlled light and a ventilated equipment room.",
    occupancy: "12–20 staff",
    activity: "The chair compares incident information and maps while liaison officers share a laptop; a room conferencing platform connects authorised remote teams.",
    transport: "matrix4",
    sources: [["Incident PC HDMI",1,"secure rack"],["Mapping PC HDMI",1,"rack"],["Liaison laptop HDMI",1,"table"],["Conferencing compute HDMI",1,"rack"]],
    outputs: [["75–86-inch coordination display",2,"front wall"]],
    speakers: 6,
    microphones: 2,
    rationale: "Four local sources and two outputs fit a fixed matrix; a remote AV-over-IP source is not presumed simply because teams collaborate remotely.",
    alternative: "If only one shared picture is needed, a switcher and splitter can replace the matrix. Move to a larger fixed matrix before proposing AV over IP for extra local I/O.",
    constraints: ["Remote agencies connect through the approved conferencing platform; any separate video feed needs a security-approved interface."],
    uc: "room",
    resilience: true,
    inputExtensions: 1,
    audio: {"approach":"distributed","experience":"Distributed ceiling speakers carry remote participants and presentation audio evenly across the table or seating area. AEC microphones provide clear two-way calls; full-range movie sound is unnecessary.","zones":[{"name":"Meeting room ceiling","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":6,"topology":"100V","tapWatts":6,"amplifierWatts":60}],"microphones":"Table/ceiling conferencing pickup position with compatible DSP input","processing":"AEC on each conferencing microphone input, automixing, gain levelling, EQ and limiting; size channels for every pickup position. Far-end return feeds the room loudspeakers and AEC reference; near-end AEC microphone mix feeds USB transmit. Keep far-end audio out of the return send (mix-minus). Local voice lift, where needed, has separately commissioned gain and delay.","connectivity":"Selected programme audio and microphone inputs enter the DSP; DSP USB connects bidirectionally to the active conferencing host, and balanced outputs feed the room amplifiers. Commission double-talk, echo cancellation, lip-sync and content-audio sharing.","dante":false,"aec":true,"programmeFeeds":1,"routing":"One selected programme feed serves this room; conferencing return and microphone processing remain separately defined where provided.","acousticTreatment":{"reason":"Reflections from glazing, table surfaces and hard walls can reduce microphone clarity and make remote speech tiring. AEC controls echo in the signal path but does not shorten the room reverberation.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
  {
    id: "emergency-dispatch-control-networkhd600",
    name: "Dispatch Review Room — Three-Feed Local Routing",
    vertical: "Emergency Services",
    space: "A 10m × 7m dispatch review room with three shared wall screens and six desk positions.",
    construction: "Assume a secure continuously staffed room with reinforced display structure, raised-floor or overhead containment, controlled light and a ventilated equipment room.",
    occupancy: "6 dispatch/supervisory staff",
    activity: "Supervisors route three authorised CAD, mapping or VMS composite outputs to the shared screens; workstation operation and incident communications remain independent.",
    transport: "matrix4",
    sources: [["Authorised dispatch/CAD HDMI output",1,"secure rack"],["Mapping HDMI output",1,"rack"],["Approved VMS composite HDMI",1,"rack"]],
    outputs: [["65-inch review display",3,"front wall"]],
    speakers: 4,
    microphones: 0,
    rationale: "Three feeds and three outputs fit a 4×4 matrix. The earlier six-transceiver 10Gb design did not justify its fabric from this I/O count.",
    alternative: "If only one shared picture is needed, a switcher and splitter can replace the matrix. Move to a larger fixed matrix before proposing AV over IP for extra local I/O.",
    constraints: ["Keep dispatch/communications functions independent; define source permissions and failure recovery.","For a larger operational wall, use a separately sized source/output schedule rather than scaling by job title."],
    resilience: true,
    audio: {"approach":"distributed","experience":"Low-level shared briefing playback is distributed for intelligibility. Operator headsets, dispatch radio and critical alarm systems remain independent of the AV speakers.","zones":[{"name":"Operational briefing audio","purpose":"Even speech and background-audio coverage; full-range cinema reproduction is not assumed.","speakers":4,"topology":"100V","tapWatts":6,"amplifierWatts":60}],"microphones":"No room reinforcement microphones are included.","processing":"Provide source selection, gain structure, EQ, limiting and independently controlled output zones; apply delay where coverage overlaps. No AEC or conferencing function is inferred from an amplifier or video decoder.","connectivity":"Selected programme audio is extracted at the nominated source/receiver and mixed with the scheduled microphones, then sent by balanced line to each amplifier. Mute display loudspeakers to prevent duplicate delayed sound.","dante":false,"aec":false,"programmeFeeds":1,"routing":"One selected programme feed serves this room; conferencing return and microphone processing remain separately defined where provided.","acousticTreatment":{"reason":"Clear teaching, briefing or recorded speech depends on a controlled acoustic environment; confirm whether the existing finishes provide enough absorption for the stated use.","scope":"Survey reverberation, background/HVAC noise and early/late reflections in furnished and occupied conditions. Include appropriately rated wall panels and ceiling clouds/baffles or absorptive finishes where needed, with measured areas and safe structural fixing. Coordinate cleaning, fire performance, lighting, sprinklers and maintenance access with the venue. Set the speech/UC performance target with the acoustic specialist and verify after installation; reduce or omit new panels only where existing treatment meets that target."}},
  },
  {
    id: "emergency-shared-status-networkhd100",
    name: "Station Shared Status — Four Local Displays",
    vertical: "Emergency Services",
    space: "A station with a briefing corridor, welfare room and staffed status desk, all within 35m cable routes of a secure rack.",
    construction: "Assume masonry perimeter walls, a serviceable ceiling and secure rack space; verify structural suspension points, daylight control, ventilation and room acoustics.",
    occupancy: "Four shared display positions",
    activity: "Two approved status/briefing feeds are routed to four displays using named presets; the public-facing position receives only cleared content.",
    transport: "matrix4",
    sources: [["Approved status CMS player HDMI",1,"secure rack"],["Briefing programme HDMI",1,"secure rack"]],
    outputs: [["Commercial status display",3,"corridor and welfare zones"],["Staffed status monitor",1,"staff desk"]],
    speakers: 0,
    microphones: 0,
    rationale: "Two sources and four local destinations fit a fixed matrix. The base design uses full-screen feeds and does not promise a multiview function.",
    alternative: "If only one shared picture is needed, a switcher and splitter can replace the matrix. Move to a larger fixed matrix before proposing AV over IP for extra local I/O.",
    constraints: ["Document content zoning and permissions; a separately specified multiview processor is needed only if simultaneous windows are required."],
    signage: true,
    resilience: true,
    audio: {"approach":"silent","experience":"Visual information is silent in this concept. Keep display audio muted; any paging, conferencing or room sound requirement needs a separately agreed audio scope.","zones":[],"microphones":"No room reinforcement microphones are included.","processing":"No audio processing is required in the base scope.","connectivity":"Video-only programme; display speakers remain muted.","dante":false,"aec":false,"programmeFeeds":0,"routing":"No programme-audio routing is included; the visual feeds remain silent."},
  },
];
