import { extraRoomTemplates } from "./roomTemplatesExtra";
export type TemplateBomType = "Required" | "Optional" | "Validate";

export type TemplateBomRow = {
  id: string;
  sku: string;
  description: string;
  role: string;
  qty: number;
  type: TemplateBomType;
  status: string;
  evidence: string;
  notes: string;
};

export type RoomTemplate = {
  id: string;
  name: string;
  vertical: string;
  application: string;
  scale: string;
  summary: string;
  customerNarrative: string;
  architecture: string;
  bom: TemplateBomRow[];
  designNotes: Array<{
    label: string;
    description: string;
  }>;
  assumptions: string[];
  validationItems: string[];
  upgradePaths: string[];
};

const coreRoomTemplates: RoomTemplate[] = [
  {
    id: "corporate-huddle-apollo",
    name: "Corporate Huddle Room - Apollo BYOD",
    vertical: "Corporate",
    application: "Small meeting room with USB-C, HDMI, wireless presentation, camera, mic, and local display.",
    scale: "4-6 people",
    summary: "Compact meeting room boilerplate for fast deployment where the customer needs a simple join, present, and meet experience.",
    customerNarrative:
      "The room is built around a single WyreStorm Apollo collaboration core so users can walk in with a laptop, connect over USB-C/HDMI or wireless presentation, and use the room camera, speakers, and microphone without a complex control system.",
    architecture:
      "Local presentation and UC appliance at the display, with table cable access, optional wireless dongles, and display audio handled by the room bar unless a separate audio system is specified.",
    bom: [
      {
        id: "apollovx20",
        sku: "APO-VX20-UC",
        description: "Apollo video bar and switcher",
        role: "Room UC and presentation core",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Huddle rooms need a compact camera, audio, switching, and wireless presentation path.",
        notes: "Confirm display input, room width, mounting height, and whether wireless conferencing is required.",
      },
      {
        id: "apovx20mnt",
        sku: "APO-VX20-MNT",
        description: "Apollo video bar wall mounting kit",
        role: "Mounting accessory",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Mounting method depends on display, wall construction, and camera height.",
        notes: "Use where wall mounting is required; otherwise confirm display or furniture mounting.",
      },
      {
        id: "apodg2",
        sku: "APO-DG2",
        description: "Apollo wireless conferencing dongle",
        role: "Optional wireless BYOD accessory",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Wireless collaboration can reduce desk cabling in small meeting spaces.",
        notes: "Confirm whether customer wants dongle-based wireless conferencing or wired-only operation.",
      },
      {
        id: "idb300",
        sku: "IDB-300",
        description: "Dual channel in-desk cable box",
        role: "Table cable access",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Small rooms often need tidy USB-C/HDMI access at the table.",
        notes: "Confirm furniture cut-out, cable tails, and local power availability.",
      },
    ],
    designNotes: [
      { label: "Display", description: "Single flat panel by others, sized for viewing distance and camera position." },
      { label: "Network", description: "Client network for wireless presentation and Teams/Zoom device policies where required." },
      { label: "Power and mounting", description: "Local display power, cable containment, and wall reinforcement by installer." },
    ],
    assumptions: ["Single display", "Local room UC", "No matrix routing", "No ceiling microphone system unless added"],
    validationItems: ["Display mounting height", "USB-C laptop charging expectations", "Wireless presentation policy", "Acoustic suitability"],
    upgradePaths: ["Add APO-COM-MIC for larger table pickup", "Add APO-DG-DOCK for managed dongle storage", "Move to a NetworkHD 500 design if room routing expands"],
  },
  {
    id: "corporate-boardroom-networkhd500",
    name: "Corporate Boardroom - NetworkHD 500",
    vertical: "Corporate",
    application: "Executive boardroom with multiple sources, multiple displays, USB routing, camera support, and high-quality 4K distribution.",
    scale: "12-20 people",
    summary: "Premium boardroom boilerplate for flexible source-to-display routing with a clear UC and presentation pathway.",
    customerNarrative:
      "The room uses NetworkHD 500 to route high-quality 4K sources to multiple displays while keeping USB, control, and future expansion in the design path.",
    architecture:
      "AV-over-IP routing over a managed AV network, with transmitters at source locations, receivers at displays, a NetworkHD controller, and separate USB/camera handling where needed.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "NetworkHD systems need governed control and configuration.",
        notes: "Confirm network isolation, control UI, and commissioning ownership.",
      },
      {
        id: "nhd500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Source endpoint",
        qty: 4,
        type: "Required",
        status: "included",
        evidence: "Four source positions are assumed for boardroom presentation and room PC inputs.",
        notes: "Adjust quantity to confirmed physical sources.",
      },
      {
        id: "nhd500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Three displays are assumed: main display, confidence display, and side/rear display.",
        notes: "Adjust quantity to confirmed display count.",
      },
      {
        id: "nhdusbtrx",
        sku: "NHD-USB-TRX",
        description: "USB over IP transceiver",
        role: "USB transport",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "USB routing is usually required where cameras or room peripherals are shared.",
        notes: "Confirm USB host location, peripheral bandwidth, and whether USB 2.0 is sufficient.",
      },
      {
        id: "cam210ptz",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Room camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Executive rooms commonly need a controllable front-of-room camera.",
        notes: "Confirm platform certification requirements and camera field of view.",
      },
    ],
    designNotes: [
      { label: "Displays", description: "Main and confidence displays by others, sized for table length and content type." },
      { label: "Audio", description: "DSP, microphones, speakers, and amplifier by others unless the design is expanded into a WyreStorm UC path." },
      { label: "Network", description: "Managed AV network with multicast handling, VLAN plan, PoE budget, and commissioning access." },
      { label: "Control", description: "Touch panel or third-party control by others, integrated to NetworkHD presets and display power." },
    ],
    assumptions: ["Managed AV network is available", "Four source endpoints", "Three display endpoints", "USB sharing may be required"],
    validationItems: ["Network readiness", "Source count", "Display count", "USB topology", "Control ownership", "Audio DSP scope"],
    upgradePaths: ["Add NHD-0401-MV for multiview monitoring", "Use NHD-500-DNT-TX where Dante/AES67 workflow is required", "Move to NetworkHD 600 for 10G lossless zero-latency routing"],
  },
  {
    id: "education-classroom-hdbaset",
    name: "Education Classroom - Front-of-Room HDBaseT",
    vertical: "Education",
    application: "Teaching room with wall plate input, USB-C/HDMI presentation, projector or display, and optional room USB.",
    scale: "Standard classroom",
    summary: "Repeatable classroom boilerplate for simple teaching spaces where a lecturer needs reliable front-of-room presentation.",
    customerNarrative:
      "The classroom gives teachers a familiar wall input point with HDMI/USB-C presentation and an HDBaseT path to the display or projector.",
    architecture:
      "In-wall presentation transmitter to a compatible receiver at the display/projector, with USB receiver choice governed by distance and whether USB transport is required.",
    bom: [
      {
        id: "sw130",
        sku: "SW-130-TX-UK",
        description: "In-wall HDMI and USB-C HDBaseT transmitter",
        role: "Teaching input point",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Classrooms need a robust lecturer connection point at the teaching wall or desk.",
        notes: "Confirm regional wall box format, cable path, and whether USB is required.",
      },
      {
        id: "rx500",
        sku: "RX-500",
        description: "Short-distance HDBaseT receiver with USB",
        role: "Receiver path for shorter USB-required runs",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "RX-500 can be used for shorter SW-130 receiver connections where USB is required.",
        notes: "If USB is not required, value-engineer to any compatible WyreStorm HDBT 2.0 receiver that fits distance and resolution.",
      },
      {
        id: "rx700",
        sku: "RX-700",
        description: "Longer-distance HDBaseT receiver with USB",
        role: "Receiver path for longer USB-required runs",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "RX-700 is the longer-distance SW-130 receiver path.",
        notes: "Use when the cable run or design requirement needs the longer SW-130 receive path.",
      },
      {
        id: "cam210",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Optional lecture camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Hybrid teaching may require a controllable camera.",
        notes: "Confirm whether lecture capture or conferencing is in scope.",
      },
    ],
    designNotes: [
      { label: "Display/projector", description: "Interactive display or projector by others, selected by room size and content legibility." },
      { label: "Audio", description: "Classroom speakers, amplifier, assistive listening, and microphones by others." },
      { label: "Control", description: "Simple display power/input control or third-party room control by others." },
      { label: "Cabling", description: "Certified category cabling and containment between wall plate and display/projector." },
    ],
    assumptions: ["Single teaching display path", "One lecturer input point", "USB may or may not be required"],
    validationItems: ["USB requirement", "Cable distance", "Display type", "Control scope", "Room audio owner"],
    upgradePaths: ["Use SW-120-TX3 with RX3-100 for HDBaseT 3.0 performance", "Add camera and USB extension for hybrid teaching", "Move to NetworkHD 100/500 for multi-room routing"],
  },
  {
    id: "education-lecture-capture-networkhd",
    name: "Education Lecture Capture - NetworkHD 100",
    vertical: "Education",
    application: "Lecture theatre with source distribution, confidence display, capture/overflow display, and multiview monitoring.",
    scale: "Lecture theatre",
    summary: "Cost-effective lecture theatre template for source distribution and monitoring using NetworkHD 100.",
    customerNarrative:
      "The theatre routes teaching sources across local displays and monitoring points while keeping source and display endpoints scalable.",
    architecture:
      "NetworkHD 100 encoders at sources, decoders at displays, a multiview decoder for monitoring, and a NetworkHD controller on a governed AV network.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "NetworkHD endpoint routing needs a controller.",
        notes: "Confirm network isolation and AV/IT ownership.",
      },
      {
        id: "nhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Source endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes lectern PC, laptop input, and document/source feed.",
        notes: "Adjust to confirmed source count.",
      },
      {
        id: "nhd120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display endpoint",
        qty: 4,
        type: "Required",
        status: "included",
        evidence: "Assumes projector/display, confidence monitor, overflow, and capture/preview display.",
        notes: "Adjust to confirmed display and capture endpoints.",
      },
      {
        id: "nhd150rx",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Monitoring multiview",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Lecture support staff often need a multiview of active sources.",
        notes: "Confirm source window count and monitoring display location.",
      },
      {
        id: "camndi",
        sku: "CAM-210-NDI-PTZ",
        description: "NDI PTZ camera",
        role: "Lecture capture camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Lecture capture may require a PTZ camera with network workflow support.",
        notes: "Confirm NDI, USB, HDMI, or capture appliance input path.",
      },
    ],
    designNotes: [
      { label: "Capture appliance", description: "Recording/streaming appliance or platform by others if not part of the WyreStorm scope." },
      { label: "Audio", description: "Lectern mic, radio mic, ceiling mics, DSP, and PA integration by others." },
      { label: "Network", description: "Managed AV VLAN, multicast handling, PoE budget, and AV/IT commissioning window." },
    ],
    assumptions: ["Three source endpoints", "Four display endpoints", "One multiview support monitor", "Managed AV network"],
    validationItems: ["Capture workflow", "Camera output format", "Source count", "Display count", "Network readiness", "Audio handoff"],
    upgradePaths: ["Move to NetworkHD 500 for 4K60 4:4:4 and stronger USB workflows", "Add more NHD-150-RX decoders for multiple monitoring positions", "Use NetworkHD 600 where lossless zero-latency routing is required"],
  },
  {
    id: "retail-signage-networkhd100",
    name: "Retail Multi-Zone Signage - NetworkHD 100",
    vertical: "Retail",
    application: "Store signage rollout with one or more media sources feeding several display zones.",
    scale: "Single store or rollout template",
    summary: "Retail boilerplate for flexible signage distribution without building a complex control-room style system.",
    customerNarrative:
      "NetworkHD 100 gives the store a scalable way to route signage content to multiple zones and add displays over time.",
    architecture:
      "Central signage sources encode onto a managed AV network, with a decoder at each display or zone and a controller for routing presets.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Store signage routing needs simple preset management.",
        notes: "Confirm whether the store or central IT team owns presets.",
      },
      {
        id: "nhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Signage source endpoint",
        qty: 2,
        type: "Required",
        status: "included",
        evidence: "Assumes two signage/media player feeds.",
        notes: "Adjust to confirmed media player count.",
      },
      {
        id: "nhd120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display zone endpoint",
        qty: 8,
        type: "Required",
        status: "included",
        evidence: "Assumes eight display zones across retail floor, window, and service areas.",
        notes: "Adjust to zone/display count.",
      },
      {
        id: "nhdrack4",
        sku: "NHD-000-RACK4",
        description: "NetworkHD rack mount",
        role: "Rack mounting",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Rack mounting keeps endpoint hardware organized in rollout installs.",
        notes: "Confirm rack space and whether endpoints are central or display-mounted.",
      },
    ],
    designNotes: [
      { label: "Displays", description: "Commercial displays and mounts by others, chosen for brightness, orientation, and runtime." },
      { label: "Media players", description: "Signage players or CMS endpoints by others unless WyreStorm source hardware is specified." },
      { label: "Network", description: "Store network must support AV-over-IP bandwidth, multicast behaviour, VLAN policy, and PoE budget." },
    ],
    assumptions: ["Two signage sources", "Eight display zones", "Preset routing", "No USB transport"],
    validationItems: ["Exact display count", "Source/player count", "Network readiness", "Mounting and local power", "Content management ownership"],
    upgradePaths: ["Use NHD-150-RX for multiview signage monitoring", "Move to NetworkHD 500 for higher-quality 4K60 paths", "Add dedicated wall processors for fixed LCD walls"],
  },
  {
    id: "retail-lcd-wall-processor",
    name: "Retail Feature Wall - Dedicated LCD Processor",
    vertical: "Retail",
    application: "Entrance or promotional LCD video wall with fixed or semi-flexible layouts.",
    scale: "2x2 to 1x4 wall",
    summary: "Dedicated video wall template where a processor is a cleaner fit than a full AV-over-IP design.",
    customerNarrative:
      "The feature wall uses a dedicated WyreStorm processor to create a simple high-impact display canvas without unnecessary network complexity.",
    architecture:
      "One or more source feeds enter a dedicated wall processor, with outputs feeding each display in the wall. AV-over-IP is only added if routing flexibility is required.",
    bom: [
      {
        id: "sw0204",
        sku: "SW-0204-VW",
        description: "Preset-layout video wall processor",
        role: "Basic wall processor",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Basic 1x4 or 2x2 LCD walls can be served by a dedicated preset-layout processor.",
        notes: "Use when layouts are simple and fixed.",
      },
      {
        id: "sw0206",
        sku: "SW-0206-VW",
        description: "Flexible 6-output video wall processor",
        role: "Alternative wall processor",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "More flexible fixed walls may need the larger dedicated processor path.",
        notes: "Use instead of SW-0204-VW when output count or layout flexibility requires it.",
      },
      {
        id: "exp0401",
        sku: "EXP-SW-0401-8K",
        description: "4x1 HDMI switcher",
        role: "Optional local source switching",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Some retail walls need simple local source selection ahead of the wall processor.",
        notes: "Confirm source count and resolution requirements.",
      },
    ],
    designNotes: [
      { label: "Displays", description: "Matched-bezel displays, wall mounts, power, and display calibration by others." },
      { label: "Source", description: "Media player, signage player, or local source by others unless included separately." },
      { label: "Control", description: "Web GUI/RS-232 handoff to local control or store operations as required." },
    ],
    assumptions: ["Fixed LCD wall", "Simple source behaviour", "No per-display independent routing unless upgraded"],
    validationItems: ["Wall geometry", "Source count", "Canvas vs mirrored content", "Control handoff", "Display bezel compensation"],
    upgradePaths: ["Use SW-0206-VW for more outputs or custom layouts", "Use NetworkHD for per-display routing or distributed content", "Add a local switcher where multiple sources are needed"],
  },
  {
    id: "hospitality-sports-bar-networkhd",
    name: "Hospitality Sports Bar - Multi-Zone AV",
    vertical: "Hospitality",
    application: "Bar or hospitality venue with multiple TV zones, source routing, and optional multiview displays.",
    scale: "8-16 displays",
    summary: "Sports bar boilerplate for flexible source routing to many displays without fixed matrix I/O limits.",
    customerNarrative:
      "NetworkHD lets staff route sports, signage, and venue content to different display zones while keeping the system expandable.",
    architecture:
      "AV-over-IP endpoints at sources and displays, controller presets for common events, and optional multiview decoder for featured screens.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Multi-zone hospitality routing needs preset control.",
        notes: "Confirm operator interface and who changes presets.",
      },
      {
        id: "nhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Source endpoint",
        qty: 6,
        type: "Required",
        status: "included",
        evidence: "Assumes six venue sources such as satellite boxes, signage, media, or house feed.",
        notes: "Adjust to source count and rights-management workflow.",
      },
      {
        id: "nhd120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display endpoint",
        qty: 12,
        type: "Required",
        status: "included",
        evidence: "Assumes twelve displays across bar, booth, and feature areas.",
        notes: "Adjust to confirmed display count and zone behaviour.",
      },
      {
        id: "nhd150",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Feature multiview display",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Sports bars often want a feature screen showing multiple games.",
        notes: "Confirm source windows, display location, and desired layout.",
      },
    ],
    designNotes: [
      { label: "Displays", description: "Venue TVs, mounts, local power, and IR/control needs by others." },
      { label: "Audio", description: "Venue audio zoning, DSP, amplifiers, and speakers by others; confirm audio follows video or fixed zones." },
      { label: "Network", description: "Managed AV network with PoE and suitable multicast configuration." },
    ],
    assumptions: ["Six sources", "Twelve displays", "Preset routing", "Audio zoning by others"],
    validationItems: ["Display count", "Source rights and boxes", "Audio-follow-video behaviour", "Network readiness", "Staff control method"],
    upgradePaths: ["Move to NetworkHD 500 for premium 4K60 venue paths", "Add extra NHD-150-RX for multiple feature screens", "Use seamless matrix where fixed I/O is preferred"],
  },
  {
    id: "hospitality-ballroom-hybrid",
    name: "Hospitality Ballroom - Divisible Room",
    vertical: "Hospitality",
    application: "Hotel ballroom or event space with divisible zones, lectern inputs, display routing, USB, and mixed event modes.",
    scale: "Divisible event room",
    summary: "Event-space boilerplate where a hybrid matrix and HDBaseT approach can be simpler than full AV-over-IP.",
    customerNarrative:
      "The ballroom supports different room divides and event layouts while keeping source switching, local inputs, and display routing under a single structured design.",
    architecture:
      "Hybrid matrix core with local HDBaseT transmitter/receiver paths, scalable displays, USB where required, and control presets for common room modes.",
    bom: [
      {
        id: "mx1007",
        sku: "MX-1007-HYB",
        description: "10x7 hybrid seamless matrix",
        role: "Room routing and processing core",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Divisible spaces often benefit from a hybrid matrix core with mixed input/output paths.",
        notes: "Confirm exact I/O, divide modes, audio DSP role, and control integration.",
      },
      {
        id: "sw120",
        sku: "SW-120-TX3",
        description: "HDBaseT 3.0 transmitter",
        role: "Remote event input",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Event rooms usually need remote presenter inputs at lectern or wall positions.",
        notes: "Confirm input locations and whether wall-plate version is required.",
      },
      {
        id: "rx3100",
        sku: "RX3-100",
        description: "HDBaseT 3.0 receiver",
        role: "Remote receive path",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "SW-120-TX3 paths require a compatible receive side unless terminating into a compatible matrix path.",
        notes: "Confirm whether the receive path is RX3-100 or a matrix input/output path.",
      },
      {
        id: "cam210",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Event camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Hybrid events may need a camera feed for streaming or overflow.",
        notes: "Confirm camera control and platform requirements.",
      },
    ],
    designNotes: [
      { label: "Displays/projectors", description: "Projectors, displays, screens, lifts, and mounts by others." },
      { label: "Audio", description: "Ballroom microphones, DSP, amplifiers, and speaker zoning by others." },
      { label: "Control", description: "Room combine/divide presets, panel UI, and event support workflow by control contractor." },
    ],
    assumptions: ["Divisible room", "Multiple presenter positions", "Fixed I/O routing preferred over full AV-over-IP"],
    validationItems: ["Room divide modes", "Exact source/display I/O", "Audio zoning", "Control presets", "USB/camera requirements"],
    upgradePaths: ["Use NetworkHD 500 for more flexible distributed routing", "Add more SW-120-TX3/RX3-100 paths for remote inputs", "Add NHD-0401-MV where event preview monitoring is required"],
  },
  {
    id: "healthcare-simulation-lab",
    name: "Healthcare Simulation Lab - Capture and Review",
    vertical: "Healthcare",
    application: "Clinical simulation room with cameras, source capture, local review, and observation display routing.",
    scale: "Simulation room plus observation",
    summary: "Healthcare training template for routing cameras and room sources to observation, recording, and review displays.",
    customerNarrative:
      "The lab captures clinical training activity and routes it to observation and review spaces while preserving a clear technical handoff to recording and audio systems.",
    architecture:
      "NetworkHD 500 endpoints for high-quality source/display routing, PTZ camera path, optional multiview monitoring, and governed USB/network handoff.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Simulation workflows need repeatable routing presets.",
        notes: "Confirm AV/IT ownership and network isolation.",
      },
      {
        id: "nhd500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Source/camera endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes camera/source feeds from simulation room to observation/review.",
        notes: "Adjust to camera and source count.",
      },
      {
        id: "nhd500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Observation/review display endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes observation display, review display, and room confidence display.",
        notes: "Adjust to confirmed display count.",
      },
      {
        id: "nhd0401",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Observation multiview",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Observers may need a composite view of multiple feeds.",
        notes: "Confirm source window count and observation workflow.",
      },
      {
        id: "camndi",
        sku: "CAM-210-NDI-PTZ",
        description: "NDI PTZ camera",
        role: "Training camera",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Simulation labs often need multiple controllable camera views.",
        notes: "Confirm NDI/HDMI/USB capture path and medical privacy requirements.",
      },
    ],
    designNotes: [
      { label: "Recording platform", description: "Simulation recording, annotation, and debrief platform by others." },
      { label: "Audio", description: "Room microphones, observation audio, DSP, and privacy controls by others." },
      { label: "Network/security", description: "Clinical network approval, VLANs, user access, and data handling by customer IT." },
    ],
    assumptions: ["Three routed feeds", "Three display endpoints", "Observation room included", "Recording system by others"],
    validationItems: ["Camera count", "Recording platform inputs", "Privacy requirements", "Audio capture", "Network/security approval"],
    upgradePaths: ["Move to NetworkHD 600 for lossless zero-latency critical review", "Add NHD-USB-TRX for USB peripheral sharing", "Add more NHD-0401-MV outputs for multi-room observation"],
  },
  {
    id: "government-control-room-networkhd600",
    name: "Government Control Room - NetworkHD 600",
    vertical: "Government",
    application: "Command and control space with low-latency source routing, wall displays, operator positions, and monitoring.",
    scale: "Control room",
    summary: "High-performance control-room boilerplate for demanding routing and display-wall environments.",
    customerNarrative:
      "NetworkHD 600 provides a high-performance AVoIP backbone for mission-style rooms where latency, quality, and flexible routing matter.",
    architecture:
      "10G AV-over-IP transceivers at sources and displays, governed network switching, controller, and optional fibre transceivers where distances or topology require them.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Control rooms need governed routing and preset control.",
        notes: "Confirm security, network isolation, and control UI requirements.",
      },
      {
        id: "nhd600trx",
        sku: "NHD-600-TRX",
        description: "NetworkHD 600 10G transceiver",
        role: "10G source/display endpoint",
        qty: 10,
        type: "Required",
        status: "included",
        evidence: "Assumes mixed source and display endpoints for a control room backbone.",
        notes: "Split final quantity by source/display positions after layout confirmation.",
      },
      {
        id: "nhd600trxf",
        sku: "NHD-600-TRXF",
        description: "NetworkHD 600 fibre transceiver",
        role: "Fibre endpoint option",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Fibre may be required for distance, isolation, or rack topology.",
        notes: "Confirm fibre plant, optics, and endpoint locations.",
      },
      {
        id: "nhdrack1u",
        sku: "NHD-RACK-1U",
        description: "NetworkHD rack mount",
        role: "Endpoint mounting",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Rack mounting is commonly required for centralized endpoint hardware.",
        notes: "Confirm rack layout and endpoint mounting positions.",
      },
    ],
    designNotes: [
      { label: "Video wall", description: "Display wall, mounts, power, wall controller needs, and calibration by others unless a WyreStorm wall processor is selected." },
      { label: "Network", description: "10G switching, multicast handling, VLANs, security hardening, and fibre/optics design by AV/IT team." },
      { label: "Operator audio/control", description: "Audio monitoring, KVM, operator consoles, and control UI by others or separate design scope." },
    ],
    assumptions: ["10 endpoints", "10G AV network", "Control room display wall", "Security review required"],
    validationItems: ["Endpoint count", "10G network design", "Fibre requirement", "Wall behaviour", "Control/security policy"],
    upgradePaths: ["Add dedicated SW-0206-VW where fixed wall processing is preferable", "Add additional NHD-600 endpoints by operator position", "Use NetworkHD 500 for less demanding rooms"],
  },
  {
    id: "venue-worship-overflow-networkhd500",
    name: "Venue Worship - Overflow and Stage Feeds",
    vertical: "Venue",
    application: "House of worship or performance venue with camera/source routing to overflow, confidence, lobby, and recording displays.",
    scale: "Medium venue",
    summary: "Venue boilerplate for routing stage and camera feeds around a building without locking into fixed matrix I/O.",
    customerNarrative:
      "NetworkHD 500 routes service or event feeds to overflow and support areas, with optional multiview monitoring for production staff.",
    architecture:
      "NetworkHD 500 encoders at production/source locations, decoders at displays, controller presets, and optional PTZ camera and multiview processor.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Venue routing needs simple route presets for services and events.",
        notes: "Confirm volunteer/operator control method.",
      },
      {
        id: "nhd500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Production source endpoint",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes program feed, camera feed, and presentation feed.",
        notes: "Adjust to confirmed production outputs.",
      },
      {
        id: "nhd500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display endpoint",
        qty: 5,
        type: "Required",
        status: "included",
        evidence: "Assumes lobby, overflow, nursery, confidence, and production monitor displays.",
        notes: "Adjust to display count and zones.",
      },
      {
        id: "nhd0401",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Production multiview",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Production teams often need a multiview of program, camera, and presentation feeds.",
        notes: "Confirm source count and output display.",
      },
      {
        id: "camndi",
        sku: "CAM-210-NDI-PTZ",
        description: "NDI PTZ camera",
        role: "Venue camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "PTZ camera can support overflow and recording workflows.",
        notes: "Confirm camera control and production switcher integration.",
      },
    ],
    designNotes: [
      { label: "Production system", description: "Switcher, recording/streaming platform, comms, and broadcast audio by others." },
      { label: "Displays", description: "Lobby, overflow, confidence, and support displays by others." },
      { label: "Network", description: "Managed AV network and any separation from general venue IT by others." },
    ],
    assumptions: ["Three production feeds", "Five display endpoints", "Managed AV network", "Audio handled by venue system"],
    validationItems: ["Production source outputs", "Display count", "Network readiness", "Camera control", "Audio embedding/de-embedding needs"],
    upgradePaths: ["Move to NetworkHD 600 for zero-latency high-performance routing", "Add more NHD-0401-MV monitoring positions", "Use dedicated HDMI/HDBaseT extension for simple point-to-point overflow"],
  },
  {
    id: "transport-operations-signage",
    name: "Transport Operations - Status Displays",
    vertical: "Transport",
    application: "Transport office or station back-of-house with status dashboards, service feeds, and staff information displays.",
    scale: "Operations suite",
    summary: "Transport template for routing live information displays and operational sources across staff areas.",
    customerNarrative:
      "The system routes operational dashboards and video feeds to multiple staff-facing displays, supporting quick updates and clear zone control.",
    architecture:
      "NetworkHD 100 for cost-effective AV-over-IP distribution, with a controller, source encoders, display decoders, and optional multiview display for supervisors.",
    bom: [
      {
        id: "nhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Operational display routing needs managed presets and control.",
        notes: "Confirm whether operations or IT owns route changes.",
      },
      {
        id: "nhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Operational source endpoint",
        qty: 4,
        type: "Required",
        status: "included",
        evidence: "Assumes status dashboard, CCTV/service feed, timetable feed, and staff message source.",
        notes: "Adjust to confirmed source systems.",
      },
      {
        id: "nhd120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Display endpoint",
        qty: 6,
        type: "Required",
        status: "included",
        evidence: "Assumes six staff displays across operations, break, and supervisor spaces.",
        notes: "Adjust to display count and security zones.",
      },
      {
        id: "nhd150",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Supervisor multiview",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Supervisors may need multiple status feeds on one screen.",
        notes: "Confirm feed count and layout requirements.",
      },
    ],
    designNotes: [
      { label: "Data/source systems", description: "Timetable, CCTV, dashboard, and status systems by others." },
      { label: "Displays", description: "Commercial displays and mounts by others, selected for runtime and visibility." },
      { label: "Security", description: "Network access, source permissions, and operational security policy by customer IT." },
    ],
    assumptions: ["Four operational sources", "Six displays", "No USB transport", "Managed AV network"],
    validationItems: ["Source system outputs", "Display count", "Security zones", "Network readiness", "Control ownership"],
    upgradePaths: ["Use NetworkHD 500 for higher-quality 4K60 dashboard feeds", "Add more NHD-150-RX multiview points", "Use dedicated processors for fixed wall displays"],
  },
  {
    id: "residential-media-matrix",
    name: "Residential Media Room - Local Matrix",
    vertical: "Residential",
    application: "Premium media room with several HDMI sources, main display/projector, secondary display, and local audio handoff.",
    scale: "Single media room",
    summary: "Residential-style boilerplate for a fixed-I/O media room where a simple local matrix is better than AV-over-IP.",
    customerNarrative:
      "The room uses a compact WyreStorm HDMI matrix to route local sources to the main display and secondary display path without unnecessary network complexity.",
    architecture:
      "Local HDMI matrix with optional switcher ahead of it, display/projector outputs, ARC/audio handoff as required, and control integration by others.",
    bom: [
      {
        id: "mx0404hdmi",
        sku: "MX-0404-HDMI",
        description: "4x4 HDMI matrix",
        role: "Primary local source routing",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Fixed media rooms often need several HDMI sources to feed multiple display paths without using an EXP product as the primary matrix.",
        notes: "Confirm source count, display count, audio return, and control requirements.",
      },
      {
        id: "expsw0401",
        sku: "EXP-SW-0401-8K",
        description: "4x1 HDMI switcher",
        role: "Optional local source expansion",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Useful where additional local HDMI source selection is required.",
        notes: "Confirm bandwidth and source compatibility before adding.",
      },
      {
        id: "rx70",
        sku: "RX-70-4K",
        description: "HDBaseT receiver",
        role: "Optional remote display receive path",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "A remote projector/display may need HDBaseT extension.",
        notes: "Confirm transmitter/output compatibility, distance, and cable grade.",
      },
    ],
    designNotes: [
      { label: "Sources", description: "Media players, game consoles, set-top boxes, and AVR by others." },
      { label: "Displays/audio", description: "Projector/display, AVR, speakers, and subwoofer system by others." },
      { label: "Control", description: "Residential control processor, handheld remote, or app control by others." },
    ],
    assumptions: ["Four HDMI sources", "Two display paths", "Fixed local routing", "No USB transport"],
    validationItems: ["Source bandwidth", "ARC/eARC expectations", "Projector distance", "Control integration", "HDR/HDCP requirements"],
    upgradePaths: ["Use an 8x8 seamless matrix for more sources/displays", "Move to HDBaseT or AV-over-IP where sources are distributed", "Add dedicated audio de-embedding where AVR handoff requires it"],
  },
  {
    id: "corporate-multi-camera-meeting-bridge",
    name: "Corporate Multi-Camera Meeting Room - Camera Bridge",
    vertical: "Corporate",
    application: "Medium meeting room with two PTZ cameras, room audio, wireless BYOD, and a camera bridge/mixer for improved meeting coverage.",
    scale: "10-18 people",
    summary: "Multi-camera meeting room template for customers who need better camera coverage than a single front-of-room bar can provide.",
    customerNarrative:
      "The room supports a more professional hybrid meeting experience by combining multiple camera views with a WyreStorm camera bridge workflow, allowing the room to capture presenter, audience, and table activity more effectively.",
    architecture:
      "Room presentation and conferencing are handled locally, with multiple cameras feeding a camera bridge/mixer before connection into the room UC workflow. Wireless collaboration dongles can be added where users need faster BYOD/BYOD access.",
    bom: [
      {
        id: "apo210uc",
        sku: "APO-210-UC",
        description: "Apollo video-speakerphone switcher",
        role: "Room collaboration and presentation core",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Multi-camera rooms still need a simple user-facing presentation and conferencing core.",
        notes: "Confirm whether the room uses the Apollo audio path, separate DSP, or a platform-specific compute device.",
      },
      {
        id: "cam420front",
        sku: "CAM-420-PTZ",
        description: "PTZ camera",
        role: "Front-of-room camera",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "A front camera provides the primary presenter or table-facing shot.",
        notes: "Confirm camera location, field of view, and control method.",
      },
      {
        id: "cam420rear",
        sku: "CAM-420-PTZ",
        description: "PTZ camera",
        role: "Rear or audience camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "A second camera improves coverage for longer meeting rooms, training rooms, and panel-style discussions.",
        notes: "Confirm whether the second camera is needed for audience, whiteboard, or presenter framing.",
      },
      {
        id: "cam0402brg",
        sku: "CAM-0402-BRG",
        description: "Camera bridge and mixer",
        role: "Camera aggregation and USB conferencing bridge",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "A bridge/mixer is required where multiple cameras need to be presented cleanly to the conferencing host.",
        notes: "Validate camera inputs, USB host location, platform compatibility, and whether an NDI bridge variant is required.",
      },
      {
        id: "apocommic",
        sku: "APO-COM-MIC",
        description: "Apollo companion microphone",
        role: "Extended table microphone pickup",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Medium rooms often need improved far-end audio pickup beyond a front-of-room device.",
        notes: "Confirm table size, seating layout, and acoustic conditions.",
      },
      {
        id: "apodg2",
        sku: "APO-DG2",
        description: "Apollo wireless conferencing dongle",
        role: "Wireless BYOD endpoint",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Wireless BYOD dongles simplify user access in shared meeting rooms.",
        notes: "Confirm whether the customer wants managed dongles, wired-only USB-C, or app-based workflows.",
      },
    ],
    designNotes: [
      { label: "Camera coverage", description: "Define presenter, audience, table, and whiteboard camera views before selecting final camera locations." },
      { label: "USB workflow", description: "Confirm which device is the USB host and whether the camera bridge is feeding a room PC, user laptop, or appliance." },
      { label: "Audio", description: "Confirm whether Apollo audio is sufficient or whether DSP, ceiling microphones, and loudspeakers are in scope." },
      { label: "Control", description: "Camera presets and source selection may need a touch panel or third-party control system." },
    ],
    assumptions: ["Two camera positions", "One conferencing host path", "Wireless BYOD optional", "Room audio may need separate validation"],
    validationItems: ["Camera sightlines", "USB host location", "Audio pickup", "Camera preset control", "Platform compatibility"],
    upgradePaths: ["Use CAM-0402-NDI-BRG where NDI camera workflows are required", "Add NetworkHD 500 if video routing expands beyond the room", "Add a dedicated control interface for camera preset selection"],
  },
  {
    id: "education-school-hall-hdbaset-projector",
    name: "Education School Hall - HDBaseT Wall Plate to Projector",
    vertical: "Education",
    application: "School hall, assembly space, or multipurpose room with a teacher/presenter wall plate feeding a ceiling projector or large display over HDBaseT.",
    scale: "School hall / assembly space",
    summary: "Simple, repeatable school hall design using a wall plate or teaching input point with HDBaseT transport to a projector.",
    customerNarrative:
      "The hall gives staff a reliable wall input point for laptop presentation, with the signal extended over HDBaseT to the projector or main display. This keeps the user experience familiar while removing long HDMI cable issues.",
    architecture:
      "A WyreStorm in-wall transmitter at the teaching or stage position sends HDMI/USB-C presentation over category cable to a compatible HDBaseT receiver at the projector or display. Audio and projector control are validated separately.",
    bom: [
      {
        id: "sw130txuk",
        sku: "SW-130-TX-UK",
        description: "In-wall HDMI and USB-C HDBaseT transmitter",
        role: "Teacher / presenter wall input",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "School halls need a robust, familiar wall plate style input for laptop presentation.",
        notes: "Confirm wall box format, lecturer/stage position, USB-C charging expectations, and input labelling.",
      },
      {
        id: "rx700",
        sku: "RX-700",
        description: "HDBaseT receiver",
        role: "Projector / display receiver",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "A receiver is required at the projector or display end of the HDBaseT path.",
        notes: "Validate exact receiver model against distance, resolution, USB requirement, and the selected transmitter.",
      },
      {
        id: "rx500",
        sku: "RX-500",
        description: "Shorter-distance HDBaseT receiver",
        role: "Alternative receiver path",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Shorter cable runs may be served by a smaller receiver option where the requirement allows it.",
        notes: "Use only after confirming cable distance and USB requirement.",
      },
      {
        id: "cam210ptz",
        sku: "CAM-210-PTZ",
        description: "PTZ camera",
        role: "Optional event / streaming camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "School halls increasingly need assemblies, performances, and meetings to be streamed or recorded.",
        notes: "Confirm whether camera output is USB, HDMI, NDI, or into a capture platform.",
      },
    ],
    designNotes: [
      { label: "Projector path", description: "Confirm projector input type, ceiling cable route, and whether projector audio or external PA is used." },
      { label: "Audio", description: "Hall PA, microphones, induction loop, and amplifier are normally separate scope items and must be validated." },
      { label: "Control", description: "Projector power, screen up/down, and input selection may require a wall controller or third-party control system." },
      { label: "Cabling", description: "Use certified category cable and avoid routing near mains or noisy electrical services." },
    ],
    assumptions: ["One teacher/presenter input point", "One projector/display output", "HDBaseT transport", "Audio system by others unless added"],
    validationItems: ["Cable distance", "Projector input", "USB requirement", "Audio handoff", "Control requirement", "Wall plate position"],
    upgradePaths: ["Add PTZ camera for assemblies or hybrid events", "Move to NetworkHD 100/500 where multiple displays or overflow areas are required", "Add a room control panel for projector and screen operation"],
  },
  {
    id: "education-flexible-learning-networkhd500",
    name: "Education Flexible Learning Space - NetworkHD 500",
    vertical: "Education",
    application: "Flexible classroom with teacher station, group tables, multiple displays, and routable presentation sources.",
    scale: "Active classroom / flexible learning",
    summary: "Flexible learning template using NetworkHD 500 where different source and display combinations are needed during group work, teaching, and collaboration.",
    customerNarrative:
      "The room supports different teaching modes by allowing the teacher or control system to route the main teaching source, group table sources, or shared content to any display in the room.",
    architecture:
      "NetworkHD 500 encoders are placed at the teacher station and group source positions, with decoders behind the room displays. The system is controlled using presets for teaching, group work, sharing, and review modes.",
    bom: [
      {
        id: "nhdctlpro",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Flexible learning spaces need controlled routing presets rather than ad-hoc manual switching.",
        notes: "Confirm whether presets are triggered by a teacher panel, scheduling system, or third-party control.",
      },
      {
        id: "nhd500txteacher",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Teacher station source endpoint",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "The teacher station is the primary source position.",
        notes: "Confirm source format, USB requirement, and whether the teacher station also needs camera/USB routing.",
      },
      {
        id: "nhd500txgroups",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Group table source endpoints",
        qty: 4,
        type: "Validate",
        status: "validate",
        evidence: "Flexible rooms often need local group table sources that can be shared to room displays.",
        notes: "Adjust quantity to confirmed group table count.",
      },
      {
        id: "nhd500rxdisplays",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display endpoints",
        qty: 4,
        type: "Required",
        status: "included",
        evidence: "Assumes four displays around the learning space.",
        notes: "Adjust to confirmed display count and display locations.",
      },
      {
        id: "syntouch10",
        sku: "SYN-TOUCH10",
        description: "10-inch touch panel",
        role: "Teacher routing interface",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Teachers need simple scene presets rather than access to engineering-level routing controls.",
        notes: "Confirm control platform, UI ownership, and whether third-party control is preferred.",
      },
    ],
    designNotes: [
      { label: "Teaching modes", description: "Define modes such as Teach, Group Work, Share Table, Review, and All Displays before creating presets." },
      { label: "Network", description: "Provide a managed AV network with correct multicast, VLAN, and PoE design." },
      { label: "Displays", description: "Each display needs a decoder location, power, cable containment, and a defined role in the teaching workflow." },
      { label: "Control", description: "The user interface should present teaching modes, not raw encoder/decoder names." },
    ],
    assumptions: ["One teacher source", "Four group source positions", "Four displays", "NetworkHD 500 AV-over-IP routing"],
    validationItems: ["Group table count", "Display count", "Teacher control method", "USB requirements", "Network readiness"],
    upgradePaths: ["Add NHD-0401-MV for source monitoring", "Add cameras for hybrid teaching", "Use NetworkHD 600 where the customer requires lossless zero-latency operation"],
  },
  {
    id: "education-hybrid-collaboration-nhd500-dante",
    name: "Education Hybrid Collaboration Teaching - NetworkHD 500 + Dante",
    vertical: "Education",
    application: "Hybrid teaching classroom with multiple presentation sources, camera support, display routing, and Dante-capable audio integration.",
    scale: "Hybrid classroom / seminar room",
    summary: "Hybrid teaching template using NetworkHD 500 for routed 4K AV and Dante-capable audio handoff for more integrated teaching spaces.",
    customerNarrative:
      "The room allows teachers to route high-quality content to displays while supporting hybrid teaching through camera, audio, and Dante-capable audio integration.",
    architecture:
      "NetworkHD 500 provides the routed video layer, with transmitters at teacher and source positions and receivers at displays. Dante-capable audio equipment is included for audio integration, while the camera and USB/capture path is validated against the platform workflow.",
    bom: [
      {
        id: "nhdctlpro",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Hybrid classrooms need controlled source-to-display routing and repeatable teaching presets.",
        notes: "Confirm control UI and whether IT or AV support owns routing changes.",
      },
      {
        id: "nhd500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Source endpoints",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes teacher station, wireless/presentation input, and room source/capture feed.",
        notes: "Adjust quantity to confirmed source count.",
      },
      {
        id: "nhd500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display endpoints",
        qty: 3,
        type: "Required",
        status: "included",
        evidence: "Assumes main display/projector, confidence display, and secondary teaching display.",
        notes: "Adjust quantity to confirmed display count.",
      },
      {
        id: "amp260dnt",
        sku: "AMP-260-DNT",
        description: "120W network amplifier with Dante integration",
        role: "Dante-capable room audio output",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Hybrid classrooms may need audio integration with a Dante-capable teaching audio system.",
        notes: "Confirm loudspeaker load, DSP requirement, microphone system, and Dante network ownership.",
      },
      {
        id: "cam210ndi",
        sku: "CAM-210-NDI-PTZ",
        description: "NDI PTZ camera",
        role: "Hybrid teaching camera",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Hybrid teaching needs a camera path for remote learners.",
        notes: "Confirm whether the camera path is NDI, USB, HDMI, or into a lecture capture appliance.",
      },
      {
        id: "nhd0401mv",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Optional teaching support multiview",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Support staff or lecturers may need a composite view of sources, camera, and program output.",
        notes: "Confirm monitoring display and source window requirements.",
      },
    ],
    designNotes: [
      { label: "Dante", description: "Confirm whether Dante is used for room audio distribution, DSP integration, amplifier feed, or monitoring." },
      { label: "Hybrid teaching", description: "Define whether the remote platform is Teams, Zoom, lecture capture, or a dedicated appliance." },
      { label: "USB/camera", description: "Confirm the USB host location and whether camera/control transport is required over the AV network or separate infrastructure." },
      { label: "Network", description: "Confirm AV VLAN, Dante network policy, multicast handling, QoS, and commissioning access." },
    ],
    assumptions: ["Three routed sources", "Three display endpoints", "Dante-capable audio integration", "Hybrid camera optional"],
    validationItems: ["Dante network ownership", "Audio DSP scope", "Camera output path", "Remote platform", "Network readiness", "Teacher control interface"],
    upgradePaths: ["Add more NHD-500 endpoints for additional displays or source positions", "Add NHD-0401-MV for monitoring and teaching support", "Move to NetworkHD 600 where lossless zero-latency routing is required"],
  },
  {
    id: "education-active-learning-nhd600-local-inputs",
    name: "Education Active Learning Lab - NetworkHD 600 Local Display Inputs",
    vertical: "Education",
    application: "Advanced teaching lab with 600-series transceivers behind displays, local inputs at each display, and teacher-controlled routing across the 10G AV network.",
    scale: "Advanced active learning / teaching lab",
    summary: "NetworkHD 600 teaching lab template where each display position can act as a local source and a display endpoint for flexible teacher-led sharing.",
    customerNarrative:
      "Each teaching or group display has a NetworkHD 600 transceiver behind it. The teacher can use a control system to choose whether a display shows its own local input, the teacher display, or any other 600-series source visible on the AV network.",
    architecture:
      "A 10G NetworkHD 600 system uses transceivers behind displays and at source positions. Each transceiver can support the local display endpoint role and provide a local input into the wider AV network, with the teacher selecting routed views through control presets.",
    bom: [
      {
        id: "nhdctlpro",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP routing control",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "NetworkHD systems require a control layer for endpoint routing and presets.",
        notes: "Validate controller model and control integration requirements for the 600-series design.",
      },
      {
        id: "nhd600trxdisplay",
        sku: "NHD-600-TRX",
        description: "NetworkHD 600 10G transceiver",
        role: "Display endpoint with local input capability",
        qty: 6,
        type: "Required",
        status: "included",
        evidence: "Each teaching/group display uses a 600-TRX behind the display so it can act as both a display endpoint and a local input source.",
        notes: "Adjust quantity to confirmed display/group station count.",
      },
      {
        id: "nhd600trxteacher",
        sku: "NHD-600-TRX",
        description: "NetworkHD 600 10G transceiver",
        role: "Teacher source / display endpoint",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "The teacher station needs a 600-series endpoint to share local content across the network.",
        notes: "Confirm whether the teacher display also needs its own local return display path.",
      },
      {
        id: "syntouch10",
        sku: "SYN-TOUCH10",
        description: "10-inch touch panel",
        role: "Teacher room control interface",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "The teacher needs an easy way to choose local display, teacher display, or any visible network source.",
        notes: "Confirm whether SYN-TOUCH10, third-party control, or custom UI is preferred.",
      },
      {
        id: "network10g",
        sku: "BY-OTHERS-10G-AV-SWITCH",
        description: "10G managed AV network switch",
        role: "Required 10G AV network infrastructure",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "NetworkHD 600 requires suitable 10G switching infrastructure.",
        notes: "Recommend a suitable 10G AV-capable managed switch platform and validate ports, PoE/power, multicast, VLANs, and fibre/copper requirements.",
      },
    ],
    designNotes: [
      { label: "Local input logic", description: "Each 600-TRX behind a display should be treated as both a display output point and a potential local source input." },
      { label: "Teacher control", description: "The teacher UI should provide simple modes such as Local, Teacher to All, Group Share, Compare Displays, and Restore Local." },
      { label: "10G network", description: "Validate 10G switch capacity, port count, cable type, topology, VLANs, multicast handling, and commissioning access." },
      { label: "Display locations", description: "Confirm power, mounting, cable access, ventilation, and service access behind each display." },
    ],
    assumptions: ["Six group/teaching displays", "One teacher station", "NetworkHD 600 10G AV-over-IP", "Teacher-driven control presets"],
    validationItems: ["10G switch design", "Display count", "Local input requirement at each display", "Teacher control UI", "Cable infrastructure", "Endpoint service access"],
    upgradePaths: ["Add more NHD-600-TRX endpoints for additional group displays", "Add multiview/monitoring where support staff need source preview", "Use NetworkHD 500 where 10G/lossless performance is not required"],
  },
  {
    id: "hospitality-large-sportsbar-nhd500",
    name: "Large Sports Bar - NetworkHD 500 Multi-Zone",
    vertical: "Hospitality",
    application: "Large sports bar or venue with many displays, premium 4K routing, featured multiview screens, and staff preset control.",
    scale: "16-40 displays",
    summary: "Premium sports bar template using NetworkHD 500 for flexible source-to-display routing across many TV zones.",
    customerNarrative:
      "The venue can route live sport, signage, event feeds, and promotional content to any display zone, with feature screens able to show multiview layouts for multiple games or channels.",
    architecture:
      "NetworkHD 500 encoders are installed at the source rack, with NetworkHD 500 receivers at each display zone. A NetworkHD controller provides routing presets for normal trading, match day, private hire, and event modes. NHD-0401-MV is included for feature multiview displays where several sources need to be visible on one screen.",
    bom: [
      {
        id: "sportsbar500ctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP routing and preset control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Large venues need preset-based control rather than manual source selection at every display.",
        notes: "Confirm operator UI, zone naming, presets, and whether third-party control is required.",
      },
      {
        id: "sportsbar500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Central source endpoint",
        qty: 8,
        type: "Required",
        status: "included",
        evidence: "Assumes eight venue sources such as satellite receivers, IPTV boxes, signage players, media server, and event feed.",
        notes: "Adjust to confirmed source count and source licensing model.",
      },
      {
        id: "sportsbar500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Display endpoint",
        qty: 24,
        type: "Required",
        status: "included",
        evidence: "Assumes twenty-four venue displays across bar, booth, dining, and feature areas.",
        notes: "Adjust to confirmed display count and display grouping.",
      },
      {
        id: "sportsbar0401mv",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Feature screen multiview",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Sports venues often need one or more large feature screens showing multiple games at once.",
        notes: "Confirm number of multiview screens, source window count, and preferred layouts.",
      },
      {
        id: "sportsbarsyntouch",
        sku: "SYN-TOUCH10",
        description: "10-inch touch panel",
        role: "Staff control interface",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "Venue staff need simple presets such as Match Day, All Screens, Zone Split, Private Event, and Close.",
        notes: "Confirm whether WyreStorm touch control or third-party control is preferred.",
      },
      {
        id: "sportsbarampdnt",
        sku: "AMP-260-DNT",
        description: "120W network amplifier with Dante integration",
        role: "Optional zone audio endpoint",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Premium venues may need Dante-capable audio zones linked to video presets.",
        notes: "Validate audio-follow-video, DSP, speaker zoning, and Dante network ownership.",
      },
    ],
    designNotes: [
      { label: "Display zones", description: "Define bar, booth, restaurant, private hire, feature wall, and outside terrace zones before final endpoint count." },
      { label: "Audio", description: "Decide whether audio follows video, remains fixed by zone, or is controlled separately by the venue audio DSP." },
      { label: "Network", description: "Use a managed AV network with correct multicast, VLAN, QoS, PoE/power, and commissioning access." },
      { label: "Control", description: "Staff control must use plain-language venue presets, not engineering endpoint names." },
    ],
    assumptions: ["Eight central sources", "Twenty-four displays", "Two feature multiview displays", "Managed AV network"],
    validationItems: ["Display count", "Source count", "Sports/event source licensing", "Audio zone behaviour", "Control UI", "Network readiness"],
    upgradePaths: ["Add more NHD-0401-MV processors for additional feature displays", "Use NetworkHD 600 where zero-latency/lossless routing is required", "Add NHD-500 endpoints for expansion zones"],
  },
  {
    id: "hospitality-local-pub-8x8-matrix",
    name: "Local Pub - 8x8 Matrix TV Distribution",
    vertical: "Hospitality",
    application: "Small pub or club with a fixed number of sources and TVs where a simple 8x8 matrix is more appropriate than AV-over-IP.",
    scale: "4-8 displays",
    summary: "Cost-conscious pub template using a fixed 8x8 matrix architecture for straightforward source routing.",
    customerNarrative:
      "The pub can route set-top boxes, media players, signage, and event sources to multiple TVs without the complexity of a full AV-over-IP network.",
    architecture:
      "A central seamless matrix routes HDMI sources to local or extended display paths. This is best when the number of sources and displays is known and unlikely to expand significantly.",
    bom: [
      {
        id: "pubmx0808",
        sku: "MX-0808-SCL",
        description: "8x8 seamless matrix switcher",
        role: "Central source-to-display routing core",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "An 8x8 matrix suits small venues with fixed source and display counts.",
        notes: "Confirm exact I/O count, required scaling, audio handling, and control method.",
      },
      {
        id: "pubrx70",
        sku: "RX-70",
        description: "HDBaseT receiver",
        role: "Remote TV receive path",
        qty: 4,
        type: "Validate",
        status: "validate",
        evidence: "Remote TVs may need HDBaseT receive paths where HDMI distance is impractical.",
        notes: "Use only where the selected matrix/output path and distance require a receiver.",
      },
      {
        id: "pubcontrol",
        sku: "SYN-KEY10",
        description: "Button panel controller",
        role: "Simple staff preset control",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "Small venues often need simple source presets rather than a full touch panel.",
        notes: "Confirm control compatibility and whether third-party control is already provided.",
      },
    ],
    designNotes: [
      { label: "Why matrix", description: "Use this when the design is fixed I/O and expansion is unlikely; AV-over-IP is not always the best commercial answer." },
      { label: "Display distance", description: "Validate which TVs are local HDMI and which require HDBaseT extension." },
      { label: "Audio", description: "Confirm whether TV speakers are used or whether venue audio zones need separate extraction/DSP." },
    ],
    assumptions: ["Up to eight sources", "Up to eight displays", "Fixed venue layout", "Limited expansion requirement"],
    validationItems: ["Source count", "Display count", "Cable distances", "Audio routing", "Staff control method"],
    upgradePaths: ["Move to NetworkHD 100 for more flexible expansion", "Use NetworkHD 500 for premium 4K venue routing", "Add NHD-150-RX where multiview feature screens are required"],
  },
  {
    id: "hospitality-large-casino-nhd500",
    name: "Large Casino - NetworkHD 500 Floor and VIP Routing",
    vertical: "Hospitality",
    application: "Casino floor, gaming area, sports lounge, signage, and VIP room AV routing with premium 4K distribution.",
    scale: "Large venue / casino floor",
    summary: "Casino template using NetworkHD 500 for premium routing across gaming areas, signage, sports zones, and VIP rooms.",
    customerNarrative:
      "The casino can distribute live sport, promotions, signage, event content, and private room feeds across a large estate while maintaining central control and expansion flexibility.",
    architecture:
      "NetworkHD 500 encoders sit at central source racks and event input points. Decoders feed gaming floor displays, VIP rooms, signage displays, and feature screens. Multiview processors provide monitoring or high-impact multi-source displays.",
    bom: [
      {
        id: "casinonhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Estate-wide AV-over-IP routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Large casino routing requires controlled presets, naming, and system management.",
        notes: "Confirm network architecture, control permissions, and operational user groups.",
      },
      {
        id: "casinonhd500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Central and event source endpoint",
        qty: 16,
        type: "Required",
        status: "included",
        evidence: "Assumes casino TV feeds, signage, media servers, private event sources, and promotional feeds.",
        notes: "Adjust to source rack and local event input counts.",
      },
      {
        id: "casinonhd500rx",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Gaming floor / VIP / signage display endpoint",
        qty: 48,
        type: "Required",
        status: "included",
        evidence: "Assumes distributed displays across gaming floor, sports lounge, VIP rooms, and signage areas.",
        notes: "Adjust to confirmed display count and zone behaviour.",
      },
      {
        id: "casino0401mv",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Monitoring and feature multiview",
        qty: 4,
        type: "Optional",
        status: "optional",
        evidence: "Casinos often need control-room previews and feature multi-source displays.",
        notes: "Confirm where multiview is required: operations, sports lounge, VIP, or surveillance-adjacent monitoring.",
      },
      {
        id: "casinosyntouch",
        sku: "SYN-TOUCH10",
        description: "10-inch touch panel",
        role: "Venue control interface",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Large venues may need separate control points for operations and hospitality managers.",
        notes: "Confirm user roles, locked presets, and whether third-party BMS/control is involved.",
      },
    ],
    designNotes: [
      { label: "Operational zones", description: "Separate gaming floor, sports lounge, VIP, signage, private event, and operations areas." },
      { label: "Network design", description: "Large casino networks need careful multicast, VLAN, switch stack, resilience, and commissioning planning." },
      { label: "Control permissions", description: "Not every operator should have access to every route; presets and permissions should be designed early." },
      { label: "Content rights", description: "Live sport, gaming, advertising, and event sources may have different operational and licensing constraints." },
    ],
    assumptions: ["Sixteen source endpoints", "Forty-eight display endpoints", "Multiple venue zones", "Managed AV network"],
    validationItems: ["Security/network policy", "Display estate count", "Source rights", "Control permissions", "Resilience requirements", "Rack locations"],
    upgradePaths: ["Use NetworkHD 600 for ultra-critical zero-latency paths", "Add NHD-0401-MV processors for more monitoring positions", "Split the design into phases by venue zone"],
  },
  {
    id: "hospitality-bingo-club-nhd100-led-wall",
    name: "Bingo Club - NetworkHD 100 Multiview to LED Wall",
    vertical: "Hospitality",
    application: "Bingo club with caller camera, numbers/game feed, signage, house displays, and LED wall feed using NetworkHD 100 and NHD-150-RX.",
    scale: "Club hall / leisure venue",
    summary: "Bingo venue template using NHD-120 source endpoints and NHD-150-RX multiview output to feed an LED wall processor.",
    customerNarrative:
      "The venue can combine bingo caller, game data, signage, and promotional feeds into display outputs around the room, with a multiview output feeding the LED wall processor where mixed layouts are required.",
    architecture:
      "NHD-120-TX encoders place key sources onto the NetworkHD 100 system. NHD-120-RX decoders feed local displays, while an NHD-150-RX provides a composed multiview HDMI output into the LED wall processor.",
    bom: [
      {
        id: "bingonhdctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "AV-over-IP control and routing",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "The venue needs routing and layout control across NetworkHD endpoints.",
        notes: "Confirm who controls bingo, advertising, and event presets.",
      },
      {
        id: "bingonhd120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "Bingo source endpoint",
        qty: 4,
        type: "Required",
        status: "included",
        evidence: "Assumes caller camera/feed, bingo numbers PC, signage player, and event/media source.",
        notes: "Adjust to confirmed source count and source formats.",
      },
      {
        id: "bingonhd120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "House display endpoint",
        qty: 8,
        type: "Required",
        status: "included",
        evidence: "Assumes displays around the club hall for game, signage, and promotional content.",
        notes: "Adjust to confirmed display count and zone behaviour.",
      },
      {
        id: "bingonhd150rx",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Multiview output to LED wall processor",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "The LED wall can receive a composed HDMI multiview output showing caller, numbers, signage, or sponsor content.",
        notes: "Confirm LED processor input format, resolution, refresh, scaling, and required layout behaviour.",
      },
      {
        id: "bingondi128",
        sku: "NHD-128-NDI-TRX",
        description: "NDI bridge / transceiver for NetworkHD 100 workflow",
        role: "Optional camera or network video bridge",
        qty: 1,
        type: "Optional",
        status: "optional",
        evidence: "NDI or network video sources can be bridged into the NetworkHD 100 H.265 workflow where required.",
        notes: "Confirm whether cameras or media sources are HDMI, USB, NDI, or streaming appliances.",
      },
      {
        id: "bingoledprocessor",
        sku: "BY-OTHERS-LED-PROCESSOR",
        description: "LED wall processor",
        role: "LED processing endpoint",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "The LED wall processor receives the WyreStorm output but is normally selected with the LED display system.",
        notes: "Validate input resolution, EDID, scaling, refresh rate, and content canvas behaviour.",
      },
    ],
    designNotes: [
      { label: "Multiview definition", description: "Confirm exactly which sources need to appear together on the LED wall and whether layouts are fixed or operator selectable." },
      { label: "LED wall handoff", description: "Coordinate with the LED vendor on input resolution, refresh, processor scaling, and safe area." },
      { label: "Venue displays", description: "Separate house display routing from LED wall processing; not every output needs the same content." },
      { label: "Camera workflow", description: "Caller camera can be HDMI/NDI depending on camera model and capture path." },
    ],
    assumptions: ["Four sources", "Eight house displays", "One LED wall processor input", "NHD-150-RX creates the multiview HDMI feed"],
    validationItems: ["LED processor input", "Multiview layout", "Source count", "Camera format", "Display zones", "Network readiness"],
    upgradePaths: ["Use NetworkHD 500 for higher-quality 4K60 workflows", "Add more NHD-150-RX units for additional composed displays", "Add NHD-128-NDI-TRX where NDI cameras or network video sources are required"],
  },
  {
    id: "hospitality-stadium-concourse-vip-nhd500",
    name: "Stadium - Concourse Signage and VIP Room TV Distribution",
    vertical: "Hospitality",
    application: "Stadium or arena with concourse signage, hospitality suites, VIP rooms, and central source distribution.",
    scale: "Stadium / arena estate",
    summary: "Stadium template using NetworkHD 500 for central source distribution to concourse displays and VIP room televisions.",
    customerNarrative:
      "The stadium can distribute match feeds, sponsor signage, wayfinding, IPTV, hospitality content, and event messages to concourse and VIP areas from a central controlled AV system.",
    architecture:
      "NetworkHD 500 encoders ingest central stadium feeds and signage sources. Decoders are installed behind concourse displays, suite TVs, hospitality displays, and selected operations screens. Presets allow different content by event type and zone.",
    bom: [
      {
        id: "stadiumctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Stadium AV-over-IP control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "A stadium estate requires central routing control and operational presets.",
        notes: "Confirm whether control is central AV, event operations, hospitality, or third-party integrated.",
      },
      {
        id: "stadium500tx",
        sku: "NHD-500-TX",
        description: "NetworkHD 500 encoder",
        role: "Central stadium source endpoint",
        qty: 12,
        type: "Required",
        status: "included",
        evidence: "Assumes match feed, broadcast feed, signage players, sponsor content, IPTV, and event messaging sources.",
        notes: "Adjust to source rack count and content management workflow.",
      },
      {
        id: "stadium500rxconcourse",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "Concourse signage display endpoint",
        qty: 40,
        type: "Required",
        status: "included",
        evidence: "Concourse areas require distributed display endpoints for signage, wayfinding, and event content.",
        notes: "Adjust to actual display zones and cable/rack topology.",
      },
      {
        id: "stadium500rxvip",
        sku: "NHD-500-RX",
        description: "NetworkHD 500 decoder",
        role: "VIP room / hospitality TV endpoint",
        qty: 24,
        type: "Validate",
        status: "validate",
        evidence: "VIP rooms and hospitality suites often require TV feeds that differ from concourse signage.",
        notes: "Adjust to confirmed suite count and content entitlement.",
      },
      {
        id: "stadiummv",
        sku: "NHD-0401-MV",
        description: "NetworkHD 500 multiview processor",
        role: "Event operations preview",
        qty: 2,
        type: "Optional",
        status: "optional",
        evidence: "Operations teams may need source preview or zone monitoring.",
        notes: "Confirm whether multiview is required in event control, broadcast support, or hospitality operations.",
      },
    ],
    designNotes: [
      { label: "Zone model", description: "Separate concourse, hospitality, VIP, sponsor, wayfinding, and operations zones." },
      { label: "Content control", description: "Some zones may be controlled by signage CMS, some by AV routing, and some by event operations." },
      { label: "Network topology", description: "Large venue AV-over-IP needs a structured switch topology, VLANs, multicast plan, fibre uplinks, and resilience strategy." },
      { label: "VIP behaviour", description: "VIP rooms may require local override, private sources, or restricted content lists." },
    ],
    assumptions: ["Twelve central sources", "Forty concourse displays", "Twenty-four VIP/hospitality endpoints", "Managed AV network"],
    validationItems: ["Display estate map", "Source rights", "Hospitality control model", "Network topology", "Resilience", "CMS integration"],
    upgradePaths: ["Add more NHD-0401-MV processors for operations monitoring", "Use NetworkHD 600 for zero-latency critical event paths", "Phase the deployment by concourse, hospitality, and VIP zones"],
  },
  {
    id: "government-security-command-nhd100-bridge",
    name: "Security Command Room - NetworkHD 100 Multiview and 128 Bridge",
    vertical: "Government",
    application: "Security operations room with camera/network video ingestion, operator multiview displays, and routed situational awareness screens.",
    scale: "Security operations / command room",
    summary: "Security command template using NetworkHD 100 multiview decoders and NHD-128-NDI-TRX bridge workflows for camera/network video sources.",
    customerNarrative:
      "The command room gives operators controlled multiview displays for cameras, maps, dashboards, and live feeds, while allowing selected network video sources to be brought into the NetworkHD 100 workflow.",
    architecture:
      "NetworkHD 100 encoders and bridge devices ingest HDMI and compatible NDI/network video sources. NHD-150-RX multiview decoders feed operator displays with composed views. Standard decoders feed wall displays or individual operator monitors.",
    bom: [
      {
        id: "securityctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "Command room routing control",
        qty: 1,
        type: "Required",
        status: "included",
        evidence: "Operator views and routing presets require a governed control layer.",
        notes: "Confirm security network policy, user permissions, and operational presets.",
      },
      {
        id: "security120tx",
        sku: "NHD-120-TX",
        description: "NetworkHD 100 encoder",
        role: "HDMI source endpoint",
        qty: 6,
        type: "Required",
        status: "included",
        evidence: "Assumes HDMI feeds from PCs, dashboards, incident systems, and local media sources.",
        notes: "Adjust to confirmed physical source count.",
      },
      {
        id: "security128bridge",
        sku: "NHD-128-NDI-TRX",
        description: "NetworkHD 128 NDI bridge / transceiver",
        role: "Network video / camera bridge",
        qty: 4,
        type: "Validate",
        status: "validate",
        evidence: "Network camera or NDI-style feeds may need to be bridged into the NetworkHD 100 workflow.",
        notes: "Validate exact camera/source protocol, network segmentation, security policy, and H.265 workflow requirements.",
      },
      {
        id: "security150rx",
        sku: "NHD-150-RX",
        description: "NetworkHD 100 multiview decoder",
        role: "Operator multiview display endpoint",
        qty: 6,
        type: "Required",
        status: "included",
        evidence: "Operators need multiple camera or information feeds visible at the same time.",
        notes: "Confirm window count, layout presets, and number of operator positions.",
      },
      {
        id: "security120rx",
        sku: "NHD-120-RX",
        description: "NetworkHD 100 decoder",
        role: "Single-view wall or desk display endpoint",
        qty: 8,
        type: "Optional",
        status: "optional",
        evidence: "Some wall displays may need full-screen single-source views rather than multiview.",
        notes: "Adjust to confirmed display wall and desk monitor count.",
      },
    ],
    designNotes: [
      { label: "Security network", description: "Confirm whether camera, corporate, and AV networks are separated and whether any bridging is permitted." },
      { label: "Multiview layouts", description: "Define operator layouts by incident type, shift role, and display size." },
      { label: "Source governance", description: "Some sources may be sensitive and should not be routable to every display." },
      { label: "Bridge validation", description: "Validate NHD-128-NDI-TRX use case against the exact network video format and security policy." },
    ],
    assumptions: ["Six HDMI sources", "Four bridge/network video sources", "Six operator multiview displays", "NetworkHD 100 H.265 workflow"],
    validationItems: ["Camera/source protocol", "Security network approval", "Operator layout count", "Display count", "Source permissions", "Control access"],
    upgradePaths: ["Use NetworkHD 500 where higher quality or stronger USB/audio integration is required", "Use NetworkHD 600 for zero-latency critical operation rooms", "Add more NHD-150-RX decoders for additional operator stations"],
  },
  {
    id: "government-situation-control-room-nhd600",
    name: "Situation Control Room - NetworkHD 600 Zero-Latency",
    vertical: "Government",
    application: "Critical control room or situation room requiring lossless zero-latency source routing, local inputs, and high-performance display feeds.",
    scale: "Mission-critical control room",
    summary: "Situation room template using NetworkHD 600 transceivers over a 10G AV network for high-performance routing.",
    customerNarrative:
      "The situation room can route critical sources, operator workstations, dashboards, maps, and live feeds to any display with a high-performance NetworkHD 600 architecture designed for low-latency operation.",
    architecture:
      "NetworkHD 600 transceivers are used at source workstations, behind displays, and at any local input positions. A 10G managed AV network provides the transport layer, with control presets for briefing, incident response, monitoring, and collaboration modes.",
    bom: [
      {
        id: "situationctl",
        sku: "NHD-CTL-PRO-V2",
        description: "NetworkHD controller",
        role: "NetworkHD routing and preset control",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "NetworkHD systems require a control layer for routing and endpoint management.",
        notes: "Validate control architecture and controller requirements for the final 600-series deployment.",
      },
      {
        id: "situation600src",
        sku: "NHD-600-TRX",
        description: "NetworkHD 600 10G transceiver",
        role: "Critical source endpoint",
        qty: 8,
        type: "Required",
        status: "included",
        evidence: "Assumes critical PCs, dashboards, map systems, and live source feeds.",
        notes: "Adjust to confirmed critical source count.",
      },
      {
        id: "situation600display",
        sku: "NHD-600-TRX",
        description: "NetworkHD 600 10G transceiver",
        role: "Display endpoint",
        qty: 12,
        type: "Required",
        status: "included",
        evidence: "Assumes main displays, operator displays, and briefing screens all require high-performance routing.",
        notes: "Adjust to confirmed display count and local input requirements.",
      },
      {
        id: "situationsyntouch",
        sku: "SYN-TOUCH10",
        description: "10-inch touch panel",
        role: "Situation room preset interface",
        qty: 2,
        type: "Validate",
        status: "validate",
        evidence: "Critical rooms require simple role-based presets such as Briefing, Incident, Monitor, Compare, and Secure.",
        notes: "Confirm whether WyreStorm control, third-party control, or secure customer control is required.",
      },
      {
        id: "situation10g",
        sku: "BY-OTHERS-10G-AV-SWITCH",
        description: "10G managed AV switch infrastructure",
        role: "Required 10G AV network",
        qty: 1,
        type: "Validate",
        status: "validate",
        evidence: "NetworkHD 600 requires suitable 10G switching infrastructure.",
        notes: "Validate switch capacity, topology, fibre/copper runs, VLANs, multicast, resilience, and commissioning access.",
      },
    ],
    designNotes: [
      { label: "Performance", description: "Use NetworkHD 600 where lossless, zero-latency, and high-performance routing are core requirements." },
      { label: "Endpoint roles", description: "A 600-TRX can be used at both source and display positions; behind-display local input use should be captured during discovery." },
      { label: "Control security", description: "Role-based control, source permissions, and secure operation modes must be agreed with the customer." },
      { label: "Network resilience", description: "Critical rooms may require resilient switching, UPS, redundant paths, and formal failover behaviour." },
    ],
    assumptions: ["Eight critical sources", "Twelve display endpoints", "10G AV network", "Preset-based secure control"],
    validationItems: ["10G network design", "Source sensitivity", "Endpoint count", "Control permissions", "Resilience/failover", "Rack and power strategy"],
    upgradePaths: ["Add more NHD-600-TRX endpoints for additional sources or displays", "Integrate with third-party control for secure workflows", "Create phased deployment for briefing room, operations room, and incident room areas"],
  }
];

export const roomTemplates: RoomTemplate[] = [...coreRoomTemplates, ...extraRoomTemplates];

export const roomTemplateVerticals = ["All", ...Array.from(new Set(roomTemplates.map((template) => template.vertical)))];
